- .github/workflows/generator.yaml
This is why I have not enabled these for PRs...
> ci: fix golang build step

- generator/README.md
- generator/src/genclient/genclient.go
- generator/src/genclient/language/internal/golang/golang.go
- generator/src/genclient/language/internal/rust/rust.go
- generator/src/genclient/templatedata.go
- generator/src/genclient/translator/protobuf/protobuf.go
- generator/templates/go/client.go.mustache
- generator/templates/rust/model.mustache
I did leave some breadcrumbs in the code still so we know where some of these changes should be made, but every todo now has a bug.
> chore: convert all todos to real bugs

- auth/src/source.rs
A user credentials file need not have a `quota_project_id` field.
> fix(auth): `quota_project_id` is optional

- generator/templates/rust/enum.mustache
- generator/testdata/rust/gclient/golden/model.rs
> fix: add additional slash in enum docs

- types/Cargo.toml
- types/src/field_mask.rs
- types/src/lib.rs
> impl(types): initial implementation for `FieldMask`

- .github/workflows/generator.yaml
- generator/internal/genclient/translator/protobuf/testdata/comments.proto
- generator/internal/genclient/translator/protobuf/testdata/oneofs.proto
- generator/internal/genclient/translator/protobuf/testdata/scalar.proto
- generator/internal/genclient/translator/protobuf/testdata/scalar_array.proto
- generator/internal/genclient/translator/protobuf/testdata/scalar_optional.proto
At least for any files that we manually write.
> ci: enforce proto file formatting

- generator/internal/genclient/translator/protobuf/protobuf.go
- generator/internal/genclient/translator/protobuf/protobuf_test.go
> fix(internal/genclient): use service config name

- .github/workflows/generator.yaml
- .github/workflows/lint.yaml
- .github/workflows/sdk.yaml
- types/src/any.rs
- types/src/duration.rs
Evidently I don't know how they work, because I was treating them as regular expressions.
> ci: globs, how do they work?

- generator/templates/rust/src/enum.mustache
- generator/templates/rust/src/model.mustache
- generator/templates/rust/src/oneof.mustache
- generator/testdata/rust/gclient/golden/src/model.rs
- generator/testdata/rust/openapi/golden/src/model.rs
> impl(generator/rust): consistent trait implementation

- generator/internal/genclient/language/internal/rust/rust.go
- generator/templates/rust/src/lib.rs.mustache
> feat(generator/rust): use gax helpers for path parameters

- generator/testdata/rust/gclient/golden/src/lib.rs
- generator/testdata/rust/gclient/golden/src/model.rs
- generator/testdata/rust/gclient/protos/service.proto
> test(generator/protobuf): larger golden files

- generator/testdata/rust/gclient/golden/src/lib.rs
I did an oopsie.  I merged two PRs that changed the golden files without
rebasing first.
> fix(generator): regenerate golden files post merge

- generator/testdata/rust/gclient/golden/src/lib.rs
- generator/testdata/rust/gclient/protos/service.proto
Fixes #157, also related to #37.
> test(generator/rust): use google.protobuf.Empty in golden files

- Cargo.lock
- Cargo.toml
- generator/cmd/main_test.go
- generator/testdata/rust/gclient/golden/type/Cargo.toml
- generator/testdata/rust/gclient/golden/type/README.md
- generator/testdata/rust/gclient/golden/type/src/lib.rs
- generator/testdata/rust/gclient/golden/type/src/model.rs
> test(googletest/rust): generate the type golden crate

- generator/internal/genclient/language/internal/rust/rust.go
- generator/internal/genclient/language/internal/rust/rust_test.go
- generator/internal/genclient/parser/openapi/openapi.go
- generator/testdata/rust/gclient/golden/secretmanager/src/model.rs
- generator/testdata/rust/openapi/golden/src/model.rs
- types/tests/message_with_map.rs
Serializing and deserializing maps requires special serde attributes.
Fixes #202
> feat(generator/rust): add map attributes

- Cargo.lock
- gax/Cargo.toml
- gax/src/error/error.rs
- gax/src/error/http_error.rs
- gax/src/error/mod.rs
- gax/src/error/rpc/mod.rs
- gax/tests/errors.rs
> feat(gax): add a common HTTP response error

- gax/src/error/mod.rs
- gax/src/request_parameter.rs
- generator/internal/genclient/language/internal/rust/rust.go
- generator/templates/rust/crate/src/lib.rs.mustache
- generator/testdata/rust/gclient/golden/iam/v1/src/lib.rs
- generator/testdata/rust/gclient/golden/secretmanager/src/lib.rs
- generator/testdata/rust/openapi/golden/src/lib.rs
> feat(generator): use new Rust error types

- types/src/field_mask.rs
Clippy told me my test was not doing what I tought it did, and when I
fixed the test I found a bug.
> fix(wkt): handle empty fieldmask

- src/integration-tests/src/lib.rs
- src/integration-tests/tests/driver.rs
- src/integration-tests/tests/secret_manager_openapi.rs
- src/integration-tests/tests/secret_manager_protobuf.rs
> refactor: split secretmanager integration tests

- Cargo.lock
- generator/testdata/rust/gclient/golden/location/.sidekick.toml
- generator/testdata/rust/gclient/golden/location/Cargo.toml
Merged the gax move and the new location golden files at the same time. Tsck tsck.
> fix: repair merge problem

- .gcb/builds/grants/main.tf
- .gcb/builds/main.tf
- .gcb/builds/triggers/main.tf
Create the GCB triggers. Run the integration tests on each PR and push.
> ci(gcb): create and enable the triggers

- src/integration-tests/src/secret_manager/openapi_locational.rs
- src/integration-tests/src/secret_manager/protobuf.rs
- src/wkt/src/duration.rs
- src/wkt/src/timestamp.rs
- src/wkt/tests/duration.rs
- src/wkt/tests/timestamp.rs
> feat(wkt): compare timestamps and durations

- src/wkt/src/lib.rs
- src/wkt/src/wrappers.rs
- src/wkt/tests/wrappers.rs
> feat(wkt): support wrapper messages

- generator/internal/genclient/language/internal/rust/rust.go
- generator/internal/genclient/language/internal/rust/rust_test.go
> feat(generator): support well-known wrapper messages

- generator/sidekick/sidekick_test.go
- generator/templates/rust/crate/Cargo.toml.mustache
- generator/templates/rust/crate/README.md.mustache
- generator/testdata/rust/gclient/golden/iam/v1/Cargo.toml
- generator/testdata/rust/gclient/golden/iam/v1/README.md
- generator/testdata/rust/gclient/golden/location/Cargo.toml
- generator/testdata/rust/gclient/golden/location/README.md
- generator/testdata/rust/gclient/golden/secretmanager/Cargo.toml
- generator/testdata/rust/gclient/golden/secretmanager/README.md
- generator/testdata/rust/gclient/golden/type/.sidekick.toml
- generator/testdata/rust/gclient/golden/type/Cargo.toml
- generator/testdata/rust/gclient/golden/type/README.md
- generator/testdata/rust/openapi/golden/Cargo.toml
- generator/testdata/rust/openapi/golden/README.md
Make the description in the generated `Cargo.toml` and the `README.md`
files consistent.
> feat(generator/rust): consistent descriptions

- generator/internal/genclient/model.go
- generator/internal/genclient/parser/openapi/openapi.go
- generator/internal/genclient/parser/openapi/openapi_test.go
- generator/internal/genclient/parser/protobuf/protobuf.go
- generator/internal/genclient/parser/protobuf/protobuf_test.go
These will soon be used by mixin code as well.
> refactor(generator): add helpers for processing services/methods

- .github/workflows/sdk.yaml
Introduce a new build that generates all the clients and detects any
differences between the commited and generated code.
> ci: verify generated files are in sync

- generator/internal/language/common.go
- generator/internal/parser/openapi/openapi.go
- generator/internal/parser/protobuf/protobuf.go
Package internal/language/common current contains one file with two functions. Merge this code into internal/language to reduce nesting.
> impl(internal/language): merge internal/language/common

- generator/internal/sidekick/cmdline_test.go
- generator/internal/sidekick/sidekick_test.go
Refactor tests to extract shared testing data into variables.
> impl(internal/sidekick): extract shared testing data into variables

- src/generated/openapi-validation/.sidekick.toml
- src/generated/openapi-validation/Cargo.toml
> chore: disable publication of test-only crate

- src/wkt/src/any.rs
- src/wkt/src/duration.rs
- src/wkt/src/lib.rs
- src/wkt/src/timestamp.rs
- src/wkt/tests/timestamp.rs
Document all public APIs, including errors. Add a brief description of the crate.
> docs(wkt): fill out documentation

- .sidekick.toml
- src/generated/iam/v1/src/model.rs
Ran this command:
```shell
go -C generator/ run ./cmd/sidekick -project-root .. update && \
taplo fmt .sidekick.toml && \
cargo fmt
```
> chore: update googleapis SHA circa 2024-12-10

- src/gax/src/query_parameter.rs
> docs(gax): fix broken rustdoc links

- doc/contributor/howto-guide-generated-code-maintenance.md
- doc/contributor/howto-guide-set-up-development-environment.md
I think we can start reviewing these guides while the PRs to simplify the maintenance commands are going through reviews.
> docs: initial contributor guides

- generator/internal/language/rust.go
The function was getting too long and hard to grok.
> refactor(generator/rust): split option parsing

- Cargo.lock
- auth/Cargo.toml
> chore(deps): update chrono to 0.4.39

- Cargo.lock
- auth/Cargo.toml
- auth/src/source.rs
> chore(deps): update rustls-pemfile to 2.2

- Cargo.lock
- auth/Cargo.toml
- auth/src/source.rs
> chore(deps): update rustls to 0.23.20

- Cargo.lock
Just run `cargo update` and send a PR with those results.
> chore(deps): update Cargo.lock file

- .github/dependabot.yml
> chore(deps): automate dependency updates

- .github/dependabot.yml
Argh... I had the wrong config:
https://github.com/googleapis/google-cloud-rust/network/updates
Hopefully I got it right this time.
> chore(deps): fix dependabot config

- src/auth/src/credentials/user_credential.rs
Implement the `get_headers()` function (based on the `get_token()` function) for user credentials.
Note that we set the header as sensitive, which is what `reqwest::RequestBuilder::bearer_auth(...)` does: https://docs.rs/reqwest/0.12.9/src/reqwest/async_impl/request.rs.html#270. (I could not find a public ctor that took `is_sensitive`, so we do it in two lines).
---
Is there a better way to set test expectations on a container?
TIL: `map_err()`. Check me on my error propagation.
> impl(auth): get_headers for user credentials

- src/gax/src/paginator.rs
Added some helpers to simplify generated code.
Usage in generated clients would be something like:
```rust
gax::paginator::extract_token(&req.page_token)
```
Updates: #297
> feat(gax): add helpers for extracting pagination tokens from reqs

- .sidekick.toml
- Cargo.lock
- generator/internal/language/rust.go
- generator/testdata/rust/gclient/golden/iam/v1/Cargo.toml
- generator/testdata/rust/gclient/golden/location/Cargo.toml
- generator/testdata/rust/gclient/golden/secretmanager/Cargo.toml
- generator/testdata/rust/openapi/golden/Cargo.toml
- src/generated/cloud/location/Cargo.toml
- src/generated/cloud/secretmanager/v1/Cargo.toml
- src/generated/iam/v1/Cargo.toml
- src/generated/openapi-validation/Cargo.toml
- src/generated/rpc/Cargo.toml
- src/generated/type/Cargo.toml
> feat(generator/rust): prune nosvc packages

- generator/internal/parser/protobuf.go
Do not warn on comments that we won't use anyway.
> cleanup(generator): fewer spurious warnings

- .codecov.yml
- .github/workflows/sdk.yaml
- doc/contributor/howto-guide-set-up-development-environment.md
Ignore generated code and integration tests.
Fixes #463
> ci: code coverage build and reporting

- src/wkt/src/any.rs
- src/wkt/src/duration.rs
- src/wkt/src/field_mask.rs
- src/wkt/src/timestamp.rs
Add a number of missing test cases, and fix the bugs uncovered in the
process.
> test(wkt): add missing tests

- src/wkt/src/any.rs
Use a narrower type for `Any`'s implementation. That reduces the amount
of error checking and testing we need to do.
> fix(wkt): tighter types for `Any`

- Cargo.lock
- src/gax/Cargo.toml
- src/gax/echo-server/Cargo.toml
- src/gax/echo-server/src/lib.rs
- src/gax/tests/http_client_errors.rs
- src/gax/tests/timeout.rs
- src/gax/tests/user_agent.rs
With some amount of refactoring.
> test(gax): missing tests for `http_client`

- src/auth/src/credentials/mds_credential.rs
- src/auth/src/credentials/user_credential.rs
- src/gax/echo-server/src/lib.rs
- src/gax/tests/paginator.rs
The wildcard address (0.0.0.0:0) does not work on GitHub actions +
Windows.
> test: use 127.0.0.1 to start test servers

- src/auth/src/credentials/user_credential.rs
Part of the work for #442
Add an internal function to parse `authorized_user` credentials json.
Soon (in the next PR, I think) we can undead the code.
> impl(auth): parse user credentials from json

- src/auth/src/credentials/mds_credential.rs
Part of the work for https://github.com/googleapis/google-cloud-rust/issues/442
Add an implementation for fetching token from mds server
Error handling
I am aware of https://github.com/googleapis/google-cloud-rust/issues/389. We should probably start tracking error kinds. I didn't do it in this PR.
Unit tests
I made a fake server similar to https://github.com/googleapis/google-cloud-rust/pull/489 and tested the cases for getting token.
Integration tests?
There are none. I did manually tested the cloud on my gce vm and verified I was able to fetch back token
> impl(auth): Implement fetching token from mds server

- generator/internal/sidekick/generate.go
The golden files should not change just because it is a new year.
> test(generator): fix copyright year for golden files

- .github/workflows/sdk.yaml
As @dbolduc predicted, this can be simplified using a build matrix.
> ci: refactor platform builds

- src/auth/README.md
- src/auth/src/lib.rs
- src/gax/README.md
- src/gax/src/lib.rs
- src/wkt/README.md
- src/wkt/src/lib.rs
These are for hand-crafted files.
> docs: add "under development" disclaimers

- src/gax/src/retry_policy.rs
When a retry attempt is throttled the retry policy needs to make
slightly different decisions. For example, when limiting the number
of attempts these do not count as an attempt.
Part of the work for #437
> feat(gax): retry policies and throttled attempts

- Cargo.lock
- src/auth/Cargo.toml
Just run `cargo update` and find out what needs fixing.
> chore: update dependencies

- src/gax/tests/auth.rs
> cleanup(auth): use mock credentials in gax unit test

- src/wkt/src/any.rs
`Duration`, `Timestamp`, and `FieldMask` need special code to extract
from `Any`. But `Empty` does not, the exception to the exception I
guess.
> fix(wkt): extract `Empty` from `Any`

- src/wkt/src/any.rs
I will need to return these errors (after some wrapping) in async
functions. That requires `Send` and `Sync`.
Motivated by #438
> feat(wkt): make `any::AnyError` `Send` and `Sync`

- src/wkt/Cargo.toml
- src/wkt/src/any.rs
- src/wkt/tests/any.rs
> feat(wkt): validate message typenames

- src/auth/src/credentials/user_credential.rs
Motivated by #651 
We will want `AuthorizedUser` to hold the `quota_project_id`. It does not belong to the `UserTokenProvider`. So going directly from `serde_json::Value` -> `UserTokenProvider` doesn't make sense.
Add a test for missing optional fields in the user credentials json.
And some minor cleanups around local variable names.
> refactor(auth): prepare to support quota project in UC

- src/gax/src/http_client/mod.rs
> cleanup(gax): simplify `ReqwestClient` debug

- src/gax/src/retry_policy.rs
This is useful to not retry when then client already has a retry policy
configured. In particular, I am planning to use this in calls to
`get_operation()` for LROs. The client may already have a retry policy
and we do not need to retry the requests to query the LRO.
Fixes #684
> feat(gax): a `NeverRetry` retry policy

- generator/internal/language/rust_test.go
Rewrite TestRust_EnumNames as a parameterized test.
> impl(language): rewrite TestRust_EnumNames

- src/auth/src/credentials/mds_credential.rs
- src/auth/src/credentials/user_credential.rs
Do a pass on retrying, mainly in User Credentials.
Retry I/O errors: `builder.send()`, `response.text()`
My read of `reqwest::Response::json<>` is that we should retry if `reqwest::Response::bytes()` fails, but we should not retry if the deserialization into json fails.
https://docs.rs/reqwest/0.12.12/src/reqwest/async_impl/response.rs.html#268-270
> impl(auth): more retrying?

- Cargo.lock
- generator/internal/language/rusttemplate.go
- generator/internal/language/templates/rust/common/Cargo.toml.mustache
- generator/internal/language/templates/rust/crate/src/client.rs.mustache
- src/generated/cloud/workflows/v1/Cargo.toml
- src/generated/cloud/workflows/v1/src/client.rs
> feat(generator): make LRO examples testable

- src/lro/src/details.rs
- src/lro/src/lib.rs
Use the polling policy to decide if a polling error is recoverable.
Fixes #714
> feat(lro): use polling policy on errors

- generator/internal/language/templates/rust/crate/src/builders.rs.mustache
- generator/testdata/rust/openapi/golden/src/builders.rs
- generator/testdata/rust/protobuf/golden/iam/v1/src/builders.rs
- generator/testdata/rust/protobuf/golden/location/src/builders.rs
- generator/testdata/rust/protobuf/golden/secretmanager/src/builders.rs
- src/generated/cloud/location/src/builders.rs
- src/generated/cloud/secretmanager/v1/src/builders.rs
- src/generated/cloud/workflows/v1/src/builders.rs
- src/generated/iam/v1/src/builders.rs
- src/generated/longrunning/src/builders.rs
- src/generated/openapi-validation/src/builders.rs
> feat(generator): add method to change all options

- generator/internal/language/templates/rust/crate/src/builders.rs.mustache
- src/generated/cloud/workflows/v1/src/builders.rs
- src/lro/tests/fake_library/builders.rs
> feat(generator): set options on LRO polling

- generator/internal/language/templates/rust/crate/src/client.rs.mustache
- src/generated/cloud/workflows/v1/src/client.rs
> feat(generator): add `until_done()` examples

- src/auth/src/credentials/util/jws.rs
> test(auth): deflake jws test

- generator/internal/language/rust.go
> fix(generator): mixins may enable streaming features

- src/wkt/src/lib.rs
- src/wkt/src/rstruct.rs
> feat(wkt): implement `Struct` and friends

- src/gax/src/query_parameter.rs
- src/gax/src/request_parameter.rs
> cleanup(gax): unused code around query parameters

- generator/internal/language/rust.go
> feat(generator/rust): Struct is a well-known type

- generator/internal/language/rusttemplate.go
> feat(generator/rust): skip empty services

- src/auth/src/credentials/user_credential.rs
Motivated by #797 
Print more information if something goes wrong in the user credentials unit tests.
> test(auth): more info if tests fail

- generator/internal/api/model.go
- generator/internal/language/codec.go
- generator/internal/language/gotemplate.go
- generator/internal/language/rust.go
- generator/internal/language/rusttemplate.go
- generator/internal/language/templates/go/message.mustache
- generator/internal/language/templates/rust/common/message.mustache
- generator/internal/language/templates/rust/crate/src/builders.rs.mustache
> cleanup(generator): use annotations for messages

- .sidekick.toml
- .typos.toml
- src/generated/cloud/scheduler/v1/src/model.rs
This unblocks #782, and clears some typos for #830
> chore: update googleapis circa 2025-01-28

- generator/internal/language/rust.go
- generator/internal/language/rust_test.go
- generator/internal/language/rusttemplate_test.go
> feat(generator/rust): oneof fields as query parameters

- generator/internal/language/rust.go
- generator/internal/language/rust_test.go
> feat(generator/rust): repeated wrapper encoding

- src/wkt/tests/wrappers.rs
> test(wkt): encoding for repeated `*Value` wrappers

- src/auth/src/credentials.rs
- src/auth/src/credentials/service_account_credential.rs
- src/auth/tests/credentials.rs
Part of the work for #679 and #806 
Support service account ADC.
> feat(auth): SA creds

- src/integration-tests/src/secret_manager/protobuf.rs
- src/integration-tests/tests/pagination.rs
> test: verify streaming pagination works

- .github/workflows/lint.yaml
- doc/contributor/howto-guide-set-up-development-environment.md
- src/auth/.gcb/builds/main.tf
- src/auth/.gcb/builds/service_account_test/main.tf
- src/auth/.gcb/builds/triggers/main.tf
> ci: format terraform files

- .github/workflows/sdk.yaml
> ci: speedup coverage build

- guide/samples/Cargo.toml
- guide/samples/src/bin/getting_started.rs
- guide/src/SUMMARY.md
- guide/src/setting_up_rust_on_cloud_shell.md
- guide/src/setting_up_your_development_environment.md
> docs: add set up guides

- generator/internal/parser/protobuf.go
- generator/internal/parser/protobuf_mixin_test.go
- generator/internal/parser/testdata/test_duplicate_mixin.proto
> feat(generator/protobuf): support duplicate mixins

- generator/internal/rust/rust.go
- generator/internal/rust/rust_used_by_test.go
> feat(generator/rust): use packages for OperationInfo

- Cargo.lock
- guide/samples/Cargo.toml
- guide/samples/src/lib.rs
- guide/samples/src/polling_policies.rs
- guide/samples/tests/driver.rs
- guide/src/SUMMARY.md
- guide/src/configuring_polling_policies.md
- guide/src/initialize_a_client.md
- guide/src/working_with_long_running_operations.md
> docs(guide): chapter on polling policies

- .github/workflows/generator_dart.yaml
- generator/internal/sidekick/sidekick_dart_test.go
- generator/testdata/dart/protobuf/golden/secretmanager/.sidekick.toml
> cleanup(generator): simplify Dart tests

- src/auth/.gcb/builds/api_key_test/main.tf
- src/auth/.gcb/builds/main.tf
- src/auth/.gcb/builds/triggers/main.tf
- src/auth/integration-tests/README.md
Part of the work for #1371 
Manages the resources used in #1376 
While we are here, add a snippet to the README on how to destroy resources in your local project.
> ci(auth): api key terraform

- src/wkt/src/generated/.sidekick.toml
- src/wkt/src/generated/mod.rs
Just use the generated type. Part of the work for #37.
> feat(wkt): add `DescriptorProto`

- src/wkt/src/rstruct.rs
> cleanup(wkt): `NullValue` cannot go into `Any`

- src/wkt/src/duration.rs
- src/wkt/tests/duration.rs
- src/wkt/tests/oneofs.rs
> fix(wkt): no trailing zeroes in duration as JSON

- .github/workflows/lint.yaml
> ci: update and pin `cargo-cli`

- generator/internal/parser/protobuf.go
- generator/internal/protobuf/input_files.go
I will need this function in the Rust+Prost codec.
> refactor(generator): move `DetermineInputFiles`

- generator/internal/rust/rusttemplate.go
Prefer `codec` methods for all the annotation functions. As we add
configuration options and attributes controlling the annotations it is
tedious to keep adding parameters to these functions.
Motivated by #1379
> refactor(generator/rust): more codec methods

- src/firestore/src/generated/model/.sidekick.toml
- src/firestore/src/generated/model/mod.rs
These templates include helpers needed for Prost <=> Sidekick conversions.
> impl(firestore): use `mod-prost` templates

- generator/internal/rust/codec.go
> feat(generator/rust): more well-known types

- src/firestore/src/lib.rs
- src/firestore/src/status.rs
> impl(firestore): convert functions `google.rpc.Status`

- generator/internal/parser/protobuf_test.go
- generator/internal/parser/testdata/map_fields.proto
- generator/internal/rust/annotate.go
- generator/internal/rust/annotate_test.go
- generator/internal/rust/codec.go
- generator/internal/rust/templates/convert-prost/message.mustache
- generator/internal/rust/templates/convert-prost/oneof.mustache
> feat(generator/rust): convert enum types

- .github/workflows/sdk.yaml
- src/gax-internal/Cargo.toml
- src/gax-internal/src/lib.rs
- src/gax-internal/tests/auth.rs
- src/gax-internal/tests/http_client_errors.rs
- src/gax-internal/tests/http_client_polling.rs
- src/gax-internal/tests/paginator.rs
- src/gax-internal/tests/query_parameters.rs
- src/gax-internal/tests/retry_loop.rs
- src/gax-internal/tests/timeout.rs
- src/gax-internal/tests/user_agent.rs
> impl(gax-internal): feature gate all components

- generator/internal/golang/gotemplate.go
- generator/internal/rust/annotate.go
- update the names of a few OneOf local variables (which I believe had been copy-pasted from iterating over fields)
> refactor(generator): update names of 'oneof' variables

- src/auth/src/credentials/service_account_credential.rs
> cleanup: post-merge review comments

- Cargo.lock
- guide/samples/Cargo.toml
- guide/samples/tests/mocking_lros.rs
- guide/samples/tests/mocking_lros_auto.rs
- guide/samples/tests/mocking_lros_manual.rs
- guide/src/SUMMARY.md
- guide/src/mocking_lros.md
- guide/src/working_with_long_running_operations.md
Part of the work for #1661  (we would also like a section on returning errors)
Looks like: [mocking_lros.pdf](https://github.com/user-attachments/files/19593022/mocking_lros.pdf)
> docs: user guide for testing LROs

- src/auth/src/credentials.rs
- src/auth/src/credentials/mds.rs
- src/auth/tests/credentials.rs
- src/gax-internal/tests/auth.rs
Part of making the auth methods rusty
> fix(auth): Rename get_universe_domain to universe_domain

- Cargo.lock
- src/auth/Cargo.toml
Removing unused unstable dependency.
> cleanup(auth): Remove unused dependency derive_builder

- generator/dart/generated/google_cloud_functions_v2/lib/cloudfunctions.dart
- generator/internal/dart/templates/lib/method.mustache
- refactor the method.mustache template for readability
- a follow-up to https://github.com/googleapis/google-cloud-rust/pull/1795
> refactor(generator/dart): refactor the method.mustache template for readability

- doc/contributor/howto-guide-generated-code-maintenance.md
- generator/doc/contributor/howto-guide-new-sidekick-codec.md
@coryan smote the golden files
> cleanup: no more golden files

- src/gax-internal/src/http.rs
> cleanup(gaxi): tuple names

- src/gax-internal/src/grpc.rs
Just pass along a `grpc::Client`. That is what we do in the HTTP client.
We are cloning the policies for the `self` that does a single request attempt. Sure, that is extra work, but it is negligible. These things are `Option<Arc<...>>`s. They are cheap to clone (we clone them for every single operation).
> refactor(gaxi): grpc request_attempt as member

- src/gax-internal/src/prost.rs
I suspect this will simplify generated code.
> impl(gaxi): `Convert` for unit type

- .github/workflows/sdk.yaml
- Cargo.toml
> ci(gha): reduce disk space requirements

- Cargo.lock
- src/integration-tests/Cargo.toml
- src/integration-tests/tests/idempotency.rs
> test: verify default idempotency

- generator/internal/dart/annotate.go
- switch many 'HasXxx' annotations on model objects over to using methods
- related to https://github.com/googleapis/google-cloud-rust/issues/1854
It would also be possible to move the `HasServices()` method up from being defined on the Dart (and Rust) model annotations, to being defined against the api.API struct itself - to extract out some common methods.
> refactor(generator/dart): prefer methods for model annotations

- Cargo.lock
- guide/samples/Cargo.toml
- guide/samples/src/gemini.rs
- guide/samples/src/lib.rs
- guide/samples/tests/driver.rs
- guide/src/SUMMARY.md
- guide/src/generate_text_using_the_vertex_ai_gemini_api.md
Demonstrate the client libraries AI superpowers and how to use feature-gated clients (though this is not highlighted a lot).
Motivated by #1863
> docs: add user guide section on Vertex AI

- src/gax/src/paginator.rs
- src/integration-tests/tests/pagination.rs
> fix(gax): paginators should be `Send`

- src/lro/src/lib.rs
- src/lro/tests/integration.rs
Motivated by #1915
Sadly I did not send this PR at 11:11, that would be been neat.
> fix(lro): `Poller` should be `Send`

- generator/internal/api/model.go
- generator/internal/parser/openapi.go
- generator/internal/parser/openapi_behavior.go
- generator/internal/parser/openapi_test.go
- generator/internal/parser/protobuf.go
- generator/internal/parser/protobuf_behavior.go
- generator/internal/parser/protobuf_test.go
This just captures the annotations. Future PRs will use them to change
the generated code.
Fixes #1937
> feat(generator): field behavior annotations

- guide/samples/Cargo.toml
- guide/src/error_handling.md
- guide/src/working_with_long_running_operations.md
> docs: add explicit dep to the guides

- Cargo.toml
- src/wkt/Cargo.toml
- src/wkt/src/internal.rs
- src/wkt/src/internal/enums.rs
> impl(wkt): support types for "enums take 3"

- src/wkt/tests/message_with_bytes.rs
- src/wkt/tests/message_with_i64.rs
> test: skip serializing default values in wkt tests

- src/storage-control/src/generated/gapic/.sidekick.toml
- src/storage-control/src/generated/gapic/client.rs
Noticed while working on #1813
> cleanup(storage): load service config

- src/wkt/src/wrappers.rs
Use the custom serialization and deserialization of f32 in the wrapper type.
For #1767
> fix: add custom serde for FloatValue

- src/auth/integration-tests/tests/driver.rs
> test(auth): disable flaky test

- generator/internal/rust/templates/convert-prost/message.mustache
- src/firestore/src/generated/convert/firestore/convert.rs
- src/firestore/src/generated/convert/rpc/convert.rs
- src/storage-control/src/generated/convert/iam/convert.rs
- src/storage-control/src/generated/convert/storage/convert.rs
Another pass on simplifying the field classification. I just missed
these on the previous pass. Fortunately, there are not that many of
them.
> cleanup(generator/rust): field classification

- .github/workflows/lint.yaml
- doc/contributor/howto-guide-set-up-development-environment.md
This is what we run in our CI.
I am considering adding scripts for each of these commands that we would reference here and call from our CI. Then this stuff will not fall out of sync.
> cleanup: update local format commands

- Cargo.lock
- src/integration-tests/Cargo.toml
- src/integration-tests/tests/serialization.rs
Was not able to find examples to use in the existing dependencies, so pulled in the aiplatform package as well.
For #1767
> test: add integration tests for custom serialization

- src/lro/src/details.rs
- src/lro/src/internal.rs
> feat(lro): convert `wkt::Empty` to unit type

- generator/internal/rust/annotate_test.go
> test: update map oneof test to include serde attribute

- Cargo.toml
- src/gax/Cargo.toml
> cleanup(gax): use workspace dependencies

- Cargo.lock
- Cargo.toml
- src/wkt/Cargo.toml
> cleanup(wkt): use workspace dependencies

- src/lro/Cargo.toml
> cleanup(lro): use workspace dependencies

- Cargo.lock
- Cargo.toml
- src/integration-tests/Cargo.toml
> cleanup(integration-tests): use workspace dependencies

- guide/src/setting_up_your_development_environment.md
> docs: add instructions for adding google-cloud-gax crate

- Cargo.lock
- Cargo.toml
- src/auth/Cargo.toml
- src/auth/integration-tests/Cargo.toml
> cleanup(auth): use workspace dependencies

- src/integration-tests/src/sql.rs
> test(integration-tests): disable flaky assertions

- .github/workflows/sdk.yaml
- Cargo.lock
- src/integration-tests/Cargo.toml
- src/integration-tests/src/lib.rs
- src/integration-tests/src/showcase.rs
- src/integration-tests/tests/driver.rs
- src/integration-tests/tests/showcase.rs
Introduce a way to run the showcase server and write some basic tests.
Part of the work for #482
> test(showcase): bootstrap testing

- src/wkt/src/timestamp.rs
This suggests ergonomic improvement to `TryFrom<>`, and that is a
breaking change.
Fixes #2182
> feat(wkt)!: `Timestamp` can implement `Copy`

- src/wkt/src/duration.rs
That suggests improvements in the `From<>` implementations, and those
are breaking.
Fixes #2183
> feat(wkt)!: `Duration` can implement `Copy`

- src/wkt/src/duration.rs
- src/wkt/src/timestamp.rs
> feat(wkt): implement `TryFrom<&String>`

- src/gax/src/polling_error_policy.rs
- src/gax/src/retry_policy.rs
- src/gax/src/retry_throttler.rs
I was reading the documentation again and cleaned up some of the
examples to have less boilerplate at the top. Fixed other nits too.
> docs(gax): improve some examples

- src/storage/src/client.rs
> impl(storage): add owner, metadata, and encryption fields to v1::Object

- guide/samples/tests/mocking.rs
- guide/samples/tests/mocking_lros_error.rs
- src/gax-internal/src/grpc/from_status.rs
- src/gax-internal/src/http.rs
- src/gax/src/error/service_error.rs
> cleanup(gax)!: use builder for `ServiceError`

- Cargo.lock
- src/storage/Cargo.toml
- src/storage/src/client.rs
> impl(storage): add checksum fields to v1::Object

- .github/workflows/sdk.yaml
> ci: update windows build

- src/gax/src/error/credentials.rs
This was returning a reference to `Arc<T>`, but we really wanted a
reference to `T`, the original error source.
Found while fixing #2221, but otherwise unrelated.
> fix(gax): correct `source()` in `CredentialsError`

- generator/internal/rust/annotate.go
- generator/internal/rust/annotate_test.go
- generator/internal/rust/codec.go
- generator/internal/rust/codec_test.go
- src/storage-control/src/generated/gapic/.sidekick.toml
> feat(generator): deconflict oneof names

- src/storage/src/client.rs
It is not idiomatic to use the fully qualified path for these from std.
Follow up from #2263
> impl(storage): cleanup fully qualified Option, Into, From and String

- src/storage/src/client.rs
> cleanup: add example to ReadObject documentation

- Cargo.lock
- src/storage/Cargo.toml
- src/storage/src/client.rs
> test(storage): add simple read object test

- src/storage/src/client.rs
> feat(storage): support additional query parameters in read_object

- src/storage/src/client.rs
> impl(storage): return unimplemented error when unused param is set

- src/storage/src/client.rs
> test(storage): add test for read_object with error credentials

- src/gax/src/error/core_error.rs
Most of our error kinds have a source, so we can refactor that to an
`Option<BoxError>`. Also refactor the details for transport and service
errors to (private) structs, so they are easier to work with.
These changes will make it easier to add more specific errors for
deserialization, unimplemented functions, and other branches we need to
handle.
Motivated by #2312
> refactor(gax): simplify `Error` implementation

- src/auth/src/credentials.rs
- src/auth/src/credentials/external_account.rs
Towards https://github.com/googleapis/google-cloud-rust/issues/2079
> feat(auth): add external account for workload identity federation

- src/auth/src/token_cache.rs
Fixes #2309 
Relax expectations around thundering herds.
We would get a false positive if 100 tasks could not launch within 50ms. Now we will get a false positive if 100 tasks cannot launch within 500ms.
> ci(auth): deflake token cache thundering herd tests

- src/gax/src/error/core_error.rs
> docs(gax): improve `Error` documentation

- src/auth/src/credentials.rs
- src/auth/src/credentials/external_account.rs
- src/auth/src/credentials/external_account_sources.rs
- src/auth/src/credentials/external_account_sources/url_sourced.rs
- src/auth/src/credentials/external_account_sources/url_sourced_account.rs
> feat(auth): add support for url sourced credentials

- src/integration-tests/src/storage.rs
- src/storage/src/client.rs
> fix(storage)!: add required parameters to initial builder

- src/wkt/src/internal.rs
- src/wkt/tests/message_with_f32.rs
- src/wkt/tests/message_with_f64.rs
> impl(wkt): parse floats from strings

- src/wkt/src/internal.rs
- src/wkt/src/internal/int32.rs
- src/wkt/src/internal/uint32.rs
- src/wkt/src/internal/visitor_32.rs
> impl(wkt): custom encoding for `u32`

- Cargo.lock
- Cargo.toml
- src/storage-control/Cargo.toml
- src/storage-control/tests/mocking.rs
TYL: `paste` - https://docs.rs/paste/latest/paste/
> cleanup(storage-control): macro for repetitive tests

- generator/internal/rust/codec.go
- src/generated/api/types/src/model.rs
- src/generated/appengine/v1/src/model.rs
- src/generated/cloud/alloydb/v1/src/model.rs
- src/generated/cloud/bigquery/v2/src/model.rs
- src/generated/cloud/certificatemanager/v1/src/model.rs
- src/generated/cloud/dataplex/v1/src/model.rs
- src/generated/cloud/edgenetwork/v1/src/model.rs
- src/generated/cloud/networksecurity/v1/src/model.rs
- src/generated/cloud/networkservices/v1/src/model.rs
- src/generated/cloud/sql/v1/src/model.rs
- src/generated/showcase/src/model.rs
- src/protojson-conformance/src/generated/test_protos/mod.rs
- src/storage-control/src/generated/gapic/model.rs
- src/wkt/tests/generated/mod.rs
- src/wkt/tests/generated/primitive_types.proto
- src/wkt/tests/message_with_u32.rs
> impl(generator/rust): custom encoding for `u32`

- src/storage/src/client.rs
> test(storage): add tests for Storage::insert_object

- Cargo.lock
- src/integration-tests/src/storage.rs
- src/storage/Cargo.toml
- src/storage/src/client.rs
> fix(storage): use new type KeyAes256 for customer supplied encryption key

- generator/internal/rust/templates/common/deser_with_message_field.mustache
- generator/internal/rust/templates/common/ser_with_message_field.mustache
- src/wkt/tests/common/src/generated/mod.rs
- src/wkt/tests/message_with_bytes.rs
- src/wkt/tests/message_with_f32.rs
- src/wkt/tests/message_with_f64.rs
- src/wkt/tests/message_with_i32.rs
- src/wkt/tests/message_with_i64.rs
- src/wkt/tests/message_with_u32.rs
- src/wkt/tests/message_with_u64.rs
Generate serialization and deserialization functions for repeated fields
that need some kind of transformation.
> impl(generator): repeated fields with custom serde

- generator/internal/rust/annotate.go
- generator/internal/rust/annotate_test.go
- generator/internal/rust/templates/common/deser_with_message_field.mustache
- generator/internal/rust/templates/common/ser_with_message_field.mustache
- src/wkt/tests/common/src/generated/mod.rs
- src/wkt/tests/message_with_bytes.rs
- src/wkt/tests/message_with_f32.rs
- src/wkt/tests/message_with_f64.rs
- src/wkt/tests/message_with_i32.rs
- src/wkt/tests/message_with_i64.rs
- src/wkt/tests/message_with_u32.rs
- src/wkt/tests/message_with_u64.rs
Implement serialization and deserialization for maps where at least one
of the fields requires a custom transform.
> feat(generator): maps with custom serde

- src/auth/integration-tests/src/lib.rs
- src/auth/integration-tests/tests/driver.rs
Depends on https://github.com/googleapis/google-cloud-rust/pull/2420
> test(auth): integration tests for exec sourced external account

- generator/internal/rust/annotate.go
- generator/internal/rust/templates/common/deser_field_tag.mustache
- generator/internal/rust/templates/common/deser_plain_message_field.mustache
- src/wkt/tests/common/src/generated/mod.rs
- src/wkt/tests/message_with_value.rs
> impl(generator): generated serde for `wkt::Value`

- generator/internal/rust/annotate.go
- src/wkt/tests/common/src/generated/mod.rs
- src/wkt/tests/message_with_bool.rs
> impl(generator): transform bool map keys

- src/generated/showcase/.sidekick.toml
- src/generated/showcase/src/model.rs
> impl(showcase): use generated `serde`

- src/gax-internal/src/path_parameter.rs
When constructing the path, we need to check if fields in a request match a certain template.
This is almost the same problem as we needed to solve in order to support gRPC routing parameters. The difference is that gRPC routing parameters have a single variable substitution per template, whereas HTTP path parameters can have many.
So for a full HTTP path, there is not a single `haystack` for us to use. We would need to concatenate multiple fields in the request to make the haystack. We do not want to be writing strings in memory that we may not use (e.g. if this path does not match).
For a single HTTP variable substitution, there is a single `haystack`, though. This is just a special case of the gRPC routing parameter code, without a prefix or suffix.
So we …
> impl(gaxi): helper to check path variable substitutions

- generator/internal/parser/openapi.go
As it stands, the OpenAPI HTTP path spec is a subset of the protobuf HTTP rule path spec. We have a parser for the latter. Let's use it.
Pros:
- Way better error handling
- Less logic in aggregate
- If we use the common parser, it is easier to validate path bindings for OpenAPI
Neutral:
- If the specs diverge, we will need a new parser
- Meh, we would have to modify the existing code anyway.
Decision:
- Refactor the code.
> refactor(sidekick): reuse HTTP parser for OpenAPI

- generator/internal/parser/protobuf_annotations.go
> cleanup(generator): query params from `PathTemplate`

- generator/internal/api/model.go
- generator/internal/parser/httprule/http_rule_parser.go
- generator/internal/parser/openapi.go
- generator/internal/parser/openapi_test.go
- generator/internal/parser/protobuf_annotations.go
- generator/internal/parser/protobuf_mixin_test.go
- generator/internal/parser/protobuf_test.go
- generator/internal/rust/annotate_test.go
- generator/internal/rust/codec_test.go
- generator/internal/sample/api.go
> cleanup(generator): remove `LegacyPathTemplate`

- generator/internal/rust/annotate.go
Cleanup some leftovers from #2317
> cleanup(generator/rust): remove some unused fields

- guide/src/setting_up_rust_on_cloud_shell.md
- guide/src/setting_up_your_development_environment.md
> docs: clarify which project in setup guide

- doc/contributor/howto-guide-forks-and-pull-requests.md
Stolen from:
https://github.com/googleapis/google-cloud-cpp/blob/main/doc/contributor/howto-guide-forks-and-pull-requests.md
Then we `s/cpp/rust/`.
And I added a tips and tricks section with things I use in my workflow.
> docs: how to github

- Cargo.lock
- Cargo.toml
- src/storage/Cargo.toml
- src/storage/src/client/upload_object_buffered.rs
- src/storage/src/client/upload_object_unbuffered.rs
Implement setters for every object metadata field and query parameter
that affects buffered uploads.
> impl(storage): buffered upload parameters

- src/storage/src/client.rs
- src/storage/src/client/upload_object.rs
- src/storage/src/client/upload_object/unbuffered.rs
As written the samples were trying to contact production, and failing.
> docs(storage): samples were reaching production

- src/storage/src/storage/client.rs
- src/storage/src/storage/request_options.rs
- src/storage/src/storage/upload_object.rs
> impl(storage): resumable upload size options

- src/storage/src/storage/upload_object.rs
- src/storage/src/storage/upload_object/buffered.rs
> refactor(storage): move upload progress parser

- src/storage/src/storage/upload_object/buffered.rs
- src/storage/src/storage/upload_source.rs
> refactor(storage): move test helper

- generator/internal/sidekick/refresh.go
> refactor(sidekick): prepare for ad-hoc model,cfg loading

- src/storage/src/storage/upload_object.rs
- src/storage/src/storage/upload_object/unbuffered.rs
> refactor(storage): move `query_resumable_upload()`

- src/storage/src/storage/client.rs
- src/storage/src/storage/upload_object.rs
- src/storage/src/storage/upload_object/buffered/resumable_tests.rs
I will use them for more than just uploads.
Part of the work for #2048
> refactor(storage): move retry mocks

- src/storage/src/storage/read_object.rs
This will simplify the implementation of resuming downloads. And since
we have a good idea of the total size, we can improve allocations.
Part of the work for #2057
> impl(storage): use `next()` for `all_bytes()`

- guide/samples/tests/storage.rs
- guide/samples/tests/storage/terminate_uploads.rs
- guide/src/SUMMARY.md
- guide/src/storage/terminate_uploads.md
> docs(storage): show how to terminate uploads

- generator/internal/api/model_test.go
I wrote these tests while debugging something. Might as well add them to the codebase.
> test(generator): simple routing combos

- src/storage/src/lib.rs
- src/storage/src/storage.rs
- src/storage/src/storage/checksum.rs
> impl(storage): make error types public

- src/gax/src/error/binding.rs
When there is exactly one condition, just say what it is without introduction.
Previously we would say "at least one of the conditions must be met: (1) the only condition"
> cleanup(gax): simplify `BindingError` display contents

- dart/README.md
- doc/contributor/howto-guide-generated-code-maintenance.md
Reference `sidekick` in its new home and describe how to make changes
for `sidekick`.
> docs: update contributor guides

- .github/workflows/generator_dart.yaml
- .github/workflows/sdk.yaml
Just making sure that (1) I know how to do this, (2) nothing changed.
> chore: update sidekick

- Cargo.lock
- Cargo.toml
- src/w1r3/Cargo.toml
- src/w1r3/src/main.rs
This initial implementation of the `w1r3` benchmark works, but we will
want to optimize it later, and we will also want to get more detailed
information about failures.
Part of the work for #2824
> feat(w1r3): initial implementation

- Cargo.lock
- src/w1r3/Cargo.toml
- src/w1r3/src/main.rs
> impl(storage-w1r3): use tracing for log messages

- src/gax/src/error/rpc.rs
> cleanup(gax): remove stale TODO

- src/wkt/tests/message_with_wrappers.rs
The test cases were disabled as a bug workaround. I should have restored
the test cases when I fixed the bug.
Related to #2376
> test(wkt): enable more test cases

- src/gax-internal/tests/grpc_retry_loop.rs
> cleanup(gax-internal): remove stale TODOs

- src/w1r3/src/main.rs
Eventually I want to capture any errors, and use a separate folder for
each run of the benchmark.
Part of the work for #2824
> impl(storage-w1r3): more details on each sample

- src/storage/src/storage/perform_upload/unbuffered/resumable_tests.rs
Add a test to cover the case where the upload size is not known. Also
cheat in the test and fake a really small upload quantum. That makes
the errors far more readable.
> test(storage): resumable uploads with unknown size

- src/storage/examples/src/add_bucket_owner.rs
- src/storage/examples/src/lib.rs
- src/storage/examples/src/print_bucket_acl.rs
- src/storage/examples/src/print_bucket_acl_for_user.rs
- src/storage/examples/src/remove_bucket_owner.rs
> docs(storage): bucket ACL examples

- src/storage/examples/src/add_bucket_owner.rs
- src/storage/examples/src/change_default_storage_class.rs
- src/storage/examples/src/create_bucket.rs
- src/storage/examples/src/create_bucket_class_location.rs
- src/storage/examples/src/create_bucket_dual_region.rs
- src/storage/examples/src/create_bucket_hierarchical_namespace.rs
- src/storage/examples/src/delete_bucket.rs
- src/storage/examples/src/get_bucket_metadata.rs
- src/storage/examples/src/lib.rs
- src/storage/examples/src/list_buckets.rs
- src/storage/examples/src/print_bucket_acl.rs
- src/storage/examples/src/print_bucket_acl_for_user.rs
- src/storage/examples/src/remove_bucket_owner.rs
> cleanup(storage): normalize example function names

- Cargo.lock
- src/storage/examples/Cargo.toml
- src/storage/examples/src/lib.rs
- src/storage/examples/src/objects.rs
- src/storage/examples/src/objects/delete_file.rs
- src/storage/examples/src/objects/list_files.rs
- src/storage/examples/src/objects/list_files_with_prefix.rs
- src/storage/examples/src/objects/set_metadata.rs
- src/storage/examples/src/objects/stream_file_download.rs
- src/storage/examples/src/objects/stream_file_upload.rs
- src/storage/examples/tests/integration.rs
> docs(storage): critical object examples

- src/storage/src/error.rs
> doc(storage): document `ChecksumMismatch`

- src/w1r3/Cargo.toml
- src/w1r3/src/main.rs
> impl(w1r3): better help and usage messages

- Cargo.lock
- Cargo.toml
- src/w1r3/Cargo.toml
- src/w1r3/src/main.rs
> impl(w1r3): batch delete objects in each task

- src/storage/src/control/client.rs
- src/storage/src/storage/client.rs
- src/storage/src/storage/read_object.rs
> cleanup(storage): no client creation in doc samples

- src/w1r3/src/main.rs
We can scale up the test to more tasks if each one uses less memory.
> impl(w1r3): share buffer across all tasks

- src/w1r3/src/main.rs
> impl(w1r3): report task errors

- src/w1r3/src/main.rs
> impl(w1r3): report interrupted downloads

- src/w1r3/src/main.rs
Reorganize the code and some parameters. I think it is slightly more
readable, and it helps me bring my development branch and `main` closer
together.
> cleanup(w1r3): cosmetic fixes

- Cargo.lock
- src/w1r3/Cargo.toml
- src/w1r3/src/instrumented_future.rs
- src/w1r3/src/main.rs
I was interested in whether errors got polled a lot of times before
getting an error. This may be useful in future troubleshooting.
> impl(w1r3): instrument futures for errors

- src/w1r3/src/main.rs
Applications (and benchmarks) are supposed to slowly ramp up load in Cloud Storage.
> impl(w1r3): slow rampup of benchmark tasks

- src/w1r3/src/main.rs
A consequence of using pre-conditions (to avoid duplicate uploads) is
that sometimes the upload fails (transport errors, timeouts, etc), but
succeeded.
This is not a problem the client library can deal with, we need to
handle it in the benchmark and/or application.
> impl(w1r3): deal with preconditions

- Cargo.lock
- Cargo.toml
- src/w1r3/Cargo.toml
- src/w1r3/src/main.rs
> impl(w1r3): optional detailed logs from reqwest

- src/w1r3/src/main.rs
> refactor(w1r3): duplicate code in error details

- src/storage/examples/src/lib.rs
- src/storage/examples/src/objects.rs
- src/storage/examples/src/objects/download_byte_range.rs
> docs(storage): add download byte range sample

- src/storage/examples/src/buckets.rs
- src/storage/examples/src/buckets/add_bucket_label.rs
- src/storage/examples/src/buckets/remove_bucket_label.rs
- src/storage/examples/src/lib.rs
> docs(storage): bucket label examples

- src/storage/examples/src/lib.rs
- src/storage/examples/src/objects.rs
- src/storage/examples/src/objects/compose_file.rs
> docs(storage): add `compose_file` example

- src/storage/examples/src/client.rs
- src/storage/examples/src/client/set_client_endpoint.rs
- src/storage/examples/src/lib.rs
- src/storage/examples/tests/integration.rs
> docs(storage): `set_client_endpoint` example

- src/storage/examples/src/lib.rs
Same as #3181, this thing is back from the grave.
> cleanup(storage): remove extra sample run

- src/storage/examples/src/lib.rs
- src/storage/examples/src/objects.rs
- src/storage/examples/src/objects/rotate_encryption_key.rs
> docs(storage): add sample for rotate encryption key

- src/storage/examples/src/lib.rs
- src/storage/examples/src/objects.rs
- src/storage/examples/src/objects/object_csek_to_cmek.rs
> docs(storage): add sample for converting object from csek to cmek

- doc/rustdocfx/generate.go
- doc/rustdocfx/render_metadata.go
- doc/rustdocfx/render_metadata_test.go
> test(rustdocfx): initial unit test

- src/storage/examples/src/lib.rs
- src/storage/examples/src/objects.rs
- src/storage/examples/src/objects/get_kms_key.rs
> docs(storage): add object get kms key example

- guide/src/working_with_long_running_operations.md
* Made various minor style fixes.
* Made a few changes to improve readability.
* Added a link to the full setup guide.
* Updated required dependencies. I needed both `google-cloud-lro` and `google-cloud-longrunning`.
* Moved "What's next" section before full code samples.
* Various nitty fixes.
> docs(lros): improve style and update dependencies

- doc/rustdocfx/generate.go
> docs(rustdocfx): fix toc order to put the crate first

- src/storage/examples/src/lib.rs
- src/storage/examples/src/objects.rs
- src/storage/examples/src/objects/print_file_acl_for_user.rs
> docs(storage): add object print acl for user example

- .gitignore
- doc/rustdocfx/README.md
- doc/rustdocfx/generate.go
- doc/rustdocfx/main.go
- doc/rustdocfx/render_index.go
- doc/rustdocfx/render_reference_test.go
- doc/rustdocfx/workspace.go
- go.work
- tools/golints/all_test.go
- tools/golints/go.mod
> cleanup(rustdocfx): enable and fix go lints

- doc/rustdocfx/process_docs.go
- doc/rustdocfx/process_docs_test.go
Part of the work for #3213 
Process headers and fenced code blocks.
In fenced code blocks, we strip out lines of Rust code that start with a `#`.
The PR is kinda doing 3 things at once. Sorry, I had already written the 1 test.
> impl(docfx): handle headers, fenced code blocks in comments

- src/storage/examples/src/lib.rs
- src/storage/examples/src/objects.rs
- src/storage/examples/src/objects/make_public.rs
> docs(storage): make public example

- guide/samples/tests/storage.rs
- guide/samples/tests/storage/rewrite_object.rs
- guide/src/storage/rewrite_object.md
Add a code sample to the user guide that shows how to use the rewrite_until_done helper to direct people to that method if it works for their use case.
Fixes #3204
> docs(guide): add rewrite_until_done helper to rewrite guide

- .github/workflows/sdk.yaml
- src/generated/cloud/compute/v1/src/model.rs
- src/generated/cloud/compute/v1/src/model/debug.rs
- src/generated/cloud/compute/v1/src/model/deserialize.rs
- src/generated/cloud/compute/v1/src/model/serialize.rs
Adds support for repeated fields and for (most) fields of type "object".
> chore(compute/v1): update sidekick version

- .github/workflows/sdk.yaml
- src/generated/cloud/compute/v1/src/model.rs
- src/generated/cloud/compute/v1/src/model/deserialize.rs
- src/generated/cloud/compute/v1/src/model/serialize.rs
- src/integration-tests/src/compute.rs
> feat(compute/v1): sidekick supports enums

- src/gax-internal/src/observability.rs
For #3239 record response attributes into HttpSpanInfo structs.
Refactored tests to reduce boilerplate.
> impl(gax-internal): Implement record_response_attributes

- src/integration-tests/src/compute.rs
Sorting images by family name is not a good practice. Change the test to
better use these APIs as they would be in a real application, while
still testing the generated code.
> test(compute/v1): use image lists as intended

- src/gax-internal/tests/http_retry_loop.rs
> test(gax-internal): Add HTTP retry loop tracing tests

- src/lro/src/internal/aip151.rs
> cleanup(lro): simplify AIP-151 implementation
