googleapis/google-cloud-rust

.github/workflows/generator.yaml

Makes it easier to grok what the branch protections are doing.

ci: rename the generator build

---

CODE_OF_CONDUCT.md

The project is using version 1.4 of the contributor-covenant.org code of
conduct. That version includes two placeholders that I just filled out.
If anybody else would prefer to act as the project steward I am happy to pass on the role.  I just feel bad that we only had a placeholder in this document, I don't feel like I am particularly qualified for the role.

doc: populate "Code of Conduct" placeholders

---

generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/model.go

I introduced a new attribute to indicate if a scalar field is optional. I am
planning to capture this attribute from the proto source in a future PR.

impl(generator): support all scalar field types

---

.github/workflows/generator.yaml
.github/workflows/lint.yaml
.github/workflows/sdk.yaml
Cargo.lock
Cargo.toml
auth/Cargo.toml
generator/all_test.go
tools/check-copyright/Cargo.toml
tools/check-copyright/src/main.rs
types/Cargo.toml
types/src/lib.rs
types/src/timestamp.rs

This includes a number of fixes for existing files and a new build to enforce the copyright boilerplate.
This is easy to run locally (unlike robots), and handles golang, Rust, TOM, and YAML files.
I wonder if the rules about what files get ignored should be (a) in the build script (as done here), (b) in the code itself (we would need to navigate the directories and ignore .`git/` directories and anything listed in .`gitignore` files), or (c) in yet another `.toml` file.

ci: enforce copyright boilerplate

---

README.md

I also applied some minimal "mdformat" changes. I am planning to enforce formatting for `.md` files via CI.

doc: trim README to what is true today

---

generator/internal/genclient/translator/openapi/openapi.go
generator/internal/genclient/translator/openapi/openapi_test.go

Support more field types, including several string formats.
Remove code duplication between array and scalar field handling.
Make it easier to write smaller unit tests.

impl(generator): support more field types

---

generator/cmd/openapi/main.go

cmd/openapi always reads from a file, so remove the option to read from stdin, and fail if no input is provided.

fix: remove read from os.Stdin

---

generator/internal/genclient/translator/openapi/openapi.go

refactor(generator): restructure OpenAPI loading

---

generator/cmd/protoc-gen-gclient/testdata/rust/golden/model.rs
generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/golang/golang_test.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/templatedata.go
generator/templates/rust/lib.rs.mustache

This PR always uses the per-language Codec to perform any "case conversion". We
need to involve the Codec because each language has a different number of
reserved words that must be escaped, and the escaping is also language
specific.
I also fixed a number of places where we used "camel case" when we meant
`PascalCase` (note the starting upper case, as opposed to `camelCase`).
Almost incidentally, I fixed the conversion for `data_crc32c` (and other names
already in `snake_case` form). Previously that got converted to
`data_crc_32_c`.
Fixes #35 and fixes #36.

impl: better name conversions

---

generator/cmd/openapi/testdata/rust/golden/model.rs
generator/internal/genclient/translator/openapi/openapi.go
generator/internal/genclient/translator/openapi/openapi_test.go

We should be able to find each message via the `State.MesssagesByID` index. The
generator assumes this index is populated when calling the mustache templates.

impl(generator/openapi): populate index for messages

---

generator/internal/genclient/translator/protobuf/protobuf.go

Use a map instead of a switch statement for readability.

impl(internal/gclient/translator/protobuf): use a map in normalizeTypes

---

generator/cmd/protoc-gen-gclient/main.go
generator/internal/genclient/translator/protobuf/protobuf.go

The Translator struct isn't necessary, so it is removed to simplify the code in generator/internal/genclient/translator/protobuf

impl(internal/genclient/translator/protobuf): simplify protobuf translator

---

generator/go.mod
generator/go.sum
generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/testdata/rust/gclient/golden/model.rs

Support repeated and optional fields. Maybe the largest contribution here is to
introduce a way to unit test the Protobuf translator.

impl(generator/protobuf): optional and repeated fields

---

generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/golang/golang_test.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/templatedata.go
generator/templates/rust/model.mustache
generator/testdata/rust/gclient/golden/model.rs
generator/testdata/rust/openapi/golden/model.rs

The mapping nested messages and enums uses a public module within the crate.
That requires a new "snake case" accessor for the message name, as Rust uses
snake case for modules.
We also need a boolean to find out if the module is needed at all.
And we need to get a different attribute for the fully qualified name of each
message and enum, as we must refer to the qualified name of the generated
struct when using the type.
Fixes #40. This PR is more bulky than I like, it snowballed on me. Let me know if you want me to break it into smaller PRs.

impl(generator): handle nested messages and enums in Rust

---

generator/cmd/openapi/main.go
generator/internal/genclient/translator/openapi/openapi.go
generator/internal/genclient/translator/openapi/openapi_test.go

The `Translator` struct isn't necessary, so it is removed to simplify the code in `generator/internal/genclient/translator/openapi`

impl(internal/genclient/translator/openapi): simplify openapi translator

---

generator/cmd/protoc-gen-gclient/main.go
generator/cmd/protoc-gen-gclient/main_test.go

Move logic for captureInput to a separate function and document it.

cmd/protoc-gen-gclient: factor out captureInput

---

generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/testdata/rust/gclient/golden/lib.rs
generator/testdata/rust/gclient/golden/model.rs

Protobuf introduces an extra newline at the beginning of each comment line.
OpenAPI comments do not have this extra space. I chose to normalize the
comments to the OpenAPI style because that makes the rest of the code cleaner.
Fixes #31

impl(generator/protobuf): fix comment cleanup

---

generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/templatedata.go
generator/templates/rust/enum.mustache
generator/testdata/rust/gclient/golden/model.rs

We decided to use strings for enum values, as the transport will be HTTP +
JSON. The generator creates some helper constants in a properly named module,
that prevents typos.
Fixes #76

impl(generator): Rust uses strings for enum values

---

generator/cmd/protoc-gen-gclient/main.go
generator/devtools/cmd/generate/main.go
generator/go.mod
generator/internal/genclient/service_config.go
generator/internal/genclient/service_config_test.go
generator/internal/genclient/translator/openapi/openapi_test.go
generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/sample/sample.go

Fixes https://github.com/googleapis/google-cloud-rust/issues/38
Updates https://github.com/googleapis/google-cloud-rust/issues/42

impl: read service config

---

generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/golang/golang_test.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/templatedata.go
generator/testdata/rust/openapi/golden/model.rs

Each language codec will need to make slightly different adjustments to the
documentation comments. This PR moves the splitting and cleanup of each line to
the Codec, and introduces some Rust specific cleanups.
Fixes #57 and fixes #33

impl(generator): move doc formatting to Codec

---

types/Cargo.toml
types/src/any.rs
types/src/lib.rs

Introduce a Rust type to support the well-known type `.google.protobuf.Any`.
This will probably need more work for a full implementation, but I think it is
enough to unblock development of the generator.
Part of the work for #77

impl(types): initial version of `Any`

---

generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/internal/genclient/translator/protobuf/testdata/object_fields.proto

Normalize message fields to always be optional. This will make other parts of
the code easier to implement: we always wrap optional fields with `Option<T>`.
Motivated by #95

impl(generator/protobuf): message fields are always optional

---

.github/workflows/sdk.yaml
auth/src/lib.rs
tools/check-copyright/src/main.rs
types/src/duration.rs

TIL: without `--fix` clippy fails silently, with `--fix` at least we get failures in the `git diff` command.

ci: fail the build on clippy warnings

---

generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/internal/genclient/translator/protobuf/testdata/map_fields.proto

Map fields are represented as repeated fields in Protobuf. I think this is
leaking their representation on the wire (a sequence of objects, with `key` and
`value` fields). For our purposes the field is not repeated, and can never be
(`repeated map<K, V> foo = 1;` is not a legal Protobuf field).
Part of the work for #95

impl(generator/protobuf): cleanup map fields

---

generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/testdata/rust/gclient/golden/model.rs
generator/testdata/rust/openapi/golden/model.rs

The Rust generator now uses `Vec<T>` for repeated fields.
Fixes #95

impl(generator/rust): support repeated fields

---

generator/internal/genclient/translator/openapi/openapi.go
generator/internal/genclient/translator/openapi/openapi_test.go
generator/testdata/rust/openapi/golden/model.rs

This "fixes" the TypezID for any repeated object field. At some point I
introduced the `.${package}.` prefix (or really `..` as the package is always
empty), and neglected to fix these in any `TypezID` for repeated objects.
Motivated by #95

impl(generator/openapi): fix TypezID for repeated objects

---

generator/templates/rust/Cargo.toml.mustache
generator/templates/rust/README.md.mustache
generator/templates/rust/src/enum.mustache
generator/templates/rust/src/lib.rs.mustache
generator/templates/rust/src/model.mustache
generator/templates/rust/src/model.rs.mustache
generator/templates/rust/src/oneof.mustache
generator/testdata/rust/gclient/golden/src/model.rs
generator/testdata/rust/openapi/golden/src/model.rs

We want to avoid `use ` declarations in the generated code, because we do not
know if these can introduce any conflicts.
Took this opportunity to introduce the copyright boilerplate to the mustache templates.
Because I have not domesticated my editor w.r.t. mustache files, I finished all
the mustache files on newlines. The only side effect is that now the closing
braces for messages are indented correctly. I like that change too.

impl(generator/rust): avoid `use serde::*`

---

generator/templates/rust/Cargo.toml.mustache
generator/templates/rust/src/lib.rs.mustache
generator/testdata/rust/gclient/golden/Cargo.toml
generator/testdata/rust/gclient/golden/src/lib.rs
generator/testdata/rust/openapi/golden/Cargo.toml

We need the `json` feature in the `reqwest` package to do JSON serialization
and deserialization of the messages.
The generated code had some syntax errors (missing parens in a function call),
and needed a temporary to convert the returned error correctly.

impl(generator/rust): fix client build problems

---

generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/testdata/rust/gclient/golden/src/model.rs
generator/testdata/rust/openapi/golden/src/model.rs

The correct "root" scope for entities created in `model.rs` is
`crate::model::`, we were using only `crate::`.

fix(generator/rust): use right scope for model

---

generator/cmd/openapi/main.go
generator/cmd/openapi/main_test.go
generator/internal/genclient/model.go
generator/internal/genclient/templatedata.go
generator/internal/genclient/translator/openapi/openapi.go
generator/internal/genclient/translator/openapi/openapi_test.go
generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/templates/rust/README.md.mustache
generator/testdata/rust/gclient/golden/README.md
generator/testdata/rust/openapi/golden/README.md

With this PR the OpenAPI variant also reads the service config file. We also
capture more information from the service config file: the API title and
summary are useful to generate acceptable README files.

impl(generator): MOAR service config information

---

.github/workflows/sdk.yaml
Cargo.lock
Cargo.toml
generator/cmd/openapi/main_test.go
generator/cmd/protoc-gen-gclient/main_test.go
generator/templates/rust/Cargo.toml.mustache
generator/templates/rust/src/lib.rs.mustache
generator/testdata/rust/gclient/golden/Cargo.toml
generator/testdata/rust/gclient/golden/src/lib.rs
generator/testdata/rust/gclient/golden/src/model.rs
generator/testdata/rust/openapi/golden/Cargo.toml
generator/testdata/rust/openapi/golden/src/lib.rs
generator/testdata/rust/openapi/golden/src/model.rs

Hardcode a few things to get the code compiling.
I want to add these files to the Rust CI builds, and that includes enforcing
any formatting for them. I could have fixed the generator to correct some of
the formatting problems, but the last few nits would have complicated the
templates too much.
Whenever the generator gets moved to its own repository: we should remove this
step. That will complicate the tooling for generator developers.
I left a number of TODO entries (pointing to bugs).  I think the changes in the CI scripts are necessary if we want to compile the golden files, but they may also be a reason to **not** merge this PR. I thought the discussion would be easier with a visible PR.

test(generator): compile Rust golden files

---

.github/workflows/generator.yaml
generator/README.md
generator/go.mod
generator/go.sum
generator/internal/genclient/translator/protobuf/protobuf_test.go

I could not get `bufbuild/protocompile` to handle all the complex options we
use in our service proto files. Since we use files to keep the test input, we
can just call `protoc` to parse the file.
Motivated by #120: I will need to do some refactoring in protobuf.go, and I would prefer having some unit tests before doing that.

test(generator): use `protoc` to parse test files

---

generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/internal/genclient/translator/protobuf/testdata/test_service.proto

This is a step towards refactoring the protobuf translator. It simply adds a
new unit tests for a small (test-only) service.
Motivated by #120

test(generator/protobuf): add unit test for services

---

types/src/any.rs
types/src/duration.rs
types/src/field_mask.rs
types/src/lib.rs
types/src/timestamp.rs

Or at least make them more uniform:
- Prefer `?` over `.unwrap()` to short-circuit on failures.
- Prefer `test_case` over for loops for several similar tests.

cleanup: simplify some tests

---

generator/internal/genclient/model.go
generator/internal/genclient/translator/protobuf/annotations.go
generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/internal/genclient/translator/protobuf/testdata/comments.proto

This introduces an (at the moment) alternative representation for HTTP RPCs. I
cannot produce the previous representation from the OpenAPI specification, and
it seems overly difficult to use. In a pending PR I will change the Codecs to
use `PathInfo` and then remove `genclient.HTTPInfo`.
Motivated by #120

impl(generator/protobuf): new representation for HTTP RPCs

---

generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/model.go
generator/internal/genclient/templatedata.go
generator/internal/genclient/translator/protobuf/annotations.go
generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/testdata/rust/gclient/golden/src/lib.rs

The `PathInfo` field is representation of the HTTP parameters that works for
both OpenAPI and Protobuf. This PR changes the codec to use `PathInfo` and
removes `HTTPInfo` and its support code.
Incidentally, this fixes a bug in the Protobuf parsing, where some parameters
were treated as both path parameters and query parameters.
Motivated by #120

impl(generator): use `PathInfo` to generate methods

---

types/src/duration.rs
types/src/field_mask.rs
types/src/timestamp.rs
types/tests/any.rs
types/tests/duration.rs
types/tests/field_mask.rs
types/tests/timestamp.rs

`FieldMask` had private fields when they should have been public. We were
missing setters for a number of fields.
I refactored some of the tests to be integration tests, so we can verify the
intended usage outside the crate.
Motivated by #132 and #129

fix: make types usable outside the crate

---

Cargo.lock
Cargo.toml
gax/Cargo.toml
gax/src/lib.rs
gax/src/query_parameter.rs
gax/tests/query_parameters.rs

I want to keep the generated code for query parameters relatively simple, and
at the same time I want to support optional query parameters, required query
parameters, query parameters of different types, including some well-known
types.
This introduces a new crate[^1] which initially just has a helper function to
convert all the expected types to strings. The integration tests show how this
helper would be used in generated code.
[^1]: curiously named `gax` for no reason I can think of
Part of the work for #128 and #129

impl: helpers for query parameters

---

Cargo.lock
generator/internal/genclient/language/internal/rust/rust.go
generator/templates/rust/Cargo.toml.mustache
generator/templates/rust/src/lib.rs.mustache
generator/testdata/rust/gclient/golden/Cargo.toml
generator/testdata/rust/gclient/golden/src/lib.rs
generator/testdata/rust/openapi/golden/Cargo.toml

Using these helpers we can handle more query parameter types, including the
well-known-types that may appear as such.
Part of the work for #128 and #129

impl(generator/rust): use query parameter helpers

---

generator/internal/genclient/translator/protobuf/annotations.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/internal/genclient/translator/protobuf/testdata/query_parameters.proto

When the RPC has a `body: "*"` annotation then none of the request fields are
query parameters.
Fixes #142

fix(generator/protobuf): handle body in query parameters

---

generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/internal/genclient/translator/protobuf/testdata/wkt_fields.proto
generator/testdata/rust/gclient/golden/src/model.rs

When I "fixed" the code to handle maps as non-repeated fields, I accidentally
made all object fields repeated.
Fixes #144

fix(generator/protobuf): not all object fields are repeated

---

generator/internal/genclient/translator/openapi/openapi.go
generator/internal/genclient/translator/openapi/openapi_test.go
generator/testdata/rust/openapi/golden/src/lib.rs
generator/testdata/rust/openapi/golden/src/model.rs

Use the information from the `paths` section to find out what RPCs are
available. They all go into the same service, because there is nothing obvious
to use.
We create synthetic request objects because the OpenAPI spec does not seem to
have them for all RPCs. We inject the require path and query parameters into
the request object, whether that is synthetic or included by the specification.
Fixes #120 and fixes #128 and fixes #129

impl(generator/openapi): generate service and RPCs

---

generator/internal/genclient/translator/protobuf/protobuf.go
generator/internal/genclient/translator/protobuf/protobuf_test.go
generator/internal/genclient/translator/protobuf/testdata/imported.proto
generator/internal/genclient/translator/protobuf/testdata/with_import.proto

Imported messages should not be generated, so we exclude them from the
`api.Messages` list. They do need to be in the `api.State.MessageByID` index,
as these messages may be referenced by other messages or services.
Part of the work for #150

impl(generator/protobuf): skip imported messages

---

gax/src/lib.rs
gax/src/path_parameter.rs
gax/tests/path_parameters.rs

Sometimes path parameters appear inside optional fields.  Consider:
https://github.com/googleapis/google-cloud-rust/blob/c9f74adf12932f910aa69c167a9ca5ec0fe258fd/generator/testdata/googleapis/google/cloud/secretmanager/v1/service.proto#L88
That requests the `.name` field from the `.secret` field in the request.  But
`.secret` is mapped to `Option<Secret>` because it is a message. We need to say
something like `.secret.ok_or_else(...)?.name`. This PR introduces some helpers
to simplify the generator. The generator always calls the
`PathParameter::required()` function. The function expands to either `self` or
`self.ok_or_else()` depending on whether the parameter is an `Option<_>` or not.
A future PR will take advantage of these helpers in the generated code.
Part of the work for #140

feat(gax): support optional path parameters

---

generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/templates/rust/src/lib.rs.mustache
generator/testdata/rust/gclient/golden/src/lib.rs
generator/testdata/rust/openapi/golden/src/lib.rs
generator/testdata/rust/openapi/golden/src/model.rs

Add a proper package name to the well-known types use the package when
generating any usage for these types.
I also cleaned up how all messages were named in the requests and responses.
Fixes #156, I think it helps with #77 and with #158.
It may help with #157, but I would like to extend the golden files after this is merger.

feat(generator/rust): improve codegen for well-known types

---

generator/cmd/main.go
generator/internal/genclient/language/language.go
generator/internal/genclient/language/language_test.go

Part of the work #158 
The idea is to receive per-codec configuration in an incoming PR.

cleanup(generator): simplify codec initialization

---

generator/cmd/main_test.go
generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/language/language.go
generator/internal/genclient/templatedata.go
generator/templates/rust/Cargo.toml.mustache
generator/testdata/rust/gclient/golden/Cargo.toml
generator/testdata/rust/openapi/golden/Cargo.toml

impl(generator): configurable packages for Rust codec

---

Cargo.lock
generator/cmd/main_test.go
generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/templatedata.go
generator/templates/rust/Cargo.toml.mustache
generator/testdata/rust/gclient/golden/Cargo.toml
generator/testdata/rust/openapi/golden/Cargo.toml

Make it possible to override the package name via
the command-line. Use this to generate unique
names for the golden files.
Part of the work for #162

feat(generator/rust): configurable package names

---

generator/cmd/main.go
generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/golang/golang_test.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/model.go
generator/internal/genclient/parser/protobuf/protobuf.go
generator/internal/genclient/parser/protobuf/protobuf_test.go

First, capture the package name (in the source specification lingo) of each
service, message, and top-level enum. We will need those to reference the
symbol by their fully qualified name.
Second, capture the *single* top-level package name for the symbols the Codec
needs to generate. With the current design / structure the Codecs cannot handle
more than one top-level package name, so return an error in that case.
Then we can change the rust codec to generate the correctly mapped package name.
Part of the work for #158

impl(generator/rust): support external packages

---

Cargo.lock
Cargo.toml
generator/cmd/main_test.go
generator/testdata/rust/gclient/golden/iam/v1/Cargo.toml
generator/testdata/rust/gclient/golden/iam/v1/README.md
generator/testdata/rust/gclient/golden/iam/v1/src/lib.rs
generator/testdata/rust/gclient/golden/iam/v1/src/model.rs

Include the IAM protos to the Rust golden file sources.
These both use external packages (`google.type`) and are used in the
secretmanager service protos.
Part of the work for #158

test(generator/protobuf): add iam/v1 protos

---

generator/testdata/rust/gclient/golden/secretmanager/src/lib.rs
generator/testdata/rust/gclient/protos/service.proto

Include the IAM RPCs in the Rust golden files. We need one patch to
workaround the `GetIamPolicy()` query parameters.
Part of the work for #158

test(generator/rust): add IAM RPCs to golden files

---

generator/go.mod
generator/go.sum
generator/internal/genclient/parser/openapi/openapi.go
generator/internal/genclient/service_config.go
generator/internal/genclient/service_config_test.go
generator/internal/sample/sample.go
generator/testdata/googleapis/google/cloud/secretmanager/v1/secretmanager_v1.yaml

Parsing via yaml -> jsonproto -> proto works for enums as strings, and
for well-know protos and for a number of other corner cases.
Part of the work for #158

impl(generator): full service config parser

---

Cargo.lock
gax/Cargo.toml
gax/src/lib.rs
generator/cmd/main_test.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/testdata/rust/gclient/golden/iam/v1/Cargo.toml
generator/testdata/rust/gclient/golden/secretmanager/Cargo.toml
generator/testdata/rust/gclient/golden/type/Cargo.toml
generator/testdata/rust/openapi/golden/Cargo.toml

Created a feature called sdk_client which we can use from our clients but that customers should not have to depend on. This makes it more clear which APIs are meant for internal consumption vs public.

refactor: move internal helpers to a rust feature

---

generator/cmd/generate.go
generator/cmd/refresh.go
generator/cmd/sidekick.go
generator/cmd/sidekick_test.go

Split the code a bit so it is easier to introduce subcommands.
Part of the work for #188

refactor(generator): prepare for subcommands

---

generator/README.md
generator/cmd/generate.go
generator/cmd/refresh.go
generator/cmd/sidekick.go
generator/cmd/sidekick_test.go
generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/testdata/rust/gclient/golden/iam/v1/Cargo.toml
generator/testdata/rust/gclient/golden/secretmanager/Cargo.toml
generator/testdata/rust/gclient/golden/secretmanager/README.md

Change the main program test to use command-line arguments. That makes
the test more comprehensive, and it helps me document the commands in
the README file.
Part of the work for #188

refactor(generator): test using command-line args

---

gax/src/error/error.rs
gax/src/error/mod.rs
gax/tests/errors.rs

This type will be the top-level error type used by all generated clients.
Updates: #175

feat(gax): add a core error type

---

generator/cmd/sidekick_test.go
generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/templatedata.go
generator/templates/go/client.go.mustache
generator/templates/go/enum.mustache
generator/templates/go/message.mustache
generator/templates/rust/crate/Cargo.toml.mustache
generator/templates/rust/crate/src/lib.rs.mustache
generator/templates/rust/crate/src/model.rs.mustache
generator/templates/rust/mod/mod.rs.mustache
generator/testdata/rust/gclient/golden/iam/v1/Cargo.toml
generator/testdata/rust/gclient/golden/iam/v1/src/lib.rs
generator/testdata/rust/gclient/golden/iam/v1/src/model.rs
generator/testdata/rust/gclient/golden/module/mod.rs
generator/testdata/rust/gclient/golden/secretmanager/Cargo.toml
generator/testdata/rust/gclient/golden/secretmanager/src/lib.rs
generator/testdata/rust/gclient/golden/secretmanager/src/model.rs
generator/testdata/rust/gclient/golden/type/Cargo.toml
generator/testdata/rust/gclient/golden/type/src/lib.rs
generator/testdata/rust/gclient/golden/type/src/model.rs
generator/testdata/rust/openapi/golden/Cargo.toml
generator/testdata/rust/openapi/golden/src/lib.rs
generator/testdata/rust/openapi/golden/src/model.rs

Wherever is possible we are supposed to include the copyright boilerplace, even
in generated code. We will capture the generation year when the library is
first created. That prevents noisy changes when regenerating in a different
year. From time to time we will create new files, we can bump the year across
all files (this is allowed for generated code), when that happens.

feat(generated): include copyright boilerplate

---

generator/internal/genclient/parser/openapi/openapi.go
generator/internal/genclient/parser/openapi/openapi_test.go
generator/testdata/rust/openapi/golden/src/model.rs

Path parameters are often undocumented in Google's OpenAPI v3
specifications. In that case, generate some generic (but still useful)
documentation.
Fixes #147

feat(generator/openapi): document path parameters

---

generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/templates/rust/common/message.mustache
generator/testdata/rust/gclient/golden/iam/v1/src/model.rs
generator/testdata/rust/gclient/golden/module/mod.rs
generator/testdata/rust/gclient/golden/secretmanager/src/model.rs
generator/testdata/rust/gclient/golden/type/src/model.rs
generator/testdata/rust/openapi/golden/src/model.rs

Any field may be missing from incoming JSON messages, we need to set
these to the default value.

feat(generator/rust): set missing fields to default

---

.taplo.toml
Cargo.toml
auth/Cargo.toml
gax/Cargo.toml
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/templates/rust/crate/Cargo.toml.mustache
generator/testdata/rust/gclient/golden/iam/v1/Cargo.toml
generator/testdata/rust/gclient/golden/secretmanager/Cargo.toml
generator/testdata/rust/gclient/golden/type/Cargo.toml
generator/testdata/rust/openapi/golden/Cargo.toml
src/auth/Cargo.toml
src/base/Cargo.toml
src/gax/Cargo.toml
src/generated/api/Cargo.toml
src/generated/cloud/common/Cargo.toml
src/generated/cloud/iam/v1/Cargo.toml
src/generated/cloud/location/Cargo.toml
src/generated/cloud/secretmanager/v1/Cargo.toml
src/generated/longrunning/Cargo.toml
src/generated/type/Cargo.toml
src/integration-tests/Cargo.toml
src/root/Cargo.toml
src/wkt/Cargo.toml
types/Cargo.toml

I think aligned entries within a table are more readable. Also fix the
generator to create `Cargo.toml` files that are very close to having
perfect formatting.

cleanup: configure `.toml` formatting

---

generator/internal/genclient/genclient.go
generator/internal/genclient/parser/protobuf/protobuf.go

Fix a bunch of warnings that really did not indicate a problem, and one
info message that we do not need on successful runs.

cleanup(generator): success runs are silent

---

Cargo.lock
src/integration-tests/Cargo.toml
src/integration-tests/src/lib.rs
src/integration-tests/tests/secret-manager.rs

Test all the RPCs for Secret Manager over Protobuf. I do not believe we
should do this for each client, but at least one client should run the
full set.
We will also want at least one integration test for LROs. More
generally, one for AIP affecting the generator behavior.

test: all RPCs for secret manager + protobuf

---

generator/internal/genclient/parser/openapi/openapi.go
generator/internal/genclient/parser/openapi/openapi_test.go
generator/testdata/rust/openapi/golden/src/lib.rs

For existing `*Request` messages we need to send the full body.
Part of the work for #226

fix(generator/openapi): full body for some requests

---

Cargo.lock
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/parser/openapi/openapi.go
generator/internal/genclient/parser/openapi/openapi_test.go
generator/testdata/rust/gclient/golden/secretmanager/src/model.rs
generator/testdata/rust/openapi/golden/src/model.rs
src/integration-tests/Cargo.toml
src/integration-tests/tests/secret_manager_protobuf.rs
types/tests/field_name_override.rs

Specially with OpenAPI specifications the field name may have gone
through a `snake_case` to `camelCase` translation. In Rust we want to
use `snake_case` for the fields, but that roundtrip is lossy.
I think the bad field name in Rust is undesirable, but it works. The bad
name is the serialized JSON does not work at all. This PR fixes that
problem.
Part of the work for #226

fix(generator/rust): handle sneaky field names

---

generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/model.go
generator/internal/genclient/parser/openapi/openapi.go
generator/internal/genclient/parser/openapi/openapi_test.go
generator/testdata/rust/openapi/golden/src/model.rs

We create synthetic fields for the `*Request` parameter. Sometimes we add these
fields to existing messages, and some of these messages have more than one
field. In all cases, we should avoid serializing these synthetic fields, as the
server does not expect them.
Part of the work for #266

fix(generator/openapi): skip synthetic fields

---

generator/templates/rust/crate/src/lib.rs.mustache
generator/testdata/rust/gclient/golden/iam/v1/src/lib.rs
generator/testdata/rust/gclient/golden/secretmanager/src/lib.rs
generator/testdata/rust/openapi/golden/src/lib.rs

Currently all you can do publicly with this config is set an endpoint override.

feat(generator/rust): add client constructor config

---

src/integration-tests/tests/secret_manager_openapi.rs
src/integration-tests/tests/secret_manager_protobuf.rs

Expand the integration tests using the client generated from the OpenAPI
specification. With this PR we can verify we can create, update, list,
get, and delete secrets (without locations). We can also get their IAM
policies, change the IAM policy, and test the IAM permissions.
For secret versions, verify we can create, enable, disable, access,
list, and delete them.
Finally verify we can list and get details about locations.
Part of the work for #226

test: expand secret manager integration tests

---

src/integration-tests/src/secret_manager/mod.rs
src/integration-tests/src/secret_manager/openapi.rs
src/integration-tests/src/secret_manager/protobuf.rs
src/integration-tests/tests/driver.rs

Easier to find things this way, and eventually it may be easier to share
code between tests too.

cleanup: move integration test modules

---

.typos.toml
generator/templates/rust/crate/src/lib.rs.mustache
generator/testdata/rust/gclient/golden/iam/v1/src/lib.rs
generator/testdata/rust/gclient/golden/secretmanager/src/lib.rs
generator/testdata/rust/openapi/golden/src/lib.rs

Had to create a `NoBody` type to pass along to satisfy generics. This type is not exported. 
Fixes: #139

refactor(generator/rust): factor out some common execute code

---

src/integration-tests/src/secret_manager/mod.rs
src/integration-tests/src/secret_manager/openapi_locational.rs
src/integration-tests/tests/driver.rs

Complete the integration tests for secret manager and OpenAPI. Each RPC
has at least one test.
Fixes #226

test: all OpenAPI + secret manager RPCs

---

.gcb/README.md
.gcb/bootstrap/.terraform.lock.hcl
.gcb/bootstrap/README.md
.gcb/bootstrap/main.tf
.gcb/bootstrap/terraform.tfstate
.gcb/bootstrap/variables.tf
.gcb/builds/.terraform.lock.hcl
.gcb/builds/backend.tf
.gcb/builds/grants/main.tf
.gcb/builds/main.tf
.gcb/builds/resources/main.tf
.gcb/builds/services/main.tf
.gcb/builds/triggers/main.tf
.gcb/builds/variables.tf
.gcb/integration.yaml
.gcloudignore

This creates all the GCB (Google Cloud Build) configuration needed to
run the integration tests. There is a lot more Terraform than I would
like, but at least that can easily grow as we start needing more
resources.
The triggers for these builds are not created yet.

ci: configure GCB to run integration tests

---

Cargo.lock
src/integration-tests/Cargo.toml
src/integration-tests/src/lib.rs
src/integration-tests/src/secret_manager/openapi_locational.rs
src/integration-tests/src/secret_manager/protobuf.rs
src/integration-tests/tests/driver.rs

Use `gax::error::Error` so we can print better error messages on
failure.

test: improve error messages for integration tests

---

.gcb/builds/grants/main.tf
.gcb/builds/main.tf
.gcb/builds/resources/main.tf

Creating project-wide grants in Terraform conflicts with the internal
Google Cloud project management tools. I moved the service account and
project-wide IAM permissions there, and use Terraform only for narrower
resources and permissions.

ci(gcb): use pre-existing resources

---

generator/go.mod
generator/go.sum
generator/sidekick/downloads_cache.go
generator/sidekick/downloads_cache_test.go

To refresh all the directories we will need to download snapshots of
googleapis/googleapis from GitHub. This PR introduces a number of
helper functions to perform these downloads and keep a local cache in
$HOME.
The cache is content based, that is, the SHA256 of the complete tarball
is the index into the cache. The download fails if the contents do not
match the specified SHA256, and if the SHA256 is already in the cache
the functions skip the download.
Part of the work for #263

impl(generator): helper functions for downloads

---

.github/workflows/sdk.yaml

I finally figured out why `cargo clippy` was not stopping the build on
problems: warnings do not break the build. Eventually we may find some
clippy warnings to be false positives. I prefer to turn all of them on
and then turn off the bad ones vs. trying to pick the right ones.

ci: treat `cargo clippy` warnings as errors

---

generator/internal/genclient/parser/openapi/openapi.go
generator/testdata/rust/openapi/golden/src/lib.rs
src/integration-tests/src/secret_manager/openapi.rs
src/integration-tests/src/secret_manager/openapi_locational.rs

OpenAPI does not have service names. We use the name from the service
config YAML file to get a name. This name includes the protobuf package.
With this change we strip the package name.
I also populated the package name in all the OpenAPI data structures,
mostly for consistency.
Fixes #235

fix(generator/openapi): better service names

---

generator/sidekick/config.go
generator/sidekick/config_test.go
generator/sidekick/generate.go
generator/sidekick/refresh.go
generator/sidekick/sidekick.go
generator/sidekick/sidekick_test.go
generator/testdata/go/gclient/golden/iam/v1/.sidekick.toml
generator/testdata/go/gclient/golden/typez/.sidekick.toml
generator/testdata/rust/gclient/golden/iam/v1/.sidekick.toml
generator/testdata/rust/gclient/golden/location/.sidekick.toml
generator/testdata/rust/gclient/golden/module/rpc/.sidekick.toml
generator/testdata/rust/gclient/golden/module/type/.sidekick.toml
generator/testdata/rust/gclient/golden/secretmanager/.sidekick.toml
generator/testdata/rust/gclient/golden/type/.sidekick.toml
generator/testdata/rust/openapi/golden/.sidekick.toml

This change introduces support for an optional per-repository
configuration file, and starts using that file in the `refresh`
subcommand.
The motivation is to set the googleapis location in a single place and
to minimize the number of arguments that we need to provide in
`generate`.
Once the googleapis location is centralized, we can also start
downloading it from GitHub.
Fixes #261

impl(generator): global configuration for refresh

---

generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/templatedata.go
generator/templates/rust/common/message.mustache
generator/testdata/rust/gclient/golden/module/rpc/mod.rs

The setters are already mangled: they start with `set_` and no reserved
word has that prefix.
Part of the work for #283

feat(generator/rust): no mangling for setters

---

generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/sidekick/sidekick_test.go
generator/testdata/rust/gclient/golden/module/rpc/.sidekick.toml
generator/testdata/rust/gclient/golden/module/rpc/mod.rs

Generated modules embedded on a hand-crafted library may not be in the `crate::model::` path. Recall that the generator uses paths anchored to `crate::`, as relative paths do not work well with nested messages and their corresponding nested modules. With this PR, the module path is configurable.
Part of the work for #283

feat(generator/rust): configurable module paths

---

generator/internal/genclient/genclient.go
generator/internal/genclient/language/internal/golang/golang.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/templatedata.go
generator/sidekick/sidekick_test.go
generator/templates/rust/common/message.mustache
generator/testdata/rust/gclient/golden/module/rpc/.sidekick.toml
generator/testdata/rust/gclient/golden/module/rpc/mod.rs

In the generated module for `gax/error/rpc` we need to tweak message
serialization to *only* accept JSON objects with all the message fields.
This PR adds an option to support this case. I expect the option will
see little use beyond that, but custom  options to bootstrap the
libraries are (I think) to be expected.
Part of the work for #283

feat(generator/rust): configurable mod serialization

---

.sidekick.toml
generator/sidekick/generate.go
generator/sidekick/refresh.go
generator/sidekick/refreshall.go
generator/sidekick/refreshall_test.go
generator/sidekick/sidekick.go

This introduces the `refreshall` subcommand. This subcommand runs the
`refresh` subcommand for all the directories that happen to have a
`.sidekick.toml` file.
The intent is to keep a pinned version of googleapis/googleapis
configured in the top-level directory. This pinned version is downloaded
to the sidekick cache (if needed) and all the subdirectories use the
version in the cache.
This subcommand is intended to handle changes in the mustache templates
or the generator itself. We will introduce a separate subcommand to
update the googleapis/googleapis pinned SHA.
Fixes #263, fixes #270

feat(generator): refreshall subcommand

---

generator/sidekick/config.go
generator/sidekick/config_test.go
generator/testdata/go/gclient/golden/iam/v1/.sidekick.toml
generator/testdata/go/gclient/golden/typez/.sidekick.toml
generator/testdata/rust/gclient/golden/iam/v1/.sidekick.toml

Most `.sidekick.toml` files will have only a few items set, with most of
the configuration saved in the top-level configuration file. With this
change, only non-empty values are saved.

feat(generator): cleaner `.sidekick.toml` files

---

generator/sidekick/cmdline.go
generator/sidekick/cmdline_test.go
generator/sidekick/config.go
generator/sidekick/config_test.go
generator/sidekick/generate.go
generator/sidekick/refresh.go
generator/sidekick/refreshall.go
generator/sidekick/refreshall_test.go
generator/sidekick/sidekick.go
generator/sidekick/sidekick_test.go

Parse the command-line arguments in a single place, so `sidekick -h`
works as expected.
Introduce a new subcommand to just print the help message.
Fixes #285

refactor(generator): consolidated command line args

---

generator/internal/genclient/parser/openapi/openapi.go
generator/internal/genclient/parser/protobuf/protobuf.go
generator/internal/genclient/parser/protobuf/protobuf_test.go
generator/internal/genclient/service_config.go
generator/sidekick/sidekick_test.go
generator/testdata/rust/gclient/golden/module/rpc/.sidekick.toml
generator/testdata/rust/gclient/golden/module/type/.sidekick.toml

It is more ergonomic to specify the inputs into the parsers relative to
`googleapis-root` (or some such configuration). That allows us to keep
the root configured in a single place, and even dynamically download
the right googleapis version where needed.
For now, we use `test-root` and `googleapis-root` as search paths, and
fall back to searching in `$PWD` if those do not work. In the future we
may want to add other `*-root` search paths, e.g. if all the discovery
docs are committed to a different directory.

feat(generator): search paths for inputs

---

generator/sidekick/generate.go

`generate` is the command to create new client libraries. The top-level
`.sidekick.toml` configuration may require use of a pinned SHA from
GitHub. In such case `generate` needs to download googleapis, and
override the configuration to use the downlead copy.
Recall that such downloads are cached, so most of the time this would
not be very slow, and may not even involve any network traffic. Also,
the tests use a local directory, so unit tests and CI tests do not
involve network traffic either.

feat(generator): `generate` can download googleapis

---

generator/sidekick/cmdline.go
generator/sidekick/cmdline_test.go

The defaults (if any) should be saved in the top-level configuration file.

fix(generator): fewer defaults for cmdline arguments

---

generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go

Most generated packages will use `gax`, `wkt`, and `auth`. It makes sense to
configure these packages in the top-level `.sidekick.toml` file. But we also
need to remove `gax` from that list when generating
`src/gax/.../generated/mod.rs`. So far, the `.sidekick.toml` configurations are
additive, or at most "replace the previous value", but now we want to *remove*
a value.
With this change, one can configure a package to be "ignored". The top-level
`.sidekick.toml` file will list the most common packages, and we will ignore
these in the few places where it makes sense.
That makes the generation of most libraries relatively ergonomic.

feat(generator): ignore some packages

---

generator/internal/genclient/language/common/common.go
generator/internal/genclient/language/internal/rust/rust.go
generator/internal/genclient/language/internal/rust/rust_test.go
generator/internal/genclient/model.go
generator/internal/genclient/parser/openapi/openapi.go
generator/internal/genclient/parser/protobuf/protobuf.go

By default, the rust crate name should be something like
`gcp-sdk-secretmanager-v1`. This change makes it so. We can still
override the name in crates that need it.
Part of the work for #284, fixes #172

feat(generator): improve default rust crate name

---

generator/internal/genclient/parser/protobuf/protobuf.go

Most APIs include multiple `.proto` files from the same directory. But
some services also include `logging/` and other subdirectories we do not
want: the symbols are in a different protobuf package, and they are not
needed to use the service.
In the future we may want more flexibility, maybe specify multiple
directories, or many manually list multiple files. I think this approach
will serve us well for the next few services we choose to generate.

fix(generator/protobuf): limit .proto search depth

---

generator/internal/genclient/license_header.go
generator/sidekick/generate.go
generator/testdata/go/gclient/golden/iam/v1/.sidekick.toml
generator/testdata/go/gclient/golden/typez/.sidekick.toml
generator/testdata/rust/gclient/golden/iam/v1/.sidekick.toml
generator/testdata/rust/gclient/golden/location/.sidekick.toml
generator/testdata/rust/gclient/golden/module/rpc/.sidekick.toml
generator/testdata/rust/gclient/golden/module/type/.sidekick.toml
generator/testdata/rust/gclient/golden/secretmanager/.sidekick.toml
generator/testdata/rust/gclient/golden/type/.sidekick.toml
generator/testdata/rust/openapi/golden/.sidekick.toml

One too many spaces at the beginning of each line, sigh.

fix(generator): correct `.sidekick.toml` boilerplate

---

.github/workflows/lint.yaml

Motivated by #284
It seems silly to format generated files that we should never look at, and it creates additional work when adding new generated crates.

ci: skip formatting of generated toml files

---

src/gax/src/error/rpc/generated/.sidekick.toml

Now `sidekick refreshall` works as expected. It regenerates the
generated files in `src/gax`.
Generated with:
```bash
go -C generator/ run ./sidekick -project-root .. \
-specification-source google/rpc/error_details.proto \
-service-config google/rpc/rpc_publish.yaml \
-output src/gax/src/error/rpc/generated \
-codec-option deserialize-with-defaults=false \
-codec-option generate-module=true \
-codec-option module-path=error::rpc::generated \
-codec-option package:gax=ignore=true \
generate
git add src/gax
cargo fmt
git ls-files -z -- '*.toml' ':!:generator/testdata/**' | xargs -0 taplo fmt
```

chore(gax): save configuration for sidekick

---

generator/internal/parser/parser.go
generator/internal/parser/protobuf/protobuf.go
generator/internal/parser/protobuf/protobuf_test.go
generator/internal/sidekick/refresh.go

* Unexport functions that do not need to be exported.
* Deleted unused code
* Rename parser.NewParser to parser.New to remove redundancy

impl(internal/parser): remove unused code and rename functions

---

generator/internal/language/golang.go
generator/internal/language/golang_test.go
generator/internal/language/language.go

Currently the Codec for each language lives in internal/language/internal/<language>. Merge these into internal/language as unexported functions to reduce nesting.

impl(internal/language): move Codec for Go

---

generator/internal/language/internal/golang/golang.go
generator/internal/language/internal/golang/golang_test.go
generator/internal/language/language.go

There are some naming conflicts I wasn't expecting with https://github.com/googleapis/google-cloud-rust/pull/317 after moving the code to one package.
Going to revert googleapis/google-cloud-rust#316 and close https://github.com/googleapis/google-cloud-rust/pull/317 for now, until I think of a structure that makes sense for this change.

Revert "impl(internal/language): move Codec for Go"

---

generator/internal/parser/protobuf/protobuf.go
generator/internal/parser/protobuf/protobuf_test.go

Unexported NewCodeGeneratorRequest as it's only used within internal/parser/protobuf.
Also handle the error returned by os.Remove.

impl(internal/parser): refactor NewCodeGeneratorRequest

---

generator/internal/genclient/common.go
generator/internal/parser/openapi/openapi.go
generator/internal/parser/protobuf/protobuf.go

This removes a dependency from package parser on package language.

impl: move language/common.go to genclient/

---

generator/internal/genclient/genclient.go
generator/internal/language/rust/rust_test.go
generator/internal/sidekick/refresh.go

Remove unused genclient.CodecOptions and genclient.TemplateDir fields.

impl(internal/genclient): remove unused CodecOptions and TemplateDir

---

generator/internal/language/golang.go
generator/internal/language/golang_test.go
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/sidekick/refresh.go

Merge rust and golang to a single language package. This reduces nesting and also makes it easier to share code between these packages in future PRs.

impl(internal/language): merge rust and golang into one package

---

generator/internal/parser/common.go
generator/internal/parser/openapi.go
generator/internal/parser/protobuf.go

Now that protobuf and openapi are in the same package, move genclient.SplitApiName and genclient.WellKnownMixin to package parser and unexport them, since that is the open place these function are used.

impl(internal/parser): move genclient.SplitApiName and genclient.WellKnownMixin

---

generator/internal/api/codec.go
generator/internal/api/model.go
generator/internal/genclient/genclient.go
generator/internal/genclient/templatedata.go
generator/internal/language/api_test.go
generator/internal/language/golang.go
generator/internal/language/golang_test.go
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/parser/annotations.go
generator/internal/parser/mixin.go
generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/parser/parser_test.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_annotations.go
generator/internal/parser/protobuf_test.go
generator/internal/sidekick/refresh.go

Move the internal API and LanguageCode models to a separate package. This is an intermediary step towards splitting up genclient, and moving the API and Codec models to the same package as the functions that construct them

impl(internal/api): create package

---

generator/internal/parser/openapi.go
generator/internal/parser/parser.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go
generator/internal/parser/service_config.go
generator/internal/sidekick/refresh.go

parser.ParserOptions has been removed because it only contained a few fields and created an extra level of indirection. These fields are now passed directly as arguments to the functions where they are needed.

impl(internal/parser): remove ParserOptions

---

generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/testdata/rust/gclient/golden/iam/v1/src/model.rs
generator/testdata/rust/gclient/golden/location/src/model.rs
generator/testdata/rust/gclient/golden/module/rpc/mod.rs
generator/testdata/rust/gclient/golden/module/type/mod.rs
generator/testdata/rust/gclient/golden/type/src/model.rs
generator/testdata/rust/openapi/golden/src/model.rs
src/gax/src/error/rpc/generated/mod.rs
src/generated/cloud/location/src/model.rs
src/generated/iam/v1/src/model.rs
src/generated/type/src/model.rs

Rust treats any blockquote as a Rust code sample, unless it has the
`norust` tag. Furthermore, `cargo test` will try to compile these code
samples. This is all very good, but we generate the documentation
comments from the Probobuf (or OpenAPI) comments, which may and do
include blockquotes that are not Rust code.
This change handles a few more blockquote types. We really need to parse
the Markdown comments to handle all possible cases, but this can handle
the most urgent cases.
Arguably this is partial progress on #92

impl(generator): better blockquote handling

---

src/gax/src/error/core_error.rs

The code snippet could not compile because it used the wrong package
name. This went undetected, as we disabled the documentation tests
(see #92 for details).

fix(gax): wrong package name in code snippet

---

Cargo.lock
src/gax/src/error/rpc/mod.rs
src/gax/src/query_parameter.rs
src/gax/src/request_parameter.rs
src/gax/tests/query_parameters.rs
src/wkt/Cargo.toml
src/wkt/src/any.rs
src/wkt/src/duration.rs
src/wkt/tests/any.rs
src/wkt/tests/duration.rs

The `Duration` type only supports values in the range
`[-10_000, 10_000]` years (plus 10^9-1 nanos). Any other values result
in undefined behavior. It seems worthwhile to enforce this restriction,
as opposed to letting things fail on serialization or (worse) silently
convert to an invalid duration.
Part of the work for #328

feat(wkt): enforce range limits in `Duration`

---

.github/workflows/sdk.yaml

The generator protects enough code blocks to enable these tests.

ci: enable docs testing

---

generator/internal/language/codec.go
generator/internal/sidekick/genclient.go
generator/internal/sidekick/refresh.go
generator/internal/sidekick/templatedata.go

The LanguageCodec interface is implemented by types within the language package. Move the interface to the language package so that its definition and implementations are co-located.

impl(internal/language): move api.LanguageCode to language

---

src/gax/tests/query_parameters.rs
src/integration-tests/src/secret_manager/openapi_locational.rs
src/integration-tests/src/secret_manager/protobuf.rs
src/wkt/src/timestamp.rs
src/wkt/tests/timestamp.rs

The `Timestamp` type only supports values in the range
`[0001-01-01T00:00:00Z, 9999-12-31T23:59:59.999999999Z]`. Any other
values result in undefined behavior. It seems worthwhile to enforce this
restriction, as opposed to leeting things fail on serialization or
(worse) silently convert to an invalid timestamp.
Fixes #328

feat(wkt): enforce range limits in `Timestamp`

---

Cargo.lock
src/wkt/Cargo.toml
src/wkt/src/duration.rs
src/wkt/tests/duration.rs

Implement traits to convert `Duration` to `std::time::Duration` (and
vice-versa) and traits to convert `Duration` to `time::Duration` (and
vice-versa). The latter are protected by a feature.
We cannot safely convert from `std::time::Duration` to the
`wkt::Duration` because Rust has higher maximum value.
We cannot safely convert from `wkt::Duration` to `std::time::Duration`
because `wkt::Duration`s can be negative, while Rust supports only
positive intervals.
But in the normal case something like `Duration::try_from(x)?` should
work in both directions.
It is always safe to convert `Duration` to `time::Duration`, but not in the
opposite direction.
Finally, `time::Duration` is protected by a feature because the `time` crate is
not 1.0, and we should avoid unstable APIs in our own APIs.
Fixes …

feat(wkt): conversion traits for `Duration`

---

src/wkt/src/timestamp.rs
src/wkt/tests/timestamp.rs

`Timestamp` objects can be converted to `tim::OffsetDateTime`. These
traits are only enabled if the `time` feature is enabled. The `time`
crate is not (yet) 1.0, we do not want to expose these in our API
by default.
We do not provide conversion to `std::time::Instant`. Those are often
used with timers and other deadlines. Semantically they represent
different things, or at least different use-cases for the same thing.
Fixes #51

feat(wkt): convert traits for `Timestamp`

---

Cargo.lock
src/gax/Cargo.toml
src/gax/src/lib.rs
src/gax/src/paginator.rs

This addes a new Paginator type that can be exposed by List RPCs for auto paginating over async streams. This feature is not yet stable in rust so we should have users opt-in to using this unstable feature. When Streams are added to the stdlib we will likely want to make a breaking change to use the traits defined there.
This currently only auto-paginates over pages. We will need to expand the trait of PageableResponse to also describe items to iterate over to paginate over those. But this seemed like enough complexity for one PR.
Updates: #297

feat(gax): add Stream auto pagination

---

src/wkt/src/duration.rs
src/wkt/src/field_mask.rs
src/wkt/src/timestamp.rs

The next version of clippy simplified some of our code.

cleanup(wkt): prepare for Rust 1.83

---

generator/internal/api/model.go
generator/internal/parser/openapi_test.go
generator/internal/parser/pagination.go
generator/internal/parser/protobuf_test.go
generator/internal/sidekick/templatedata.go

These message types will need to implement a trait to be used with the Paginator type. This means we need to mark them as such in advance. 
Also prep template to start using this data.
Updates: #297

feat(generator): mark messages as pageable responses

---

generator/templates/rust/crate/src/transport.rs.mustache
generator/testdata/rust/gclient/golden/iam/v1/src/transport.rs
generator/testdata/rust/gclient/golden/location/src/transport.rs
generator/testdata/rust/gclient/golden/secretmanager/src/transport.rs
generator/testdata/rust/openapi/golden/src/transport.rs
src/generated/cloud/location/src/transport.rs
src/generated/cloud/secretmanager/v1/src/transport.rs
src/generated/iam/v1/src/transport.rs

In preparation for passing function states around for iterators our execution of RPCs needs to be completely owned and not have references to `self`. This means passing in all the state that is needed to the execute function.
Updates: #297

refactor(generator): make execute and associated fn

---

src/integration-tests/Cargo.toml

Use the same annotation in this hand-crafted crate vs. the generated
crates.

cleanup: consistent "do-not-publish" annotation

---

src/wkt/src/timestamp.rs
src/wkt/tests/timestamp.rs

I accidentally left these fields are public when the type gained some
invariants.

fix(wkt): `Timestamp` fields should be private

---

.sidekick.toml
Cargo.lock
auth/Cargo.toml
src/gax/Cargo.toml
src/generated/cloud/location/Cargo.toml
src/generated/cloud/secretmanager/v1/.sidekick.toml
src/generated/cloud/secretmanager/v1/Cargo.toml
src/generated/iam/v1/.sidekick.toml
src/generated/iam/v1/Cargo.toml
src/generated/type/Cargo.toml
tools/check-copyright/Cargo.toml

Any package we intend to publish should include a version for each of its
dependencies. This PR marks a few more crates as `publish = false`, and marks
all the dependencies with a specific version.

cleanup: published dependencies need versions

---

auth/src/lib.rs
auth/src/metadata.rs

We are never going to fix these TODO entries, the code is going away. In
the interim, they just pollute any search for things to do.

cleanup: remove stale TODO entries

---

generator/internal/sidekick/sidekick.go
generator/internal/sidekick/update.go
generator/internal/sidekick/update_test.go

The `update` command updates the `googleapis-root` SHA and then
refreshes all the generated code.
Fixes #271

feat(generator): new cmd to update googleapis-root

---

Cargo.lock
src/gax/Cargo.toml
src/gax/src/error/rpc/mod.rs

We were missing the `status` field from the JSON encoding.
Fixes #255

feat(gax): support full `Status` message

---

Cargo.lock
src/gax/Cargo.toml
src/gax/build.rs
src/gax/src/api_header.rs
src/gax/src/lib.rs

feat(gax): `x-goog-api-client` header formatter

---

generator/templates/rust/crate/src/client.rs.mustache
generator/testdata/rust/gclient/golden/iam/v1/src/client.rs
generator/testdata/rust/gclient/golden/location/src/client.rs
generator/testdata/rust/gclient/golden/secretmanager/src/client.rs
generator/testdata/rust/openapi/golden/src/client.rs
src/generated/cloud/location/src/client.rs
src/generated/cloud/secretmanager/v1/src/client.rs
src/generated/iam/v1/src/client.rs
src/generated/openapi-validation/src/client.rs

fix(generator): correct rustdoc link for `Arc`

---

generator/internal/sidekick/cmdline_test.go
generator/internal/sidekick/refreshall.go
generator/internal/sidekick/sidekick_test.go
generator/testdata/go/gclient/golden/iam/v1/.sidekick.toml
generator/testdata/go/gclient/golden/typez/.sidekick.toml
generator/testdata/rust/gclient/golden/iam/v1/.sidekick.toml
generator/testdata/rust/gclient/golden/iam/v1/Cargo.toml
generator/testdata/rust/gclient/golden/location/.sidekick.toml
generator/testdata/rust/gclient/golden/module/rpc/.sidekick.toml
generator/testdata/rust/gclient/golden/module/type/.sidekick.toml
generator/testdata/rust/gclient/golden/secretmanager/.sidekick.toml
generator/testdata/rust/gclient/golden/secretmanager/Cargo.toml
generator/testdata/rust/gclient/golden/type/.sidekick.toml
generator/testdata/rust/openapi/golden/.sidekick.toml

This separates the generator tests from the `google-cloud-rust`
configuration. I want to make changes to the top-level `.sidekick.toml`
without impacting the generator golden files.
It also helps (I think) with an eventual move of the generator to a new
repository.

cleanup: fewer references to `generator/`

---

src/auth/src/credentials.rs

For MDS based creds, universe domain needs to be obtained via a call to MDS endpoint. Since there is a possibility of a failure, changing return type from Option to Result.

fix: Update return type of  get_universe_domain to Result

---

.github/workflows/sdk.yaml
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/testdata/rust/gclient/golden/module/rpc/mod.rs
generator/testdata/rust/gclient/golden/module/type/mod.rs
generator/testdata/rust/gclient/golden/secretmanager/src/model.rs
generator/testdata/rust/gclient/golden/type/src/model.rs
generator/testdata/rust/openapi/golden/src/model.rs
src/gax/src/error/rpc/generated/mod.rs
src/generated/cloud/secretmanager/v1/src/model.rs
src/generated/iam/v1/src/model.rs
src/generated/openapi-validation/src/model.rs
src/generated/type/src/model.rs

Rustdoc requires URLs to be in angle brackets, it warns if they are not,
and does not autolink them. The comments in most proto files assume
autolinking.
Fixes #403

feat(generator/rust): make URLs rustdoc-friendly

---

.taplo.toml
Cargo.toml
src/gax/Cargo.toml

This is mostly to make maintenance of the top-level `Cargo.toml` file
easier. When `sidekick generate` a new crate it gets into the right
place, and that minimizes conflicts if two developers add different
crates.

chore: keep TOML arrays sorted

---

doc/contributor/howto-guide-generated-code-maintenance.md

Remove the need for a manual edit in the library generation steps. I
think that makes things easier to script, and (maybe) eventually make it
part of steps driven by the Rust Codec.

docs: no manual edits on library generation steps

---

src/gax/src/request_parameter.rs
src/wkt/src/duration.rs
src/wkt/src/timestamp.rs

Change the `Duration` and `Timestamp` well known types so it is easier
to format them as strings (their prescribed JSON formatting). Take
advantage of this change in the implementation of request parameters.
Fixes #136

cleanup(gax): simpler request parameter formatting

---

.sidekick.toml
Cargo.lock
auth/Cargo.toml
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/language/templates/rust/crate/Cargo.toml.mustache
generator/testdata/rust/gclient/golden/iam/v1/Cargo.toml
generator/testdata/rust/gclient/golden/location/Cargo.toml
generator/testdata/rust/gclient/golden/secretmanager/Cargo.toml
generator/testdata/rust/gclient/golden/type/Cargo.toml
generator/testdata/rust/openapi/golden/Cargo.toml
src/generated/cloud/location/Cargo.toml
src/generated/cloud/secretmanager/v1/Cargo.toml
src/generated/iam/v1/Cargo.toml
src/generated/openapi-validation/Cargo.toml
src/generated/type/Cargo.toml

Remove all hard-coded packages from `Cargo.toml.mustache`. Having the
list on the template file would require changing the  generator when
a new version of these packages is needed. We can keep this list of
packages in the top-level `.sidekick.toml` file, which is easier to
manually change when needed (and then just `sidekick refreshall`).

cleanup(generator/rust): no fixed packages templates

---

generator/internal/language/rust.go
generator/internal/language/rust_test.go

Sometimes we want to depend on a package, but disable the default
features. That can help us trim the dependencies.
Motivated by #433

feat(generator/rust): packages w/o default features

---

Cargo.lock
src/gax/Cargo.toml
src/gax/tests/paginator.rs

Use the [`axum`](https://crates.io/crates/axum) framework to write the
integration tests. Mainly because it has more up to date dependencies.

test(gax): switch to `axum`

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/credentials.rs

Move around the definitions for the Credential trait, as per the design. The crate version is `0.0.0`, this is fine.
Let me know what all needs documenting. Anything `pub`?
And whether I need/want unit tests for `impl traits::Credential for Credential`

impl(auth): credential traits in modules

---

.github/dependabot.yml
ci/requirements.txt
generator/README.md

Also remove this tooling from dependabot automatic updates. We don't
care that much about keeping the tools up to date, and I care more about
stable CI and tooling.

ci: update mdformat version and reformat

---

.sidekick.toml
Cargo.lock
src/generated/cloud/location/Cargo.toml
src/generated/cloud/secretmanager/v1/Cargo.toml
src/generated/iam/v1/Cargo.toml
src/generated/openapi-validation/Cargo.toml
src/generated/type/Cargo.toml

I want to create a test release, one that is marked as pre-release on
GitHub and where the crates are all `*-rc1`. The idea is to find out
what is broken (if anything) in our crate definitions, dependencies,
documentation, etc.

chore: prepare for a test release

---

src/auth/src/credentials.rs
src/auth/src/lib.rs

Re: https://github.com/googleapis/google-cloud-rust/pull/455#discussion_r1887541999

refactor(auth): move `Result` definition

---

src/gax/Cargo.toml
src/gax/src/lib.rs
src/gax/src/paginator.rs

- We need to make this type fully Send so we can satisfy our dyntraits. 
- Align the feature name to be consistent with other unstable features.
- Impl Debug so tracing will work with the returned type
Updates: #297

fix: make paginator Send and align feature names

---

.sidekick.toml
Cargo.lock
src/auth/Cargo.toml
src/gax/Cargo.toml
src/generated/cloud/location/Cargo.toml
src/generated/cloud/secretmanager/v1/Cargo.toml
src/generated/iam/v1/Cargo.toml
src/generated/openapi-validation/Cargo.toml
src/generated/type/Cargo.toml
src/wkt/Cargo.toml

Missed the hand-crafted libraries (wkt, gax, auth) in the *-rc1
versions.

chore: prepare for 0.1.0-rc2

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/credentials.rs
src/auth/src/credentials/user_credential.rs
src/auth/src/errors.rs
src/auth/src/token.rs

Introduce the (internal) `TokenProvider`, and (internal) `UserCredential` types.
My intention is to mock the `TokenProvider` in the test cases. It looks like unit tests for internal classes belong in the same file as the implementation, so that is what I did for `user_credential.rs`.
Q: Should unit tests return `Result`s?
I decided to cut off the PR early (without implementing `get_headers()`) because I have probably made too many mistakes already.
Note that `CredentialError` is using a `Box`, so we cannot clone it. That prevents me from using code like this in my test. Maybe it should use an `Arc`?
```rs
struct TestTokenProvider {
token: Result<Token>,
}
```

impl(auth): introduce `TokenProvider`, `UserCredentials`

---

src/gax/src/api_header.rs
src/gax/src/error/rpc/mod.rs
src/gax/src/paginator.rs
src/gax/tests/paginator.rs

I for one welcome our clippy overlords.
The only controversial thing may be silencing the warning around
`next()`. Clippy thinks we should be implementing the `Iterator` trait
or think of a better method name.  Clippy is wrong, neither suggestion
applies here.

cleanup(gax): fix (or silence) clippy warnings

---

.sidekick.toml
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go
generator/internal/parser/service_config.go
generator/internal/sidekick/downloads_cache.go
generator/internal/sidekick/downloads_cache_test.go
generator/internal/sidekick/generate.go
generator/internal/sidekick/refreshall.go
src/generated/showcase/.not-working-sidekick.toml

Eventually we will want to download and compile the showcase protos.
That require an "extra" proto source that is also downloadable. This
PR introduces that source, but does not enable it, as the comments in
showcase break the parser.

feat(generator): extra downloadable proto sources

---

src/gax/src/lib.rs
src/gax/src/options/mod.rs

Introduce a struct to represent all per-request options. We will use
this type in the generated code, but only as a passthru. Creating a
placeholder unblocks the generator changes while we work on fine tuning
the options.
Part of the work for #469

impl(gax): request options placeholder

---

generator/internal/language/codec.go
generator/internal/language/golang.go
generator/internal/language/rust.go
generator/internal/sidekick/genclient.go

This will be used in a future PR for iterator support.

refactor: pass API to codec.AdditionalContext and stub out Rust context

---

generator/internal/api/model.go
generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/parser/parser_test.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go
generator/internal/sidekick/templatedata.go

Sometimes we need to find the service that owns a method. Add a
backlink and simplify some code.

cleanup(generator): link method to service

---

Cargo.lock
generator/internal/language/templates/rust/crate/src/client.rs.mustache
generator/testdata/rust/gclient/golden/iam/v1/src/client.rs
generator/testdata/rust/gclient/golden/location/src/client.rs
generator/testdata/rust/gclient/golden/secretmanager/src/client.rs
generator/testdata/rust/openapi/golden/src/client.rs
src/generated/cloud/location/src/client.rs
src/generated/cloud/secretmanager/v1/src/client.rs
src/generated/iam/v1/src/client.rs
src/generated/openapi-validation/src/client.rs
src/integration-tests/Cargo.toml
src/integration-tests/tests/mocking.rs

Add the necessary constructor and a new integration test.
Fixes #469

feat(generator/rust): make clients mockable

---

src/gax/src/error/rpc/mod.rs
src/gax/tests/errors.rs

The error details are encoded as any. Protobuf encodes the type in the
`@type` field, and we can use it to disambiguate what error detail we
are dealing with.
Fixes #291

feat(gax): use `@type` to tag `ErrorDetails`

---

generator/internal/language/templates/rust/crate/src/model.rs.mustache
generator/internal/language/templates/rust/mod/mod.rs.mustache
generator/internal/sidekick/sidekick_test.go
generator/internal/sidekick/templatedata.go
generator/testdata/googleapis/google/rpc/code.proto
generator/testdata/rust/gclient/golden/module/rpc/.sidekick.toml
generator/testdata/rust/gclient/golden/module/rpc/mod.rs
src/generated/type/src/model.rs

We need to generate top-level enums, that is, those that are not nested
within a message.

feat(generator/rust): top-level enums

---

src/auth/src/errors.rs

We will use this function to tell us which errors are retryable. I think they apply broadly (not just to user credentials), so they go in `errors.rs`.

impl(auth): add helper for retryable errors

---

generator/internal/sidekick/update.go
generator/internal/sidekick/update_test.go

The `update` command updates the top-level `.sidekick.toml` file. This file is
hand-crafted, and contains comments and other annotation. We need to preserve
those or the updates get tedious.

feat(generator/rust): `update` cmd preserves comments

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/credentials/user_credential.rs

Part of the work for #442
Add OAuth2 request/response types and test their serialization/deserialization. (Re: https://github.com/googleapis/google-cloud-rust/pull/489/files#r1893394717)

impl(auth): oauth2 token req/resp types

---

generator/internal/api/model.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_annotations.go
generator/internal/parser/protobuf_test.go
generator/internal/parser/testdata/test_service.proto
generator/internal/sidekick/templatedata.go

We will cannot support streaming methods, or methods that lack HTTP
annotations. Skip them until we have the support for them.

feat(generator): skip unsupported methods

---

Cargo.lock
generator/internal/language/templates/rust/crate/src/builders.rs.mustache
generator/internal/language/templates/rust/crate/src/transport.rs.mustache
generator/testdata/rust/gclient/golden/iam/v1/src/builders.rs
generator/testdata/rust/gclient/golden/iam/v1/src/transport.rs
generator/testdata/rust/gclient/golden/location/src/builders.rs
generator/testdata/rust/gclient/golden/location/src/transport.rs
generator/testdata/rust/gclient/golden/secretmanager/src/builders.rs
generator/testdata/rust/gclient/golden/secretmanager/src/transport.rs
generator/testdata/rust/openapi/golden/src/builders.rs
generator/testdata/rust/openapi/golden/src/transport.rs
src/gax/Cargo.toml
src/gax/src/http_client/mod.rs
src/gax/src/lib.rs
src/gax/src/options/mod.rs
src/gax/tests/echo_server.rs
src/gax/tests/paginator.rs
src/gax/tests/user_agent.rs
src/generated/cloud/location/src/builders.rs
src/generated/cloud/location/src/transport.rs
src/generated/cloud/secretmanager/v1/src/builders.rs
src/generated/cloud/secretmanager/v1/src/transport.rs
src/generated/iam/v1/src/builders.rs
src/generated/iam/v1/src/transport.rs
src/generated/openapi-validation/src/builders.rs
src/generated/openapi-validation/src/transport.rs
src/integration-tests/src/secret_manager/protobuf.rs

This introduces an end-to-end option from the generated code all the
way down to the `ReqwestClient::execute()` method. The option is not
particularly important (though it is used by some customers), but it is
easy to understand.
Fixes #436

feat(gax): support `user-agent` option

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/credentials/user_credential.rs

Feel free to throw this PR back at me if it is too large.
Add and implement a `UserTokenProvider` for talking with `oauth2.googleapis.com/token`.
I am aware of #389. We should probably start tracking error kinds. I didn't do it in this PR.
We make a fake server in 4 different unit tests. I really wanted something like:
```
fn MakeHandler(response: OAuth2RefreshResponse) -> axum::handler::Handler;
```
But I couldn't figure it out. So we have 1 handler function per test to test the different response possibilities.
I also did not know how to fake a time in the unit test that checks the expiration time, so I just used a comparison operator.
There are none. I did manually use my authorized user credentials and successfully get tokens from …

impl(auth): token provider for user credentials

---

generator/internal/language/rust.go
generator/internal/language/rust_test.go

We need to link the oneof documentation.

fix(generator/rust): rustdoc links for oneofs

---

Cargo.lock
src/gax/Cargo.toml
src/gax/src/lib.rs
src/gax/src/query_parameter.rs
src/gax/src/request_parameter.rs
src/gax/tests/query_parameters.rs

We also need to support `bool` and `bytes` path and query parameter
types. Both are used in `gapic-showcase`, hopefully because real
services use them.

fix(gax): more request parameter types

---

generator/internal/language/codec.go
generator/internal/language/golang.go
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/sidekick/templatedata.go

Refactor the code to decide what methods are skipped to the codec. Then
avoid linking those methods in the `rustdoc` documentation.

feat(generator): do not link skipped methods

---

src/gax/Cargo.toml
src/gax/src/http_client/mod.rs
src/gax/src/options/mod.rs
src/gax/tests/echo_server.rs
src/gax/tests/timeout.rs

Support setting per-attempt timeouts on the request builders, and use
these timeouts when sending the RPC.
Fixes #435

feat(gax): per-attempt timeouts

---

src/gax/src/error/http_error.rs
src/gax/src/error/mod.rs
src/gax/src/error/rpc/mod.rs
src/gax/tests/errors.rs
src/gax/tests/http_client_errors.rs

The implementation of `Status::try_from()` works better with references: we will use a reference to deserialize the bytes, and we often have a reference to `HttpError` as the result of `err.as_inner()`.
Motivated by #437 where I will need to examine the status more often than not.

cleanup(gax): simplify `Status::try_from()`

---

src/gax/src/request_parameter.rs
src/wkt/src/duration.rs
src/wkt/tests/duration.rs

For #423. 
This PR focuses on the conversion between a String representation and Duration.
Verified locally with: `cargo fmt && cargo clippy -- --deny warnings && cargo test`

feat: rely on try/from trait for Duration conversions

---

.sidekick.toml
Cargo.lock
src/auth/Cargo.toml
src/gax/Cargo.toml
src/generated/cloud/location/Cargo.toml
src/generated/cloud/secretmanager/v1/Cargo.toml
src/generated/iam/v1/Cargo.toml
src/generated/longrunning/Cargo.toml
src/generated/openapi-validation/Cargo.toml

So this is a problem with a strict "sidekick always regenerates all the files, including Cargo.toml" we cannot use external tools to update the dependencies for us.

chore(deps): update reqwest to 0.12.11

---

Cargo.lock
src/wkt/Cargo.toml
src/wkt/src/duration.rs

For #423.
Add TryFrom trait for conversion between [chrono::time](https://crates.io/crates/chrono) and `Duration`.

feat: add try/from trait for conversion between chrono and Duration

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/credentials.rs

Adds a helper function (to be used shortly) that returns the path to look up ADC.
Note that the path changes depending on the OS.
~I do not think our CI exercises the Windows code path. I successfully ran a `cargo test` on my windows machine, if that means anything.~
**EDIT:** Good thing we have Windows coverage thanks to #554.
This is the first use of `scoped_env::ScopedEnv`. I found it helpful: https://docs.rs/scoped-env/latest/scoped_env/index.html

impl(auth): helper function for ADC path

---

generator/internal/parser/httprule/http_rule_parser.go
generator/internal/sidekick/generate.go

Followed [@coryan's recommendation](https://github.com/googleapis/google-cloud-rust/pull/545#discussion_r1899849354) on #545 and changed the parser functions to consume as many runes as possible (instead of the full string), and return a counter alongside the successful result. This reduced the number of checks each parser function had to make, and made the code easier to read.

cleanup(sidekick): revised and simplified http annotation parser

---

generator/internal/sidekick/generate.go
src/gax/src/http_client/mod.rs
src/gax/src/options/mod.rs

Preparing for `RequestOptions` to gain a number of new attributes, it
seems better to improve the coverage. I also noticed an incorrect method
name and fixed it.
Motivated by #437

test(gax): improve `RequestOptions` coverage

---

generator/internal/language/codec.go
generator/internal/language/codec_test.go
generator/internal/language/golang.go
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/language/templates/rust/crate/src/client.rs.mustache
generator/internal/sidekick/templatedata.go
generator/testdata/rust/gclient/golden/iam/v1/src/client.rs
generator/testdata/rust/gclient/golden/location/src/client.rs
generator/testdata/rust/gclient/golden/secretmanager/src/client.rs
generator/testdata/rust/openapi/golden/src/client.rs
src/generated/cloud/location/src/client.rs
src/generated/cloud/secretmanager/v1/src/client.rs
src/generated/iam/v1/src/client.rs
src/generated/longrunning/src/client.rs
src/generated/openapi-validation/src/client.rs
src/integration-tests/src/secret_manager/openapi.rs
src/integration-tests/src/secret_manager/openapi_locational.rs
src/integration-tests/src/secret_manager/protobuf.rs
src/integration-tests/tests/mocking.rs

Change the generated code to require any arguments that will be part of
the path parameters. These include optional fields (such as objects)
where it is a sub-field of the parameter that goes into the path
parameter.
Part of the work for #536

feat(generator/rust): require path parameters

---

generator/internal/language/templates/rust/crate/src/client.rs.mustache
generator/internal/language/templates/rust/crate/src/lib.rs.mustache
generator/testdata/rust/openapi/golden/src/client.rs
generator/testdata/rust/openapi/golden/src/lib.rs
generator/testdata/rust/protobuf/golden/iam/v1/src/client.rs
generator/testdata/rust/protobuf/golden/iam/v1/src/lib.rs
generator/testdata/rust/protobuf/golden/location/src/client.rs
generator/testdata/rust/protobuf/golden/location/src/lib.rs
generator/testdata/rust/protobuf/golden/secretmanager/src/client.rs
generator/testdata/rust/protobuf/golden/secretmanager/src/lib.rs
src/gax/src/lib.rs
src/generated/cloud/location/src/client.rs
src/generated/cloud/location/src/lib.rs
src/generated/cloud/secretmanager/v1/src/client.rs
src/generated/cloud/secretmanager/v1/src/lib.rs
src/generated/iam/v1/src/client.rs
src/generated/iam/v1/src/lib.rs
src/generated/longrunning/src/client.rs
src/generated/longrunning/src/lib.rs
src/generated/openapi-validation/src/client.rs
src/generated/openapi-validation/src/lib.rs
src/integration-tests/src/secret_manager/openapi.rs
src/integration-tests/src/secret_manager/openapi_locational.rs
src/integration-tests/src/secret_manager/protobuf.rs
src/integration-tests/tests/mocking.rs

We were using an alias of an alias for in the generated code. Just use
the type directly.
Motivated by #437

cleanup: simplify generated code

---

src/gax/src/request_parameter.rs
src/wkt/src/timestamp.rs
src/wkt/tests/timestamp.rs

Fixes #423 
- Replaces use of `to_json` and `from_json` with TryFrom traits for conversion between `Timestamp` and String representations. 
- Adds TryFrom traits for conversion between `chrono::DateTime` and `Timestamp`. **Note** that additional tests have been added to a separate `tests/timestamp.rs` following the convention set by existing tests that verify conversion between `Timestamp` and `time::OffsetDateTime`.

feat: add try/from traits for conversion between Timestamp and String/chrono::DateTime

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/credentials.rs
src/auth/src/credentials/user_credential.rs
src/auth/tests/credentials.rs

Load ADC from a file. Parse the contents of the json. If the `type == "authorized_user"`, then create user credentials. In any other case, return an error.
In a follow up, I will hook this thing up to the MDS credentials.
There are still no integration tests. We will just check that Credentials are successfully created, not that tokens are successfully retrieved.

feat(auth): user credentials from ADC

---

Cargo.lock
src/gax/Cargo.toml
src/gax/src/lib.rs
src/gax/src/options/mod.rs
src/gax/src/retry_policy.rs
src/gax/tests/retry_policy.rs

This introduces a trait and some implementations to drive retry loops.
The policy controls for how long the retry loop runs, and what errors
are considered retryable.
Part of the work for #437.  #565  maybe give you a more complete picture of where this is going.

feat(gax): introduce `RetryPolicy`

---

src/auth/src/credentials.rs
src/auth/src/credentials/mds_credential.rs
src/auth/tests/credentials.rs

If the ADC path is not known, or the file does not exist, fallback to MDS credentials.
If the ADC path is found, but malformed in some way, we do not fallback, we return the error.
We are desperate for some integration tests. The unit tests just verify that some credentials are successfully made. They cannot tell the difference between MDS and User Credentials. It also wouldn't make sense to try to use the token providers in the unit tests.

feat(auth): fallback to MDS credentials

---

src/auth/src/credentials.rs
src/auth/src/credentials/mds_credential.rs
src/auth/src/credentials/user_credential.rs
src/auth/src/errors.rs
src/auth/src/token.rs

Make the credentials easier to troubleshoot. Implementing the `Debug`
traits will help us log their state at runtime, including what specific
token provider is in use.
In some cases we need to censor some fields because they contain
sensitive information. We may consider logging a hash of the field, or
maybe the first N characters of the field and a hash. I decided to be
conservative for now.

feat(auth): implement `std::fmt::Debug` trait

---

src/auth/tests/credentials.rs

Thanks to #589, we have a convenient way to validate credential types in unit tests.

test(auth): validate credential types

---

src/auth/src/credentials.rs
src/auth/src/credentials/mds_credential.rs
src/auth/src/credentials/user_credential.rs
src/auth/src/token.rs

The `gax::http_client::ReqwestClient` has `Clone`. We want it to hold `auth::credential::Credential`. So `Credential` needs `Clone` as well.
We definitely want the interfaces in the `traits::Credential` to take `&self` instead of `&mut self`. We want to be able to call these things in `ReqwestClient::execute(&self, ...)`.
This PR also changes the `TokenProvider`'s traits to use `&self` instead of `&mut self`. This is not necessarily what we want in the long term, but it unblocks us for now.
When we introduce caching, we will be mutating some aspect of the token provider. We could have the caching layer hold an interior mutable cache.
I think more likely though, we will want the `*Credential` types to hold an interior mutable token provider.
We can solve the …

impl(auth): Credentials have clone

---

Cargo.lock
src/auth/src/credentials.rs
src/gax/Cargo.toml
src/gax/src/http_client/mod.rs
src/gax/src/options/mod.rs
src/gax/tests/auth.rs
src/gax/tests/http_client_errors.rs
src/gax/tests/paginator.rs
src/gax/tests/timeout.rs

Fixes #442
Swap out the `gax` implementation of auth from `google-cloud-auth` to `gcp-sdk-auth`.
The GCB build runs integration tests using the `MDSCredentials` written by @harkamaljot.
Also introduces fake credentials in `gcp_sdk_auth::credentials::testing`. I think we need a public module. I don't think this thing gets exported to other crates if we gate it with a `#[cfg(test)]`.
I would like to fix the mocking story for credentials, and use them in the auth unit test. But I will defer that. It is tracked in #593

impl: swap out auth implementation in gax

---

src/auth/src/credentials.rs
src/auth/src/credentials/mds_credential.rs
src/auth/src/credentials/user_credential.rs
src/gax/src/http_client/mod.rs
src/gax/src/options/mod.rs

rename
- `credentials::traits::Credential` -> `credentials::CredentialTrait`
- `credentials::traits::dynamic::Credential` -> `credentials::dynamic::CredentialTrait`
In response to: https://github.com/googleapis/google-cloud-rust/pull/594#discussion_r1903318243

cleanup(auth): rename traits

---

Cargo.lock
src/gax/Cargo.toml
src/gax/src/backoff_policy.rs
src/gax/src/lib.rs
src/gax/src/options/mod.rs
src/gax/tests/backoff_policy.rs

Introduce `BackoffPolicy` a trait that defines how long the retry
loop waits before making a new attempt.  Provide the most common
implementation: truncated exponential backoff with (full) jitter.
Part of the work for #437

feat(gax): introduce `BackoffPolicy`

---

src/gax/src/backoff_policy.rs
src/gax/src/lib.rs
src/gax/src/options/mod.rs
src/gax/src/retry_throttler.rs
src/gax/tests/backoff_policy.rs
src/gax/tests/retry_throttler.rs

Introduce the `RetryThrottler` trait and a couple of implementations.
This is used to limit the number of retries when too many retries are
failing. That can improve the recovery time under large failure or
overload conditions. Unlike backoff or retry policies, a single
RetryThrottler is used for all the requests in a client, or even in
multiple clients.

feat(gax): introduce `RetryThrottler`

---

generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go

Some service config yaml files may be missing the `Description` section.
The generator was crashing in this case. Instead, we generate services
with a missing description for the crate.
Fixes #606

fix(generator): crashes reading service config yaml

---

src/gax/src/options/mod.rs

feat(gax): support passing idempotency as a request option

---

generator/internal/language/templates/rust/crate/src/transport.rs.mustache
generator/testdata/rust/openapi/golden/src/transport.rs
generator/testdata/rust/protobuf/golden/iam/v1/src/transport.rs
generator/testdata/rust/protobuf/golden/location/src/transport.rs
generator/testdata/rust/protobuf/golden/secretmanager/src/transport.rs
src/generated/cloud/location/src/transport.rs
src/generated/cloud/secretmanager/v1/src/transport.rs
src/generated/cloud/workflows/v1/src/transport.rs
src/generated/iam/v1/src/transport.rs
src/generated/longrunning/src/transport.rs
src/generated/openapi-validation/src/transport.rs

Note that there is no default retry policy, so this has no effect
beyond reducing the amount of code customers have to write to enable
retry loops.
Part of the work for #437

feat(generator): provide default idempotency

---

generator/internal/api/model.go
generator/internal/language/templates/rust/crate/src/builders.rs.mustache
generator/internal/language/templates/rust/crate/src/client.rs.mustache
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_annotations.go
generator/internal/parser/protobuf_test.go
generator/internal/parser/testdata/test_operation_info.proto
generator/internal/sidekick/templatedata.go
generator/testdata/googleapis/google/longrunning/operations.proto
generator/testdata/googleapis/google/rpc/status.proto
generator/testdata/rust/protobuf/golden/module/rpc/mod.rs
src/generated/cloud/workflows/v1/src/builders.rs
src/generated/cloud/workflows/v1/src/client.rs

If a method has the LRO annotations, capture them into the model and the
mustache templates model.
Mostly to convince myself this is working: generate better documentation using
these annotations. We cannot generate LRO helpers, but we can tell callers what
types to expect in the LRO.
Fixes #561

feat(generator): capture protobuf LRO options

---

src/auth/src/credentials.rs
src/gax/src/http_client/mod.rs
src/gax/src/options/mod.rs

Part of the work for #593 
`Credential` need not get its public interfaces from `CredentialTrait`.
We want to define
```rs
impl<T> std::convert::From<T> -> Credential
where T: CredentialTrait;
```
But if `Credential` implements `CredentialTrait`, this will conflict with the generic `impl<T> From<T> -> T`. (let `T = Credential` to see the problem).
The fix is to manually define the public interface for `Credential`.
This has some benefits:
1. Consumers do not need to `use auth::credentials::CredentialTrait` to have access to the methods.
1. The interface should read nicer. It is a simple `async fn`, instead of a `fn ... -> impl Future<Output = ...>`

fix(auth): Credential API

---

src/auth/src/credentials.rs
src/auth/tests/credentials.rs

Most of the work for #593
For things that implement (the public, sync) `CredentialTrait`, add an implementation for (the private, dyn) `dynamic::CredentialTrait`.
Add a constructor to create `Credential` from something that implements `CredentialTrait`.
Add a test (outside the crate) that demonstrates mocking.
Arguably the `mockall::mock! { ... }` belongs in a document somewhere. I will think about that.

feat(auth): mockable Credentials

---

src/gax/src/paginator.rs

This only comes up under:
```
cargo clippy -p gcp-sdk-gax --features unstable-stream
```
That is a rarely used feature combo. I was trying to test all feature
combos.

cleanup(gax): unused code with a feature combo

---

src/auth/src/credentials.rs
src/auth/tests/credentials.rs

It is simpler to return an empty vector (which @coryan did in #592).
We were using `test_credentials()` in gax's unit test for auth, and relying on there being an `Authorization` header to verify the credentials. Now (after #631) we no longer use the `test_credentials()`, so we can simplify the `test_credentials()`.
Also add tests because this is a public interface.

cleanup(auth): simpler test credentials

---

src/wkt/src/any.rs
src/wkt/src/duration.rs
src/wkt/src/empty.rs
src/wkt/src/field_mask.rs
src/wkt/src/lib.rs
src/wkt/src/message.rs
src/wkt/src/timestamp.rs

Introduce a trait that all messages will (eventually) implement. `Any`
uses this trait to correctly set the `@type` field.
Part of the work for #98, I will be sending the generator changes after this PR, and then finally fixing the issue, see #642 to see the full picture.

feat(wkt): supporting traits for better `Any`

---

src/gax/src/error/rpc/mod.rs

Sometimes we receive a `rpc::model::Status` as part of a larger message,
and may want to convert this into a `gax::*::Status` to examine the
error details with less of a fuss.
Part of the work for #640

feat(gax): `Status` from a `rpc::model::Status`

---

src/gax/src/error/http_error.rs
src/gax/src/http_client/mod.rs
src/gax/tests/errors.rs

The function to convert HTTP headers into something we can use in
`HttpError` was used only in `http_client/mod.rs`, so move it there and
make it private.
In the process, I noticed we were printing sensitive headers, so I
changed the code to avoid doing so. I am not sure if any incoming
headers are labeled sensitive, but it does not hurt to prevent
embarrassing leaks.
I had to move some test code, which motivated some changes to it:
instead of testing that we can create an `HttpError` from a response,
verify that the `ReqwestClient` does this and verify its output.

cleanup(gax): move `convert_headers()`

---

src/gax/src/error/mod.rs
src/gax/src/error/service_error.rs

This will represent errors received from the service, with a `Status`
attached.  For now this is unused, a future PR will use these in
`ReqwestClient` (when applicable) and even further into the future we
will use these for LROs and other requests that include a
`google.rpc.Status`.
Fixes #640

impl(gax): introduce `ServiceError`

---

src/gax/src/error/core_error.rs
src/gax/src/error/mod.rs
src/gax/src/error/rpc/mod.rs
src/gax/src/http_client/mod.rs
src/gax/src/retry_policy.rs
src/gax/tests/errors.rs
src/gax/tests/http_client_errors.rs
src/gax/tests/retry_loop.rs

Return a `ServiceError` when the response includes a `Status`, and
reserve `HttpError` for responses that just have a blob of bytes.

feat(gax): use `ServiceError` for responses

---

src/auth/src/credentials.rs
src/auth/src/credentials/user_credential.rs

Fixes #651
Parse `quota_project_id` if it is part of an Authorized User Credential in ADC.
Include the quota project in requests as the `x-goog-user-project` header.

feat(auth): support quota project in UserCredentials

---

generator/internal/language/rust_test.go

In `TestRust_ParseOptions`, ensure that `RustCodec.ExtraPackages` is sorted before comparing the output, so the packages appear in the same order.

impl(internal/language): make TestRust_ParseOptions deterministic

---

generator/internal/language/golang.go
generator/internal/language/golang_test.go

Refactor `TestGo_MessageNames` into a parameterized test, and remove the use of `newTestAPI` since the `state` argument is unnecessary. The `state` parameter exists solely because `GoCodec` needs to implement the `Codec` interface. 
Additionally, explicitly document that `state` is not utilized by either `GoCodec.MessageName` or `GoCodec.FQMessageName`.

impl(internal/language): refactor TestGo_MessageNames

---

generator/internal/language/client.go
generator/internal/sidekick/refresh.go

The GenerateClientRequest struct currently contains only three fields. To simplify the code, eliminate the struct and pass its fields directly as arguments to the GenerateClient function.

impl(language): delete GenerateClientRequest

---

.sidekick.toml
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/language/rusttemplate.go

Use named features to decide what packages are used. Makes it easier to
accomodate LRO helpers, and maybe other upcoming features, such as
streaming RPCs and gRPC-based libraries.

feat(generator/rust): named features for used pkgs

---

Cargo.lock
Cargo.toml
src/lro/Cargo.toml
src/lro/src/details.rs
src/lro/src/lib.rs
src/lro/tests/fake_library/builders.rs
src/lro/tests/fake_library/client.rs
src/lro/tests/fake_library/mod.rs
src/lro/tests/fake_library/model.rs
src/lro/tests/fake_responses/mod.rs
src/lro/tests/fake_service/mod.rs
src/lro/tests/integration.rs

Introduce a new crate to support LRO helpers. The key abstraction is
`gcp_sdk_lro::Poller`: a type to poll LROs and automatically decode the
metadata and response types.
Fixes #683

feat(lro): new crate for LRO helper support

---

generator/internal/language/client.go
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/language/rusttemplate.go
generator/internal/language/rusttemplate_test.go

Convert several Rust codec methods to functions, as a step towards removing the Rust codec.

impl(language): convert Rust codec methods to functions

---

.sidekick.toml
Cargo.lock
src/generated/cloud/workflows/v1/Cargo.toml

Now that the `gcp-sdk-lro` crate exists, configure `sidekick` to
automatically add this as a dependency of any generated crate with LROs.
Fixes #688

impl: use `gcp-sdk-lro` as a named feature

---

src/gax/src/exponential_backoff.rs
src/gax/src/lib.rs
src/gax/src/options/mod.rs
src/gax/src/polling_backoff_policy.rs

To further simplify the LRO loops we need a configuration option that
controls how long to wait before polling the LRO again.

feat(gax): options have polling backoff policy

---

src/gax/src/lib.rs
src/gax/src/options/mod.rs
src/gax/src/polling_policy.rs

Create new polling policies, these are similar to retry policies, but
different enough that they should be different types. Add configuration
options that have these policies.

feat(gax): polling policies

---

src/gax/src/http_client/mod.rs
src/gax/tests/http_client_polling.rs

We need to access the polling and polling backoff policies in the
implementation of the generated clients.

impl(gax): make polling policies accessible

---

src/gax/src/polling_policy.rs

Polling loops may need to stop on successful polling requests too.
Part of the work for #713

feat(gax): limit polling loops on success too

---

src/lro/src/details.rs

We want to stop the polling loop if it has been running for too long, or
it has made too many polling attempts.
Part of the work for #713

feat(lro): use polling policy on success

---

src/integration-tests/src/workflows.rs
src/integration-tests/tests/driver.rs
src/lro/Cargo.toml
src/lro/src/lib.rs
src/lro/tests/fake_library/builders.rs
src/lro/tests/integration.rs

If the application is not interested in the metadata, they can await an
LRO using:
```rust
let response = client.lro_thing().poller().until_done().await?;
```
Fixes #713 and fixes #715

feat(lro): implement `until_done()` helper

---

src/gax/tests/query_parameters.rs

I am about to change how the generator handles query parameters. Before
doing so, I updated the query parameters test to verify the generated
code will work as we need it to. I also expanded the test to cover more
cases.
Part of the work for #610

test(gax): update tests for query parameters

---

generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/language/rusttemplate.go
generator/internal/language/templates/rust/crate/src/transport.rs.mustache
generator/testdata/rust/openapi/golden/src/transport.rs
generator/testdata/rust/protobuf/golden/location/src/transport.rs
generator/testdata/rust/protobuf/golden/secretmanager/src/transport.rs
src/generated/cloud/location/src/transport.rs
src/generated/cloud/secretmanager/v1/src/transport.rs
src/generated/cloud/workflows/v1/src/transport.rs
src/generated/longrunning/src/transport.rs
src/generated/openapi-validation/src/transport.rs

Support enum query parameters. In the process, simplify the emitted code to
handle the case of optional and repeated parameters.
Part of the work for #610. Effectively enum query parameters work now, but I want to remove some unused code before declaring success (#739 if you want to see what is coming).

feat(generator/rust): handle enum query parameters

---

generator/internal/api/model.go
generator/internal/language/rusttemplate.go
generator/internal/language/templates/rust/common/message.mustache
generator/internal/language/templates/rust/common/oneof.mustache
generator/internal/language/templates/rust/crate/src/builders.rs.mustache
generator/internal/language/templates/rust/crate/src/client.rs.mustache
generator/internal/language/templates/rust/crate/src/transport.rs.mustache

Start a cleanup of the `rusttemplate.go` file. The idea is to minimize
duplication with the `api.*` types. Instead we attach a number of
annotations to `api.Field` that represent the Rust-specific thing.
Other languages will attach different annotation objects. The type of
the annotation is `any` to support this case.
Part of the work for #653, helps with #655, and from there #610 and #482

cleanup(generator): annotate `api.Field` types

---

generator/internal/language/rust.go
generator/internal/language/rust_test.go
src/generated/type/src/model.rs

Also escape URLs that appear as `Example: https://example.com`, but avoid
escaping URLs that appear as `"https://example.com"`.
Part of the work for #748

fix(generator/rust): stricter URL-escaping

---

src/gax/src/path_parameter.rs

Part of the work for #764, #655, and #482

impl(gax): simplify errors on missing path parameter

---

generator/internal/language/templates/rust/crate/src/builders.rs.mustache
generator/testdata/rust/openapi/golden/src/builders.rs
generator/testdata/rust/protobuf/golden/iam/v1/src/builders.rs
generator/testdata/rust/protobuf/golden/location/src/builders.rs
generator/testdata/rust/protobuf/golden/secretmanager/src/builders.rs
src/generated/cloud/location/src/builders.rs
src/generated/cloud/secretmanager/v1/src/builders.rs
src/generated/cloud/workflows/v1/src/builders.rs
src/generated/iam/v1/src/builders.rs
src/generated/longrunning/src/builders.rs
src/generated/openapi-validation/src/builders.rs
src/generated/spanner/admin/database/v1/src/builders.rs
src/generated/spanner/admin/instance/v1/src/builders.rs

We hold the `stub` in an `Arc<dyn T>`. That implements both `T` and
`std::clone::Clone` (and other traits) which makes calls to `.clone()`
ambiguous. Using `*stub` turns it into a call via `T` which is under
our control and (hopefully) leads to less ambiguity.
Fixes #770

feat(generator/rust): disambiguate calls via Arc

---

generator/internal/api/model.go
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/language/rusttemplate.go
generator/internal/language/templates/rust/crate/src/transport.rs.mustache
generator/testdata/rust/openapi/golden/src/transport.rs
generator/testdata/rust/protobuf/golden/iam/v1/src/transport.rs
generator/testdata/rust/protobuf/golden/location/src/transport.rs
generator/testdata/rust/protobuf/golden/secretmanager/src/transport.rs
src/generated/cloud/secretmanager/v1/src/transport.rs
src/generated/cloud/workflows/v1/src/transport.rs
src/generated/spanner/admin/database/v1/src/transport.rs
src/generated/spanner/admin/instance/v1/src/transport.rs

I need to support RPCs where the path is fixed (no parameters). It was easier
to fix the management of optional fields and enums at the same time.
Fixes #764 and helps with #655 and #482

feat(generator): improve http path management

---

.sidekick.toml
.typos.toml
src/generated/spanner/admin/database/v1/src/model.rs

Incidentally this removes the need to override some typos in `.typos.toml`

chore: update googleapis circa 2025-01-21

---

src/auth/src/credentials/service_account_credential.rs
src/auth/src/credentials/util/jws.rs

Fixes #733 
Make sure the token's `expires_at` time matches the `exp` field in the claim.
We drop the `JwsClaimsBuilder` and do any defaulting in `service_account_credential.rs`. Note that the `exp` and `iat` fields are required, so they are probably better represented as `OffsetDateTime` than `Option<OffsetDateTime>`.

fix(auth): sync claim/token times in SA creds

---

.sidekick.toml
Cargo.lock
src/auth/Cargo.toml
src/gax/Cargo.toml
src/gax/echo-server/Cargo.toml
src/generated/cloud/kms/v1/Cargo.toml
src/generated/cloud/location/Cargo.toml
src/generated/cloud/run/v2/Cargo.toml
src/generated/cloud/secretmanager/v1/Cargo.toml
src/generated/cloud/sql/v1/Cargo.toml
src/generated/cloud/translate/v3/Cargo.toml
src/generated/cloud/webrisk/v1/Cargo.toml
src/generated/cloud/workflows/v1/Cargo.toml
src/generated/devtools/cloudbuild/v2/Cargo.toml
src/generated/devtools/cloudtrace/v2/Cargo.toml
src/generated/iam/v1/Cargo.toml
src/generated/longrunning/Cargo.toml
src/generated/openapi-validation/Cargo.toml
src/generated/spanner/admin/database/v1/Cargo.toml
src/generated/spanner/admin/instance/v1/Cargo.toml
src/integration-tests/Cargo.toml
src/lro/Cargo.toml
src/wkt/Cargo.toml

Change the `Cargo.toml` files to just requires version `1`. We are happy
to get updates, and I do not think we depend on specific features or
bugfixes beyond 1.0.0. In any case, a `cargo update` updates the lock
file to get the latest version.
I am hoping this will make the dependabot updates less toily.

chore: unpin and update `serde_json`

---

.gcb/builds/backend.tf

Someone is copying the terraform configuration, but with a different project. They noticed the project name could be substituted here.
https://github.com/googleapis/google-cloud-rust/blob/b412e6cb9134fe3e7caeb989aec77a45a840ea0b/.gcb/builds/variables.tf#L15-L17

cleanup(ci): use tf variable where possible

---

src/auth/.gcb/integration.yaml

Part of the work for #806
Introduce a placeholder config for running auth integration tests on GCB.
Keep it separate than the top level `.gcb/`, because these things have different owners/maintainers and access different projects with different permissions.
Note that `rust-auth-testing` also has a SA named `integration-test-runner`.

ci(auth): placeholder GCB integration test config

---

.gcb/builds/backend.tf

Reverts googleapis/google-cloud-rust#805
https://developer.hashicorp.com/terraform/language/backend says
```
A backend block cannot refer to named values (like input variables, locals, or data source attributes).
```
It was not possible to use a variable here, I now realize. I shall claim the first recorded :monkey: of the Rust SDK.

Revert "cleanup(ci): use tf variable where possible"

---

src/auth/.gcb/bootstrap/.terraform.lock.hcl
src/auth/.gcb/bootstrap/README.md
src/auth/.gcb/bootstrap/main.tf
src/auth/.gcb/bootstrap/variables.tf

Introduce a (pre-existing) GCS bucket to hold the terraform state (for when we actually start introducing testing resources). And commit the terraform state for this bootstrap to version control.
This is the same design as is used in the top level `.gcb/` directory.
Also, we might just see a `gcb-pr-auth-integration` build running due to a local terraform plan I have not committed yet. :scream:

ci(auth): bootstrap terraform resources

---

generator/internal/language/gotemplate.go
generator/internal/language/rusttemplate.go
generator/internal/language/templates/go/client.go.mustache
generator/internal/language/templates/go/message.mustache

Use annotations instead of duplicating the api.* data structures. This
brings the golang Codec to parity with the Rust Codec.
Part of the work for #653

cleanup(generator): use annotations for fields

---

generator/internal/api/model.go
generator/internal/api/recursive.go
generator/internal/api/recursive_test.go
generator/internal/api/test.go
generator/internal/language/codec_test.go
generator/internal/language/golang_test.go
generator/internal/language/gotemplate_test.go
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/language/rusttemplate_test.go
generator/internal/sidekick/refresh.go
src/generated/api/src/model.rs
src/generated/cloud/translate/v3/src/builders.rs
src/generated/cloud/translate/v3/src/model.rs
src/generated/devtools/cloudtrace/v2/src/model.rs

Message fields may refer to the same message, directly or indirectly.
With this change the fields gain a `Recursive` attribute, set to `true`
if the field directly (or indirectly) references the containing message.
The Rust Codec uses this attribute to emit `Option<Box<T>>` instead of
`Option<T>` for such fields.
Fixes #586

feat(generator): support self-referential fields

---

generator/internal/parser/mixin.go
generator/internal/parser/protobuf.go

Some services need the `longrunning` mixin, but their service config YAML file
does not provide it. Automatically add it when needed.
Fixes #781

feat(generator): automatic `longrunning` mixin

---

generator/internal/language/rust.go
generator/internal/language/rust_test.go

For services that are in ALLCAPS we need to do just capitalize the
first letter.
Fixes #824

feat(generator/rust): better service name mapping

---

src/auth/.gcb/builds/.terraform.lock.hcl
src/auth/.gcb/builds/backend.tf
src/auth/.gcb/builds/grants/main.tf
src/auth/.gcb/builds/main.tf
src/auth/.gcb/builds/resources/main.tf
src/auth/.gcb/builds/services/main.tf
src/auth/.gcb/builds/triggers/main.tf
src/auth/.gcb/builds/variables.tf

Manage the auth GCB configuration (test runner SA, triggers, GH link) via terraform.
This is very similar to `.gcb/builds`, but with some name changes.
This configuration is live.

ci(auth): terraform for GCB

---

.sidekick.toml

fix: configure sidekick to always use `wkt`

---

generator/internal/parser/mixin.go
generator/internal/parser/mixin_test.go

Fixes #781 (yes, second time)
If you are wondering how this can possible work: for services with `/v1` in the path, the default rules inherited from the mixin work just fine.  
I wonder if we should mixin *all* the methods.  Thoughts?

feat(generator/rust): implicit LROs mixin

---

generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/testdata/rust/protobuf/golden/secretmanager/src/model.rs
src/generated/cloud/secretmanager/v1/src/model.rs
src/generated/container/v1/src/model.rs
src/wkt/src/generated/mod.rs

Fixed handling of implied (`[Thing][]`) and relative (`[blah][Thing]`)
cross-reference links. So far we only supported the fully-qualified
kind (as in `[blah][google.test.v1.Thing]`).
Fixes #850

fix(generator/rust): MOAR cross-reference links

---

.github/workflows/generator.yaml
.github/workflows/lint.yaml
.github/workflows/sdk.yaml

Apparently we need go > 1.23.4. ([build fail](https://github.com/googleapis/google-cloud-rust/actions/runs/13004718871/job/36269942403?pr=865))
I do not know the process to update go. Feel free to close this PR and do it better. Or wait until asking for `1.23` gives us `1.23.5`. (Also, I see there are other places where we pin go to `1.23.2`, we just don't `go test` with this version it looks like).
This PR unblocks me though ([build win](https://github.com/dbolduc/google-cloud-rust/actions/runs/13004855835))

chore: update go version past vuln

---

generator/internal/language/templates/rust/common/message.mustache

Fixes #868
Regenerating cloud/aiplatform/v1 with this template addressed the error:
```
error[E0412]: cannot find type `RRF` in this scope
--> src/generated/cloud/aiplatform/v1/src/model.rs:35355:40
|
35340 |         pub struct Rrf {
|         -------------- similarly named struct `Rrf` defined here
...
35355 |         impl wkt::message::Message for RRF {
|                                        ^^^ help: a struct with a similar name exists: `Rrf`
```
After the change( note that the other errors are being tracked in https://github.com/googleapis/google-cloud-rust/issues/845) :

fix: update message template to have consistent naming

---

generator/internal/language/codec.go
generator/internal/language/rust.go
generator/internal/language/rust_test.go
generator/internal/language/templates/rust/common/oneof.mustache
generator/testdata/rust/protobuf/golden/secretmanager/src/model.rs
src/generated/api/src/model.rs
src/generated/bigtable/admin/v2/src/model.rs
src/generated/cloud/functions/v2/src/model.rs
src/generated/cloud/kms/v1/src/model.rs
src/generated/cloud/run/v2/src/model.rs
src/generated/cloud/scheduler/v1/src/model.rs
src/generated/cloud/secretmanager/v1/src/model.rs
src/generated/cloud/sql/v1/src/model.rs
src/generated/cloud/translate/v3/src/model.rs
src/generated/container/v1/src/model.rs
src/generated/devtools/cloudbuild/v2/src/model.rs
src/generated/devtools/cloudtrace/v2/src/model.rs
src/generated/iam/admin/v1/src/model.rs
src/generated/iam/v2/src/model.rs
src/generated/longrunning/src/model.rs
src/generated/spanner/admin/database/v1/src/model.rs
src/generated/type/src/model.rs
src/integration-tests/src/secret_manager/protobuf.rs
src/integration-tests/src/workflows.rs
src/lro/src/details.rs
src/lro/src/lib.rs
src/lro/tests/fake_responses/mod.rs

Messages is `oneof` fields may trigger clippy errors about branches with
radically different sizes. That seems like a good warning to heed.
Fixes #837

feat(generator/rust): box messages in `oneof`

---

src/auth/src/credentials/service_account_credential.rs

Part of the work for #679 
censor private fields, like we do for user credentials.

cleanup(auth): censor SA private fields

---

src/auth/src/credentials/service_account_credential.rs
src/auth/src/credentials/util/jws.rs

Part of the work for #679 
`scope` needs to be serialized as a space-separated string. Found this while running integration tests locally.
I considered implementing a `serde(serialize_with = ...)` but then figured a similar, simpler function could go into `service_account_credential.rs` when we are ready to handle custom scopes.

fix(auth): scope serialization in jws claim

---

src/generated/showcase/.not-working-sidekick.toml

Remove options we do not need and update the (expected) generation year.

cleanup(showcase): minor sidekick config fixes

---

generator/internal/api/model.go
generator/internal/api/xref.go
generator/internal/api/xref_test.go
generator/internal/language/rusttemplate.go
generator/internal/language/rusttemplate_test.go
generator/internal/language/templates/rust/common/message.mustache
generator/internal/sidekick/refresh.go
generator/testdata/rust/protobuf/golden/secretmanager/src/model.rs
src/generated/api/src/model.rs
src/generated/bigtable/admin/v2/src/model.rs
src/generated/cloud/functions/v2/src/model.rs
src/generated/cloud/kms/v1/src/model.rs
src/generated/cloud/language/v2/src/model.rs
src/generated/cloud/run/v2/src/model.rs
src/generated/cloud/scheduler/v1/src/model.rs
src/generated/cloud/secretmanager/v1/src/model.rs
src/generated/cloud/sql/v1/src/model.rs
src/generated/cloud/translate/v3/src/model.rs
src/generated/cloud/webrisk/v1/src/model.rs
src/generated/cloud/workflows/v1/src/model.rs
src/generated/container/v1/src/model.rs
src/generated/devtools/cloudbuild/v2/src/model.rs
src/generated/devtools/cloudtrace/v2/src/model.rs
src/generated/iam/admin/v1/src/model.rs
src/generated/iam/v2/src/model.rs
src/generated/longrunning/src/model.rs
src/generated/monitoring/dashboard/v1/src/model.rs
src/generated/spanner/admin/database/v1/src/model.rs
src/generated/spanner/admin/instance/v1/src/model.rs
src/generated/type/src/model.rs

Generate methods to set and get each oneof branch. Including the
`IntoIterator<>` adapters for repeated fields.
Part of the work for #845

feat(generator/rust): oneof setters and getters

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/credentials/service_account_credential.rs
src/auth/src/credentials/util/jws.rs

Part of the work for #679 
We were missing the ...
- `kid` claim, which is equal to the `private_key_id`,  if there is one.
- `sub` claim which is the subject aka principal aka SA email.
Found by local integration testing.
Verify the values  of the claims we set in a unit test.

fix(auth): SA cred missing claims

---

generator/README.md

- update command-line  for the openapi example in the readme
W/o this change I saw the error below; but perhaps this is a local config error on my part.
```
go: github.com/googleapis/google-cloud-rust/generator/sidekick@latest:
module github.com/googleapis/google-cloud-rust/generator@latest found (v0.0.0-20250129204245-87fd1ddc5475),
but does not contain package github.com/googleapis/google-cloud-rust/generator/sidekick
```

docs(generator): update README.md

---

src/auth/src/credentials/service_account_credential.rs

I did not mean to commit this print statement. Note that we would log the `token.token` later if it is in an unexpected format.

cleanup(auth): remove accidental debug statement

---

src/auth/src/credentials/service_account_credential.rs

Part of the work for #679 
If an application sets a default crypto provider, use that. Otherwise use a default one.
This reduces the need for boilerplate code in applications which should lead to a better customer experience.
I am open to suggestions on how to make the `map_or_else` better. One is a `CryptoProvider`, the other is an `&Arc<CryptoProvider>`. I feel like I want to say the following, but couldn't figure it out.
```rs
let crypto_provider = ...;
let key_provider = crypto_provider.key_provider;
```
"Why are there no unit tests that check that we use a custom crypto provider if the application sets one?", you ask.
`CryptoProvider::install_default()` can only be called once per process. If you try to call it again, it fails. Previously, we were just eating up this error.
`cargo …

impl(auth): sa creds default crypto provider

---

generator/internal/api/model.go
generator/internal/api/xref.go
generator/internal/api/xref_test.go
generator/internal/golang/gotemplate.go
generator/internal/golang/templates/client.go.mustache
generator/internal/rust/rusttemplate.go
generator/internal/rust/templates/crate/src/builders.rs.mustache
generator/internal/rust/templates/crate/src/client.rs.mustache
generator/internal/rust/templates/crate/src/stubs.rs.mustache
generator/internal/rust/templates/crate/src/stubs/dynamic.rs.mustache
generator/internal/rust/templates/crate/src/tracing.rs.mustache
generator/internal/rust/templates/crate/src/transport.rs.mustache
generator/internal/sidekick/refresh.go

Continue the work to refactor the `*template.go` files, using
annotations on the original model to store language specific data.
Part of the work for #653

cleanup(generator): use annotations for methods

---

Cargo.lock
Cargo.toml
src/auth/.gcb/integration.yaml
src/auth/integration-tests/Cargo.toml
src/auth/integration-tests/tests/driver.rs

Add a package for `auth-integration-tests`. Right now it is one test, guarded by the `run-integration-tests` feature.
Update auth's `cloudbuild.yaml` to run the tests in this new package.
Add a test that verifies SA credentials. Hopefully the code makes it clear what we are doing. I will wait to refactor until we have another test.
I will take a TODO to abstract the project ID, and add a README for running the integration tests locally.

ci(auth): add SA integration test

---

src/auth/integration-tests/tests/driver.rs

Ability to run auth integration test in other projects

ci(auth): run integration test in any project

---

src/auth/.gcb/builds/grants/main.tf
src/auth/.gcb/builds/main.tf
src/auth/.gcb/builds/service_account_test/main.tf
src/auth/.gcb/builds/services/main.tf
src/auth/.gcb/builds/triggers/main.tf

Add the terraform configuration needed to set up the service account integration test.
I think it is cleaner to keep the setup for each test in its own module. (vs. splitting it across `resources/` and `grants/`).
I am considering flattening the structure of `resources/` and `grants/`.

ci(auth): terraform for SA integration tests

---

generator/internal/golang/golang.go
generator/internal/golang/golang_test.go
generator/internal/golang/gotemplate.go
generator/internal/golang/templates/client.go.mustache
generator/internal/rust/rust_test.go

I broke the golang generator in #895: it found no templates and
therefore generated no code and nothing changed in the golden files.
Then I introduced regressions in #905 and #912. This restores the
testing and fixes the golden files.

fix(generator/golang): fix testing and regressions

---

.github/dependabot.yml

- have dependabot send one PR for all github actions changes (instead of one PR per updated action)
We use this config for the dart-lang repos in order to reduce the number of dependabot PRs.

chore(deps): update dependabot.yml

---

.github/workflows/sdk.yaml
src/gax/src/polling_policy.rs

The normal `cargo test` enables all the features needed by other crates,
including generated libraries. Running `cargo test -p gcp-sdk-gax`
verifies the library builds on its own.

ci: test gax with features disabled

---

generator/internal/parser/protobuf_test.go
generator/internal/parser/testdata/json_name.proto
generator/internal/rust/rusttemplate_test.go

If the `json_name` annotation is present, then we capture it in the
AST and the Rust generator outputs the right attributes for JSON
serialization *and* the right query parameter code.
Fixes #97

test(generator): `json_name` annotations work

---

generator/internal/api/model.go
generator/internal/parser/auto_populated.go
generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_annotations.go
generator/internal/parser/protobuf_test.go
generator/internal/parser/testdata/auto_populated.proto
generator/internal/parser/testdata/auto_populated_openapi.json
generator/testdata/googleapis/google/api/field_info.proto

Add an annotation to the fields so we can implement AIP-4235: automatically
populate fields in the request message.
Part of the work for #439 - we do not use the annotation in any mustache template

feat(generator): model auto-populated fields

---

src/auth/.gcb/builds/triggers/main.tf
src/auth/.gcb/integration.yaml

Fixes #806 
Add a build cache for the rust auth integration tests.
A bit of a YOLO, but I trust in my abilities to `Ctrl` + `C`, `Ctrl` + `V`. The first run of the `auth-integration` build should populate the cache. I will probably restart it to see if the build time drops before requesting review.
**Update**: it seems to work.

ci(auth): add build cache

---

.codecov.yml
.gcb/integration.yaml
.github/workflows/sdk.yaml
Cargo.lock
Cargo.toml
doc/contributor/howto-guide-set-up-development-environment.md
guide/.gitignore
guide/book.toml
guide/samples/Cargo.toml
guide/samples/src/lib.rs
guide/samples/tests/initialize_client.rs
guide/samples/tests/list_resources.rs
guide/src/SUMMARY.md
guide/src/initialize_a_client.md
guide/src/introduction.md

Create an initial `mdbook` with a simple tutorial showing how to initialize a
client.  Include the guide generation and testing of the code snippets *and*
the included samples into the CI build.
Part of the work for #574

docs: bootstrap user guide

---

generator/internal/language/generate.go

- have mustache fail if there are unresolved template variables
I found a flag on the cbroglie/mustache library to fast fail if there are variable references in the templates that don't resolve; likely useful to enable?

feat(generator): have mustache fail if there are unresolved template variables

---

.github/workflows/generator.yaml
.github/workflows/lint.yaml
.github/workflows/sdk.yaml

- have github workflows run fewer times (just on PRs, or, pushes to main)
I noticed that most checks where running twice per PR; this should just run a workflow once per PR (or PR change), and once when that PR lands in main.

chore(ci): have github workflows run fewer times

---

generator/internal/golang/golang.go
generator/internal/rust/rusttemplate.go

Another fix for packages without a service config file. The package
may only contain enums, so we cannot determine the source package name
from the services or the messages.
Motivated by #1014

fix(generator/rust): packages with only enums

---

generator/internal/api/scopes.go
generator/internal/rust/rust.go
generator/internal/rust/rust_test.go
generator/internal/rust/rusttemplate.go
src/wkt/protos/google/protobuf/api.proto
src/wkt/src/generated/mod.rs

This deals with cross-reference links that reference a local (to a
message) field. For example, when a comment includes  `[root][]` to
reference a field named `root`.
This allows me to remove a local patch to `api.proto`, and is required
to (soon) use the protos directly from GitHub.
Motivated by #766

feat(generator/rust): xref links take 2 or 7

---

generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go
generator/internal/sidekick/sidekick_test.go
generator/testdata/rust/protobuf/golden/wkt/generated/wkt/.sidekick.toml

Sometimes we want to generate client libraries or modules using only a subset
of the protos found in a given directory. This introduces configuration options
to only include explicitly listed files, and to exclude some files.
Motivated by #766

feat(generator): support lists for proto files

---

generator/internal/parser/protobuf.go
generator/internal/parser/service_config.go
generator/internal/parser/source_roots.go
generator/internal/sidekick/downloads_cache.go
generator/internal/sidekick/refreshall.go

We will need to add more `-root` options for the protobuf well-known
protos. And someday we may use `-root` for the discovery doc or OpenAPI
sources.
Part of the work for #766

feat(generator): support more `-root` options

---

generator/internal/golang/templates/message.mustache

- update a reference from `NestedMessages` to `Messages`
I don't see `NestedMessages` populated in the model but do see `Messages` (as a field on Message). I'm guessing that the mustache library doesn't complain about undefined lists - treating them as empty lists? It would be great if we could get that library to fast-fail for more cases.

fix(generator/go): update a reference from NestedMessages => Messages

---

generator/internal/api/model.go
generator/internal/dart/dart.go
generator/internal/dart/dart_test.go
generator/internal/dart/darttemplate.go
generator/internal/dart/templates/enum.mustache
generator/internal/dart/templates/message.mustache
generator/testdata/dart/protobuf/golden/secretmanager/secretmanager.dart

Update the dart generator to emit enums:
- update the templates to emit enums
- update the templates to traverse into nested messages and enums
- general work towards https://github.com/googleapis/google-cloud-rust/issues/1034
This uses Dart classes to represent enums instead of actual language `enum`s. I assume this will work better with unknown values coming over the wire. And I'm assuming enum values over the wire will be represented by their int values (and not something like their SCREAMING_CAPS string name).
I'm using `'$'` to concatenate nested messages and enums. `'_'` and `''` are also reasonable; nothing's particularly idiomatic. Perhaps shorter names could be used if we determine there are no namespace conflicts in a library?

feat(generator/dart): emit enums

---

generator/protojson/README.md
generator/protojson/any_in_any_test.go
src/wkt/src/any.rs
src/wkt/src/duration.rs
src/wkt/src/message.rs
src/wkt/src/timestamp.rs
src/wkt/tests/any.rs

Apparently some of our APIs like to store an `Any` object inside another `Any` object.
Fixes #1090

feat(wkt): support `Any` inside an `Any`

---

src/auth/src/credentials/mds_credential.rs
src/auth/src/credentials/service_account_credential.rs
src/auth/src/credentials/user_credential.rs
src/auth/src/token.rs

Fixes #387
`time` crate is currently unstable. Use a `std::time::Instant` instead to represent the expiration timepoint.
Pro:
- `std` is stable.
- (not customer facing) `std::time::Instant` can be manipulated in a `tokio::test`, whereas `OffsetDateTime` cannot.
Con:
- `std::time::Instant` only means something within a process. It takes effort to copy it across processes.
I left a recommendation for customers to not interact with the expiration at all, and instead let the auth library do it. If they absolutely must, I left a hint for how to preserve the expiration across processes.

fix(auth)!: stable token expiration type

---

generator/internal/rust/rust.go
generator/internal/rust/rust_test.go
generator/internal/rust/rusttemplate.go

Output a warning as a reminder to fix the problem upstream, and just
generate no output (since the list item is empty) instead of crashing.
Fixes #1174

fix(generator/rust): handle empty list items

---

guide/src/configuring_polling_policies.md
guide/src/initialize_a_client.md
guide/src/introduction.md
guide/src/setting_up_rust_on_cloud_shell.md
guide/src/setting_up_your_development_environment.md

The titles are not supposed to capitalize each word, except product
names (and other proper names, presumably).
Also add some missing boilerplate.

docs: use Google guidelines on titles style

---

generator/internal/language/generate.go

- switch back to allowing missing variables for mustache
Currently, when this fails the error does not contain any positional information (which template? which line?). This is much harder to debug than just substituting an empty string and letting downstream systems fail (static analysis / compilation).

fix(mustache): allow missing variables for mustache

---

generator/internal/sidekick/refreshall.go

The time when it was useful to print each directory that is refreshed is
long past.

feat(generator): a quieter `refreshall`

---

generator/internal/sidekick/refreshall.go

fix(generator): skip `generator/` in refreshall

---

generator/internal/dart/dart_test.go
generator/internal/dart/darttemplate_test.go
generator/internal/golang/golang_test.go
generator/internal/rust/rust_test.go

We used to prefix the codec tests with the language because they all
lived in the same package. Now that we have a package per codec this is
not needed and we can use shorter, and I believe more idiomatic, test
names.

cleanup(generator): shorter test names

---

generator/internal/sidekick/cmdline_test.go
generator/internal/sidekick/command.go
generator/internal/sidekick/sidekick.go

The intention is to use the language configured in the top-level
`.sidekick.toml` file, with an opportunity to override via the
command-line or with a local `.sidekick.toml` file.
The actual implementation always overrode the language to `rust` because
it provided a default value for the command-line argument.
Motivated by #1324

fix(generator): default to root config language

---

src/auth/src/credentials.rs
src/auth/src/credentials/mds_credential.rs
src/auth/src/credentials/service_account_credential.rs
src/auth/src/credentials/service_account_credential/jws.rs
src/auth/src/credentials/user_credential.rs
src/auth/src/errors.rs

Part of the work for #1210, second try at #1213
The point is that we are making `CredentialError` clone-able.
This is a breaking change because `CredentialError::new(...)` accepts different types.
Add new `*_from_str()` methods for constructing a `CredentialError`. While these could be helpful to customers mocking credentials, leave them crate-private for now.
Arguably I should have used `anyhow::Error` instead of writing `StringError`.

feat(auth)!: clone-able `CredentialError`

---

generator/internal/sidekick/refresh.go
generator/internal/sidekick/sidekick_test.go
generator/testdata/rust/protobuf/golden/override/type/.sidekick.toml
generator/testdata/rust/protobuf/golden/override/type/README.md

The immediate need is to override the `google-cloud-longrunning` description (nit: there is none, so maybe s/overridethe /provide a/).
We may use this for any other crate / library that lacks a description.

feat(generator): support description overrides

---

src/generated/longrunning/.sidekick.toml
src/generated/longrunning/README.md

Link the previous version of the crate, it is polite and may avoid
confusion for some folks. Since I was customizing the description, might
as well add something about what the crate is about.

docs(longrunning): link previous crate version

---

generator/all_test.go

`go test ./...` was broken for me without this update. :shrug:
Ah, maybe because I am using go 1.24 on my laptop and 0.6.0 adds support for that version.

chore(generator): update `staticcheck`

---

generator/internal/sidekick/refresh.go

Using `sidekick refresh` for a single directory required 
- Overriding the googleapis root option
- Having the googleapis root already extracted
Now you can say:
```shell
sidekick refresh -output src/generated/iam/v2
```
and it will use the right googleapis version. `refreshall` also works, but it is slower now that we have so many libraries.

fix(generator): refresh with github roots

---

generator/dart/packages/generated/google_cloud_protobuf/.sidekick.toml
generator/dart/packages/generated/google_cloud_type/.sidekick.toml
generator/internal/dart/darttemplate.go
generator/internal/dart/templates/pubspec.yaml.mustache
generator/testdata/dart/protobuf/golden/secretmanager/analysis_options.yaml
generator/testdata/dart/protobuf/golden/secretmanager/pubspec.yaml

- support the 'not-for-publication' config setting; translate this to the Dart `publish_to: none` convention
- remove some unnecessary 'package-name-override' settings; they are the same as the calculated, default name
- ignore analysis for `generator/testdata/dart/protobuf/golden/secretmanager`; we'll get correct analysis (provisioned packages, ...) from `generator/dart/packages/`

feat(generator/dart): support the 'not-for-publication' config setting

---

src/auth/src/token.rs

If we have tokens with unknown expiration, we should use an `enum` that distinguishes between unknown, and no expiration. Until then, we will use `None` to mean "no expiration".

doc(auth): clarify `None` expiration

---

generator/dart/.sidekick.toml
generator/dart/packages/generated/google_cloud_protobuf/lib/protobuf.dart
generator/dart/packages/generated/google_cloud_rpc/lib/rpc.dart
generator/dart/packages/generated/google_cloud_rpc/pubspec.yaml
generator/internal/dart/dart.go
generator/internal/dart/dart_test.go
generator/internal/dart/darttemplate.go
generator/internal/dart/darttemplate_test.go
generator/internal/dart/templates/lib/main.dart.mustache
generator/internal/rust/rust.go
generator/internal/sidekick/sidekick_dart_test.go
generator/testdata/dart/protobuf/golden/secretmanager/.sidekick.toml
generator/testdata/dart/protobuf/golden/secretmanager/lib/secretmanager.dart
generator/testdata/dart/protobuf/golden/secretmanager/pubspec.yaml

- create a mapping from several well-known type proto packages to Dart package and library imports
- use that info when annotating the model objects to update the dart imports info
-  prep for generating the `google.protobuf.Duration` type by renaming references to it to `PbDuration` (`Duration` is a core Dart type)
Note that this PR collects import information as part of generally annotating the model tree. In order to not over-collect import info (avoid calculating import info based on messages that won't be emitted in the current library) we now only annotate model objects that will be emitted in the current library. Having annotated and non-annotated messages in the api model works for the Dart generator currently but could cause issues down the road. I'm open to instead annotating …

feat(generator/dart): calculate dependencies on wkt packages

---

Cargo.lock
src/auth/integration-tests/Cargo.toml
src/auth/integration-tests/tests/driver.rs

Fixes #1371 
Add an integration test for API  Keys.
The test uses a long lived API key, stored in secret manager. These keys can take on the order of minutes to be ready after being created by the `apikeys` service. So let's avoid that latency in our tests.
https://github.com/googleapis/google-cloud-cpp/blob/1f054ae244e473fe3911419ddec3358e4dbeeccf/examples/api_key.cc#L141-L160

test(auth): api key integration  test

---

generator/internal/rust/rust.go
generator/internal/rust/rust_test.go
generator/internal/rust/rusttemplate.go
generator/internal/sidekick/sidekick_test.go
generator/testdata/rust/protobuf/golden/module/rpc/.sidekick.toml
generator/testdata/rust/protobuf/golden/module/rpc/mod.rs

To be pedantic, the option was only used in tests. It became obsolete
when we introduced message names for `Any`.

cleanup(generator/rust): remove unused option

---

generator/internal/rust/templates/common/enum.mustache

Initialize enums with no obvious default to the empty string. None of
the Google Cloud enums need this, but we will use it to generate
`google.protobuf.ProtoDescriptor`.
Part of the work for #37

feat(generator/rust): enums with bad defaults

---

generator/internal/parser/protobuf.go

The generator was emitting warnings about comments for extension ranges,
extensions, and options. None of the Google Cloud protos have such
comments. `google.protobuf.DescriptorProto` does have them, but the
elements they reference do not result in any generated code, so I think
they are safe to ignore.
Motivated by #37

cleanup(generator/rust): ignore unused comments

---

src/wkt/src/rstruct.rs
src/wkt/tests/null_value.rs

The `google.protobuf.NullValue` well-known type is represented as a
unit-like struct. It only has one value, and it is a distinct type.
It can be stored inside a `wkt::Any` and freely converts to and from
`serde_json::Value::NullValue`. Recall that `wkt::Value` is a type alias
for `serde_json::Value`, meaning it works well with the value type.
The type also works as a member of oneof fields, their only use (AFAICT)
in Google Cloud services.
Fixes #37

feat(wkt): implement  `NullValue`

---

generator/dart/packages/generated/google_cloud_protobuf/.sidekick.toml
generator/dart/packages/generated/google_cloud_protobuf/lib/protobuf.dart
generator/dart/packages/generated/google_cloud_protobuf/lib/src/protobuf.p.dart
generator/dart/packages/generated/google_cloud_protobuf/test/types_test.dart
generator/dart/packages/generated/google_cloud_rpc/lib/rpc.dart
generator/internal/dart/dart.go
generator/internal/dart/dart_test.go
generator/internal/dart/darttemplate.go
generator/internal/dart/templates/lib/message.mustache
generator/testdata/dart/protobuf/golden/secretmanager/lib/secretmanager.dart

- generate the `Duration` WKT
- contribute hand-written json encode and decode methods
- remove the rename special-casing for `Duration` (we'll revisit this w/ some future mechanism)

feat(generator/dart): generate the Duration WKT

---

generator/dart/packages/generated/google_cloud_protobuf/lib/protobuf.dart
generator/dart/packages/generated/google_cloud_protobuf/test/types_test.dart
generator/dart/packages/generated/google_cloud_rpc/lib/rpc.dart
generator/dart/packages/generated/google_cloud_type/lib/type.dart
generator/internal/dart/dart.go
generator/internal/dart/dart_test.go
generator/internal/dart/templates/lib/enum.mustache
generator/internal/dart/templates/lib/field.mustache
generator/internal/dart/templates/lib/main.dart.mustache
generator/internal/dart/templates/lib/message.mustache
generator/internal/dart/templates/lib/method.mustache
generator/internal/dart/templates/lib/service.mustache
generator/testdata/dart/protobuf/golden/secretmanager/lib/secretmanager.dart

Whitespace updates to the emitted dartdocs:
- don't generate lines with trailing whitespace
- don't generate trailing blank dartdoc lines
- tests for the existing behavior
We will eventually want to move to running `dart format` over the source as part of the generation process.

feat(generator/dart): whitespace updates to the emitted dartdocs

---

.github/workflows/generator_dart.yaml

Analyze and test the generated packages on CI:
- analyze and test `google_cloud_protobuf`
- analyze `google_cloud_type` (it doesn't have unit tests)
- don't do anything for `google_cloud_rpc` (we need `Any` to analyze it cleanly)

ops(generator/dart): analyze and test the generated packages on CI

---

.typos.toml
generator/internal/parser/protobuf.go

It seems that something changed with `typos-cli` and now it flags a few more typos. It is not the version, that is pinned, maybe the source data for the dictionary?
Part of the work for #1405

chore: silence typos

---

Cargo.lock
guide/samples/Cargo.toml
src/auth/Cargo.toml
src/auth/integration-tests/Cargo.toml
src/gax/Cargo.toml
src/integration-tests/Cargo.toml
src/lro/Cargo.toml
src/wkt/Cargo.toml
tools/check-copyright/Cargo.toml

Unless we are explicitly using a feature only available in 1.x (or 0.y.z) we should not mention the minor version (nor patch) version in our Cargo.toml files.

chore: unpin minor and patch versions

---

src/auth/Cargo.toml
src/auth/src/credentials/service_account_credential.rs

Part of the work for #1077 
It avoids bringing in the entire aws_lc_rs crate when ring is used for the crypto provider.
Maybe aws_lc_rs needs to be disabled by default, but this why it won't be breaking change.

fix(auth): feature gate aws_lc_rs from rustls

---

generator/internal/config/source_roots.go
generator/internal/parser/protobuf.go
generator/internal/parser/service_config.go
generator/internal/sidekick/refreshall.go

Move this function to the `config`, I am planning to use it outside of
the `parser` package for the Rust+Prost codec.

refactor(generator): move `SourceRoots()`

---

src/wkt/src/any.rs

With this change applications can query the contents of the `Any`. This
is useful when there is a list of known types that may contained in an
`Any`.

feat(wkt): add `type_url()` to `Any`

---

Cargo.lock
src/wkt/Cargo.toml
src/wkt/src/lib.rs
src/wkt/src/prost.rs

We will need to convert to and from Prost's versions of the well-known
types. The same trait will be used to convert between our generated
types and the types that Prost generates.

feat(wkt): convert to Prost's version of the WKT

---

generator/internal/dart/dart.go
generator/internal/golang/golang.go
generator/internal/rust/rust.go
generator/internal/sidekick/refresh.go

Eventually we will need to use more of the configuration in the codecs.
For example, we need to know if the specification was in Protobuf form
to decide if enums are integers over the wire.
Part of the work for #1379

refactor(generator): codecs consume full config

---

generator/internal/api/model.go
generator/internal/parser/parser_test.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go
generator/internal/parser/testdata/enum_values.proto

Some enums have aliases for the same value. Sometimes we need the list
of unique values to generate switch statements and similar constructs.
Part of the work for #1379

feat(generator): separate unique enum values

---

ARCHITECTURE.md
README.md

This is where we will document the basic structure of the code, and the
internals of the main libraries.

docs: start architecture document

---

src/auth/integration-tests/Cargo.toml
src/auth/integration-tests/src/lib.rs
src/auth/integration-tests/tests/driver.rs

Split the code such that the bulk of the tests are always compiled, even
if they do not get to run. That makes it easier to detect build problems
before sending a PR for review.

refactor(auth): always compile integration tests

---

.github/workflows/generator_dart.yaml
generator/dart/.sidekick.toml
generator/dart/packages/generated/google_cloud_protobuf/lib/protobuf.dart
generator/dart/packages/generated/google_cloud_protobuf/pubspec.yaml
generator/dart/packages/generated/google_cloud_rpc/lib/rpc.dart
generator/dart/packages/generated/google_cloud_rpc/pubspec.yaml
generator/dart/packages/generated/google_cloud_type/lib/type.dart
generator/dart/packages/generated/google_cloud_type/pubspec.yaml
generator/dart/packages/google_cloud_common/README.md
generator/dart/packages/google_cloud_common/lib/common.dart
generator/dart/packages/google_cloud_common/pubspec.yaml
generator/internal/dart/darttemplate.go
generator/internal/dart/darttemplate_test.go
generator/internal/dart/templates/lib/enum.mustache
generator/internal/dart/templates/lib/message.mustache
generator/internal/dart/templates/lib/service.mustache
generator/testdata/dart/protobuf/golden/secretmanager/lib/secretmanager.dart
generator/testdata/dart/protobuf/golden/secretmanager/pubspec.yaml

Introduce a base google_cloud_common package:
- add a new `package:google_cloud_common` hand-written base package that all generated packages can refer to
- have all messages, services and enums inherit from base classes (`CloudMessage`, `CloudService`, and `CloudEnum`). `CloudService` will let us provide common behavior wrt RPC calls to services. CloudMessage and CloudEnum will provide some shorthand facilities for JSON encoding.
- extracted from https://github.com/googleapis/google-cloud-rust/pull/1454

feat(generator/dart): introduce a base google_cloud_common package

---

generator/internal/rust/rust.go
generator/internal/rust/rust_test.go
generator/internal/sidekick/sidekick_test.go
generator/testdata/rust/protobuf/golden/module/rpc/.sidekick.toml
generator/testdata/rust/protobuf/golden/module/type/.sidekick.toml
generator/testdata/rust/protobuf/golden/wkt/generated/wkt/.sidekick.toml
src/firestore/src/generated/model/.sidekick.toml
src/wkt/src/generated/.sidekick.toml

I am going to need a new template directory for Prost+Tonic libraries.
Instead of using a series of boolean options I opted for a single
option that overrides the template directory.

feat(generator/rust): option to override templates

---

generator/internal/rust/templates/mod-prost/enum.mustache
generator/internal/rust/templates/mod-prost/message.mustache
generator/internal/rust/templates/mod-prost/mod.rs.mustache
generator/internal/rust/templates/mod-prost/oneof.mustache

These will create a module-only library (or part thereof) with some
additional helpers to create `oneof` fields. We decided not to add these
helpers to all libraries because they slow down compilation too much. We
can always change this decision in the future.

feat(generator/rust): new `mod-prost` templates

---

generator/dart/packages/generated/google_cloud_protobuf/lib/protobuf.dart
generator/dart/packages/generated/google_cloud_rpc/lib/rpc.dart
generator/dart/packages/generated/google_cloud_type/lib/type.dart
generator/internal/dart/darttemplate.go
generator/internal/dart/darttemplate_test.go
generator/internal/dart/templates/lib/message.mustache
generator/internal/sample/api.go
generator/testdata/dart/protobuf/golden/secretmanager/lib/secretmanager.dart

- add toString() methods to messages
- extracted from https://github.com/googleapis/google-cloud-rust/pull/1454
Having reasonable toString() methods - mostly used for debugging for Dart - is more of a quality of life thing than super necessary; I found them useful when printing out the results from the end-to-end call.

feat(generator/dart): add toString() methods to messages

---

generator/internal/api/skip.go
generator/internal/api/skip_test.go
generator/internal/sidekick/refresh.go

Sometimes we need to skip some elements in the generated code. The
current motivation is to skip conversion functions to and from Prost
types.

feat(generator): options to skip some elements

---

generator/internal/dart/dart.go
generator/internal/dart/dart_test.go
generator/internal/dart/darttemplate.go
generator/internal/dart/darttemplate_test.go
generator/internal/dart/templates/lib/field.mustache
generator/internal/dart/templates/lib/message.mustache
generator/internal/dart/templates/lib/service.mustache
generator/internal/sample/api.go
generator/testdata/dart/protobuf/golden/secretmanager/lib/secretmanager.dart
generator/testdata/dart/protobuf/golden/secretmanager/pubspec.yaml

Calculate required fields:
- calculate which message fields are definitely required (fields that are path params are required as well as fields that are used as the body of calls)
- use the required info to inform nullability of generated message fields (see `golden/secretmanager/lib/secretmanager.dart`)
- some cleanup of the sample test data in `sample/api.go` (IDs and relationships)
- extracted from https://github.com/googleapis/google-cloud-rust/pull/1454

feat(generator/dart): calculate required fields

---

src/wkt/src/prost.rs
src/wkt/src/rstruct.rs

In some contexts it is useful if `NullValue` behaves more like an enum.
Protobuf defines it as an enum, and the generator produces code assuming
it has the interface defined for enums.
Part of the work for #1384

feat(wkt): `NullValue` behaves like enums

---

generator/internal/rust/annotate_test.go

We had no tests for the service and/or method annotations. This is a
start.

test(generator/rust): improve annotate* coverage

---

src/gax/Cargo.toml

Part of the work for #1468 
Paginator will (hopefully soon) pick up a `fn to_stream()` which is gated by the `unstable-stream` feature. We want this to appear in our docs.
While client crates currently have an `unstable-stream` feature which is gating their `stream()` methods, and preventing the methods from appearing in our docs, we plan to change the method to `paginator()` and make it always available. (Hence there are no changes to client crates).
See: https://docs.rs/about/metadata
---
Aside: Remind me where I can look at the generated documentation to make sure this change actually works...

docs(gax): include streaming APIs

---

src/wkt/Cargo.toml

Fixes #1468 
Add convenient conversion functions for `wkt` <-> {`time`, `duration`} to the docs.
---
https://docs.rs/rustls/latest/rustls/crypto/aws_lc_rs/fn.default_provider.html
I am hoping `cargo doc` is the thing that adds this tag, and we do not need to document the methods individually. I did not find that "Available on crate feature `aws_lc_rs` only" text in the source code anywhere.

docs(wkt): time and chrono conversions

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/credentials/service_account_credential.rs

Related to #1077 
The `ring` crate is less offensive than the `aws-lc-rs` crate. So we will depend on it by default.
We will not offer a way to exclude the `ring` crate in the dependency tree. That requires propagating a default feature to all N of our client crates. It is not worth it.

impl(auth)!: ring for default crypto provider

---

src/auth/tests/crypto_provider.rs

Fixes #1077 
Add a test that installs a custom crypto provider.
This custom provider returns some error. We know our library is using the custom provider if that error is returned to us.
Bring attention to the fact that `CryptoProvider::install_default(...)` can only be called once per process.

test(auth): custom crypto provider

---

Cargo.lock
src/lro/Cargo.toml
src/lro/tests/fake_library/builders.rs
src/lro/tests/fake_library/client.rs

Use the re-exports from `google-cloud-http-client`, in preparation to
moving the implementation from gax to that library.
Part of the work for #1490

refactor(lro): use `google-cloud-http-client`

---

src/http-client/src/lib.rs

The path parameter and query parameter helpers are only used for
HTTP+JSON based clients, so they belong in `google-cloud-http-client`.
Part of the work for #1490

feat(http-client): re-export parameter helpers

---

src/lro/Cargo.toml

I missed this in #1468 
FWIW, I do not think there is a good way to test this locally. I think this package stuff is specific to how docs.rs builds the crates given to it.

docs(lro): to_stream methods

---

src/wkt/src/wrappers.rs

Part of the work for #645
Implement `Message` for `BoolValue`, as suggested by @coryan.
If this looks right, I'll proceed with the other `*Value` types in `wrappers.rs`.

impl(wkt): `BoolValue` in `Any`

---

src/wkt/src/wrappers.rs

Part of the work for #645 
Implement `Message` for the wrapper types (except for `BytesValue`, `UInt64Value`, and `Int64Value`, which require extra care to serialize/deserialize).
Use macros, because the code is repetitive.

impl(wkt): `Message` for several wrapper types

---

src/wkt/src/wrappers.rs

Part of the work for #645 
Implement `Message` for `UInt64Value` and `Int64Value`. These values get encoded as strings.
I will re-use `encode_string()` for `BytesValue`. I did not think it was worth factoring out the `from_map()` impls.

impl(wkt): `(U)Int64Value` in `Any`

---

generator/internal/rust/annotate.go
generator/internal/rust/annotate_test.go
generator/internal/rust/templates/common/enum.mustache

After converting the enum value names to Rust style we may find some
duplicates. With this change the generator can skip the dups. In all
practical cases the dups are harmless, they differ in case but have the
name numeric value. We warn if this assumption fails.
part of the work for #829

feat(generator/rust): skip duplicate enum values

---

Cargo.lock
src/wkt/Cargo.toml
src/wkt/src/wrappers.rs

Fixes #645 
https://protobuf.dev/programming-guides/json/ says:
> JSON value will be the data encoded as a string using standard base64 encoding with paddings. Either standard or URL-safe base64 encoding with/without paddings are accepted."
I think using `STANDARD` as the base64 generator makes the most sense.

impl(wkt): `BytesValue` in `Any`

---

.github/workflows/sdk.yaml

Use symbolic names for the "current" (or "highest version tested") and "msrv" (or "oldest version tested") of Rust and go. With symbolic version names we get stable job names, and then we don't have to change the branch protection rules every time we update the versions.
In the process of making these changes I discovered that we were installing Rust 1.70, but not configuring cargo+rustup to actually use it. And then `Cargo.lock` was too new, so I needed to clean that up (we need Rust >= 1.78 for Cargo.lock version 4), and then some of our deps required newer versions of Rust, so I had to bump the MSRV. The latter is not a big deal only because we are about to bump this to 1.85 anyway, but we need to think about how testing with older versions of Rust may invalidate the lock file.
Part of …

ci(gha): make Rust versions symbolic

---

.gcb/integration.yaml
.github/workflows/sdk.yaml
src/auth/.gcb/integration.yaml

Build with Rust 1.85 and Rust 1.85.1. We will update the second as new
releases are created. I expect the first to be more stable.
Part of the work for #1559

chore: update builds to Rust 1.85

---

doc/contributor/howto-guide-set-up-development-environment.md

My VS Code was struggling on macros. They were all red squigglies. This configuration helps VS Code expand and lint macros.
optional: Make the `settings.json` copy-paste-able, as is.

cleanup: vscode config for macros

---

generator/internal/api/model.go
generator/internal/parser/openapi.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go
generator/internal/parser/testdata/test_service.proto

Methods can return "nothing". For Protobuf this is represented by the
`.google.protobuf.Empty` message. OpenAPIv3 has the same notion, but it
is represented differently (and I did not implement it).
In some languages we may want to map such return types to a "unit" type,
such as `void` in C++ and friends, or `()` in Rust.
Part of the work for #1549

feat(generator): support empty return types

---

.github/workflows/sdk.yaml
src/auth/src/lib.rs
src/auth/src/token_cache.rs

The token cache has a background task that keeps refreshing in the background before the token expires, irrespective of whether the token is used.
We can optimize in future to refresh only if the token is used in the past hour.

impl(auth): introduce TokenCache

---

src/wkt/src/prost.rs

Tonic converts `google.protobuf.Empty` to the unit type in method returns. We
(currently) return `wkt::Empty`, we should probably do the same as Tonic, but
this will do for now.
Part of the work for #1549

feat(wkt): convert the unit type to `Empty`

---

generator/go.mod
generator/internal/parser/mixin.go
generator/internal/parser/protobuf_mixin_test.go
generator/internal/parser/testdata/test_noempty_mixin.proto

Fixes #1598
At least I can generate the code for Rust, and it was failing before.

fix(generator): load mixin dependencies

---

src/wkt/src/prost.rs

After other changes, it turns out we do not need this.
This reverts commit ccb413b8fe6673a1a2a97d082af36533aaba1e6a, #1593
Another followup frm #1539

revert(wkt): convert the unit type to `Empty`

---

.gcb/builds/main.tf
.gcb/builds/resources/main.tf
.gcb/builds/services/main.tf
Cargo.lock
doc/contributor/howto-guide-set-up-development-environment.md
src/firestore/Cargo.toml
src/integration-tests/Cargo.toml
src/integration-tests/src/firestore.rs
src/integration-tests/src/lib.rs
src/integration-tests/tests/driver.rs

Since this is the first gRPC-based client some integration tests seem
appropriate. I just tested basic CRUD stuff, pagination and delete are probably
the most interesting.
Fixes #1549

test(firestore): add basic integration tests

---

src/auth/src/credentials/user_credential.rs

For user credentials, use the token cache introduced in #1554

impl(auth): introduce caching for user credentials

---

guide/samples/src/polling_policies.rs
guide/src/configuring_polling_policies.md
guide/src/working_with_long_running_operations.md
src/gax-internal/src/http.rs
src/gax-internal/tests/http_client_polling.rs
src/gax/src/lib.rs
src/gax/src/options/mod.rs
src/gax/src/polling_error_policy.rs
src/lro/src/details.rs
src/lro/src/lib.rs
src/lro/tests/fake_library/builders.rs

The policy is all about handling polling errors, renaming to
`PollingErrorPolicy` makes the intent clearer, and more consistent with
the names of other policies.
Part of the work for #1135

refactor!: rename polling policy

---

generator/dart/generated/google_cloud_language/lib/language.dart
generator/dart/generated/google_cloud_rpc/lib/rpc.dart
generator/internal/dart/dart.go
generator/internal/dart/dart_test.go
generator/testdata/dart/protobuf/golden/secretmanager/lib/secretmanager.dart

- rewrite api references to use code formatted text
- fix https://github.com/googleapis/google-cloud-rust/issues/1566
This rewrites `[foo][bar]` api references to use code formatted text:
```
`foo`
```
which avoids writing incorrect refs into the generated dartdoc; we'll want to follow up with #1575 in the near term.

feat(generator/dart): rewrite api references to use code formatted text

---

src/integration-tests/Cargo.toml

This is only used when the `log-integration-tests` feature is enabled
set.

chore(deps): `tracing-subscriber` is optional

---

src/gax-internal/src/http.rs
src/gax/src/lib.rs
src/gax/src/options/mod.rs
src/gax/src/polling_error_policy.rs

I temporarily left some backwards compatibility names to keep the PRs
small enough. This finally cleans all of them up.
Fixes #1135

cleanup!: remove `PollingPolicy` vestiges

---

src/gax/src/options/mod.rs

Fixes #1622 
`ClientConfig` is more set once and forget. It does not need to be able to reset any of its fields.
Note that we do not need to version bump in `gax`. `v0.21.0` has not been released yet.

cleanup(gax)!: `ClientConfig` does not need to clear options

---

src/auth/src/token_cache.rs

Remove  `allow(dead_code)` from token cache because all credential types now use the cache. Fixes #1552.

cleanup(auth): Remove deadcode attribute from token cache

---

src/gax/src/paginator.rs
src/integration-tests/tests/pagination.rs

Noticed in #1541 
https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv
My read on this is that we should use `into_` because this is a cheap operation that consumes the underlying type. It is at a similar level of abstraction, but I think the "cheap" part is why `into_` fits better than `to_`.
This is not a break, because the renamed APIs (added in #1466) have not been released yet.

cleanup(gax): rename paginator to stream

---

Cargo.lock
guide/samples/Cargo.toml
guide/samples/src/lib.rs
guide/samples/src/retry_policies.rs
guide/samples/tests/driver.rs
guide/src/SUMMARY.md
guide/src/configuring_retry_policies.md

Add a section on how to configure retry policies for the client and
per-request.
Fixes #1652 and fixes #1653

docs: user-guide section on retry policies

---

generator/dart/examples/lib/language.dart
generator/dart/generated/google_cloud_language/README.md
generator/dart/generated/google_cloud_language/lib/language.dart
generator/dart/packages/google_cloud_gax/lib/common.dart
generator/internal/dart/annotate.go
generator/internal/dart/dart.go
generator/internal/dart/dart_test.go
generator/internal/dart/generate.go
generator/internal/dart/templates/README.md.mustache
generator/internal/dart/templates/lib/service.mustache
generator/testdata/dart/protobuf/golden/secretmanager/README.md
generator/testdata/dart/protobuf/golden/secretmanager/lib/secretmanager.dart

Minor refactorings and code cleanups:
- rename the main (http client) parameter into the service constructors
- consolidate the logic to name fields into a `fieldName()` method
- updates to the generated README.md files

refactor(generator/dart): minor refactorings and code cleanups

---

Cargo.lock
guide/samples/Cargo.toml
guide/samples/src/error_handling.rs
guide/samples/src/lib.rs
guide/samples/tests/driver.rs
guide/src/SUMMARY.md
guide/src/error_handling.md
src/integration-tests/src/secret_manager/protobuf.rs

docs: user guide on error handling

---

generator/internal/sidekick/rust_generate.go

For some reason, `cargo doc` goes into modules that are `#[doc(hidden)]`.
This was making the `sidekick rust-generate` command fail because `crate::grpc::Client` does not exist in `gax-internal` when we only enable the HTTP feature:
https://github.com/googleapis/google-cloud-rust/blob/26c98334608cc879fe1457aa0688eb96324afaa2/src/gax-internal/src/options.rs#L17
Try for yourself with:
```sh
env RUSTDOCFLAGS="-D warnings" cargo doc -p google-cloud-tpu-v2
```
My fix is to not build docs for any dependencies in this command, which is sufficient, and a good change anyway. `cargo docs --no-deps` will still fail if we try to link types that don't exist in dependencies.

ci: fix cargo doc for new library

---

src/gax/src/error/rpc/mod.rs

I had the wrong type URLs for the error details. They were missing all
the `type.googleapis.com/` prefixes. Without them, the deserialization
via `wkt::Any` fails, and the errors were not correct.

fix(gax): deserialize error details

---

Cargo.lock
guide/samples/Cargo.toml
guide/samples/src/examine_error_details.rs
guide/samples/src/lib.rs
guide/samples/tests/driver.rs
guide/src/SUMMARY.md
guide/src/examine_error_details.md

docs(user-guide): how to examine error details

---

src/gax/src/client_builder.rs
src/gax/src/error.rs
src/gax/src/error/credentials.rs

`CredentialError` represents problems trying to create the
authentication credentials. Some of these errors are recoverable, e.g.,
trying to fetch access tokens from the metadata server. Other errors are
not, e.g., malformed credential files.
Part of the work for #1542

feat(gax): new type to represent credential errors

---

src/auth/src/credentials.rs
src/auth/src/credentials/api_key_credential.rs
src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/service_account/jws.rs
src/auth/src/credentials/user_credential.rs
src/auth/src/errors.rs
src/auth/src/token_cache.rs

This is part of the work to move the `CredentialError` type out of the
crate.
Part of the work for #1542

refactor(auth): move error helpers to module

---

src/gax-internal/src/grpc.rs
src/gax-internal/src/grpc/from_status.rs
src/gax-internal/tests/grpc_simple_request.rs
src/gax/src/error/rpc.rs

Tonic returns `tonic::Status` as errors, we want to treat these as a
`gax::error::ServiceError`. In this PR we just handle the code error
message. This makes the retry loop reusable for gRPC. The additional
details will happen in future PRs.
Part of the work for #1699

feat(gax-internal): convert `tonic::Status` errors

---

.github/workflows/generator_dart.yaml
generator/dart/examples/bin/language_api.dart
generator/dart/generated/google_cloud_protobuf/lib/src/protobuf.p.dart
generator/dart/generated/google_cloud_rpc/.sidekick.toml
generator/dart/generated/google_cloud_rpc/lib/rpc.dart
generator/dart/generated/google_cloud_rpc/lib/src/rpc.p.dart
generator/dart/generated/google_cloud_rpc/pubspec.yaml
generator/dart/generated/google_cloud_rpc/test/status_test.dart
generator/dart/tests/test/status_test.dart

Add error utility methods to `rpc.Status`:
- add a `Status.errorInfo` getter which retrieves the single expected ErrorInfo instance from Status.details
- add a `Status.localizedMessage` getter to get any `LocalizedMessage` from the details list
- add `Status.detailsAsMessages` which can autoconvert the ~10 known error types
- closes https://github.com/googleapis/google-cloud-rust/issues/1572
This should make it easier for users to unpack the `Any` messages from `Status.details`. Code completion will show the existing members for `Status` (code, message, details) as well as these three new extension methods.

feat(generator/dart): add error utility methods to rpc.Status

---

src/auth/src/credentials.rs
src/auth/src/credentials/api_key_credential.rs
src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/user_credentials.rs
src/auth/tests/credentials.rs
src/gax-internal/tests/auth.rs

This change is a part of an effort to Consistently use the term "Credentials" instead of "Credential"

fix(auth): Rename CredentialTrait to CredentialsTrait and UserCredential to UserCredentials

---

src/auth/integration-tests/src/lib.rs
src/auth/src/credentials.rs
src/auth/src/credentials/api_key_credentials.rs
src/auth/tests/credentials.rs

This change is a part of an effort to Consistently use the term "Credentials" instead of "Credential"

fix(auth): Replace api_key_credential with api_key_credentials

---

src/auth/src/credentials/api_key_credentials.rs

Missed some parts in API Key file in previous PR.

fix(auth): Updating ApiKeyCredential to ApiKeyCredentials

---

generator/internal/rust/templates/grpc-client/transport.rs.mustache
src/auth/src/credentials.rs
src/auth/src/credentials/api_key_credentials.rs
src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/user_credentials.rs
src/auth/src/lib.rs
src/auth/tests/credentials.rs
src/auth/tests/crypto_provider.rs
src/firestore/src/generated/gapic/transport.rs
src/gax-internal/echo-server/src/lib.rs
src/gax-internal/grpc-server/src/lib.rs
src/gax-internal/src/grpc.rs
src/gax-internal/src/http.rs
src/gax-internal/src/options.rs
src/gax-internal/tests/auth.rs
src/gax-internal/tests/client_builder.rs
src/lro/tests/fake/library/client.rs

fix(auth): Rename the public Credential Struct to Credentials

---

generator/internal/rust/templates/grpc-client/transport.rs.mustache
src/auth/integration-tests/src/lib.rs
src/auth/src/credentials.rs
src/auth/tests/credentials.rs
src/auth/tests/crypto_provider.rs
src/firestore/src/generated/gapic/transport.rs
src/gax-internal/src/grpc.rs
src/gax-internal/src/http.rs

fix(auth): Rename create_access_token_credential to create_access_token_credentials

---

doc/contributor/howto-guide-generated-code-maintenance.md

This trips up a lot of Debian users, where the protobuf system package is `v21`.

doc: contributor protoc prereqs

---

src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/tests/credentials.rs
src/auth/tests/crypto_provider.rs

fix(auth): Rename ServiceAccountCredential and MDSCredential

---

src/auth/src/credentials.rs
src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/user_credentials.rs
src/auth/src/errors.rs
src/auth/src/lib.rs
src/auth/tests/credentials.rs
src/gax-internal/tests/auth.rs
src/gax/src/error.rs
src/gax/src/error/credentials.rs
src/gax/src/retry_policy.rs

fix(auth): Rename CredentialError to CredentialsError

---

ci/requirements.txt
doc/contributor/howto-guide-set-up-development-environment.md
guide/src/setting_up_rust_on_cloud_shell.md
guide/src/setting_up_your_development_environment.md

We have some broken links in the documentation.
My local `mdformat` is version `0.7.18` which will escape `[` and `]` that aren't proper links. This alerted me to the missing links.
`mdformat` `v0.7.19` (which we currently use in our CI) stopped escaping `[` and `]` that weren't proper links.
I think we should revert our version of `mdformat` until there is a compelling reason to take another update, because it is good to flag broken links.

docs: fix broken links

---

src/auth/.gcb/builds/service_account_test/main.tf
src/auth/integration-tests/README.md
src/auth/src/credentials.rs
src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/user_credentials.rs
src/auth/tests/credentials.rs
src/gax/src/client_builder.rs
src/gax/src/error/credentials.rs

fix(auth): Leftover Credential to Credentials renaming

---

src/auth/src/credentials/mds.rs
src/auth/tests/credentials.rs

**Motivation:**
Align the MDS credential builder methods with the convention used by other builders in the module, primarily by adopting the `with_` prefix for configuration methods.
**Changes:**
* Refactored the MDS credential builder implementation. Renamed the following public methods to use the `with_` prefix for consistency:
* `endpoint(value)` -> `with_endpoint(value)`
* `quota_project_id(value)` -> `with_quota_project_id(value)`
* `universe_domain(value)` -> `with_universe_domain(value)`
* `scopes(value)` -> `with_scopes(value)`

cleanup(auth): update MDS credential builder methods

---

generator/internal/rust/templates/grpc-client/transport.rs.mustache
src/auth/src/credentials.rs
src/auth/src/credentials/api_key_credentials.rs
src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/user_credentials.rs
src/auth/tests/credentials.rs
src/firestore/src/generated/gapic/transport.rs
src/gax-internal/src/grpc.rs
src/gax-internal/src/http.rs
src/gax-internal/tests/auth.rs

Part of making the auth methods rusty

fix(auth): rename get_headers to headers

---

ARCHITECTURE.md

This PR fixes minor typos in the architecture document.

docs: fix typos in architecture document

---

generator/internal/dart/dart.go
generator/internal/dart/dart_test.go

- expand the list of dart keywords
This allows generation of `google/firestore/v1` (an enum there - StructuredQuery$FieldFilter$Operator - has an enum value named `in`).

feat(generator/dart): expand the list of dart keywords

---

src/auth/src/credentials.rs
src/auth/src/credentials/api_key_credentials.rs
src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/user.rs
src/auth/src/token.rs
src/auth/src/token_cache.rs
src/auth/tests/credentials.rs
src/auth/tests/crypto_provider.rs
src/gax-internal/tests/auth.rs

Part of making the auth methods rusty

fix(auth): Rename get_token to token

---

.typos.toml

- have the typos-cli config apply to all languages
This adjusts the config in `.typos.toml` so that it's not rust specific; related to https://github.com/googleapis/google-cloud-rust/pull/1731.

chore: have the typos-cli config apply to all languages

---

src/gax-internal/src/grpc/from_status.rs
src/gax/src/error/rpc.rs

gRPC uses this spelling: https://grpc.io/docs/guides/status-codes/
and so does the `google.rpc.Code` proto: https://github.com/googleapis/googleapis/blob/07c7b132c79656e944a2cc97fb400532834eb6f0/google/rpc/code.proto#L41
(While many other protos in googleapis use the spelling with a single `L`, consistency with the `google.rpc.Code` proto seems most important.)

cleanup(gax)!: prefer "CANCELLED"

---

src/gax-internal/grpc-server/protos/service.proto
src/gax-internal/grpc-server/src/generated/protos/google.test.v1.rs
src/gax-internal/grpc-server/src/lib.rs
src/gax-internal/tests/grpc_retry_loop.rs
src/gax-internal/tests/grpc_simple_request.rs

Support pausing in the gRPC echo server. We will need this to test timeouts over gRPC.
`grpc::Client` does not currently have a way to inject custom headers on a request. I preferred to add a field to the `EchoRequest` instead of trying to send a `delay_ms` header.
This new functionality is not exercised in this PR. We do not test the test code.
I initially planned to use a `google.protobuf.Duration` but that introduced all sorts of `prost_types` horribleness that was not worth dealing with.

impl(grpc-server): support delays

---

guide/src/initialize_a_client.md

Clients no longer have a public `new()`. They use `builder().build().await?`.
The link doesn't exist, because we haven't published the docs yet.

docs: update client builder

---

.github/workflows/generator.yaml
.github/workflows/lint.yaml
.github/workflows/sdk.yaml

- bump the golang version to `1.23.8`
(investigating the breakage from https://github.com/googleapis/google-cloud-rust/pull/1748)

chore: bump the golang version to 1.23.8

---

.github/workflows/generator.yaml

Matrix dimensions show up in the names of builds. The list of required builds is maintained by name. Changing the name to something static ("go:current") saves us some toil in maintaining the list of required builds.

ci: constant build names

---

generator/all_test.go

We use `go` locally, with no permissions. We are not really susceptible to vulnerabilities.
So remove the vulnerability check, which can break the CI without a PR.

ci: no more `govulncheck`

---

src/gax/src/lib.rs
src/gax/src/response.rs

feat(gax): a wrapper for responses with metadata

---

src/gax-internal/tests/retry_loop.rs
src/gax-internal/tests/timeout.rs
src/gax/Cargo.toml
src/gax/src/retry_loop_internal.rs
src/gax/src/retry_policy.rs

Motivated by #1612  (I will want a test like this for gRPC timeouts, so write the HTTP one first)
We have tests for the effective timeout fn, but no tests that verify we call it with the right parameters in the `ReqwestClient`. This code:
https://github.com/googleapis/google-cloud-rust/blob/aaf619e1dadbd6b78ce8c61e41d86a0735ecf113/src/gax-internal/src/http.rs#L127-L129
So add a test that verifies the effective timeout.
While we are here, put some stricter bounds on the other timeout tests.
In order to make this work, we use `tokio::time::Instant::now().into_std()` internally. This lets us control the timing in our tests. Note that `tokio`'s wrapper is as thin as possible. https://docs.rs/tokio/1.42.2/src/tokio/time/instant.rs.html#33-36

test(http): effective timeout used in loop

---

.github/workflows/generator_dart.yaml

- validate that the code we generate is the same as the code being committed (the source googleapis SHAs are the same, all the affected clients have been generated, ...)

chore: validate the committed clients

---

src/gax-internal/src/http.rs
src/gax/src/retry_loop_internal.rs

Motivated by #1612 
While this thing could stay in the `gax-internal` crate, I like it next to the `retry_loop` helper.
I am not sure if `auth` will need it. I cannot think that far ahead.

refactor: move effective timeout

---

src/gax-internal/src/grpc.rs
src/gax-internal/tests/grpc_timeout.rs

With this PR, the `grpc::Client` requests attempt timeouts (from the request options) and overall timeouts (from the retry policy).
Reviewers are strongly encouraged to compare `grpc_timeout.rs` with [`timeout.rs`](https://github.com/googleapis/google-cloud-rust/blob/9362b27551d435040594a0cd77ce4e632ce8fac8/src/gax-internal/tests/timeout.rs).

impl(gaxi): support timeouts over gRPC

---

doc/contributor/howto-guide-set-up-development-environment.md

This PR fixes minor typos in: `Howto-Guide: Set Up Development Environment` document.

docs: fix typos in setup dev environment document

---

guide/samples/tests/mocking.rs

In response to: https://github.com/googleapis/google-cloud-rust/pull/1722#discussion_r2030186037
I think it is odd that we have to set the HTTP code twice. Perhaps the plan is for `Status.code` to represent a gRPC code.

cleanup: real error in mocking user guide

---

.gitignore
src/wkt/src/any.rs
src/wkt/src/duration.rs
src/wkt/src/rstruct.rs
src/wkt/src/timestamp.rs

I used `cargo mutants` to find missing tests or cases where the code
could be simpler. With this, the generated code still has coverage
gaps, but we typically ignore those.

test(wkt): fix coverage gaps

---

.github/workflows/generator_dart.yaml
generator/dart/generated/google_cloud_functions_v2/lib/cloudfunctions.dart
generator/dart/generated/google_cloud_longrunning/.sidekick.toml
generator/dart/generated/google_cloud_longrunning/lib/longrunning.dart
generator/dart/generated/google_cloud_longrunning/lib/src/longrunning.p.dart
generator/dart/generated/google_cloud_longrunning/pubspec.yaml
generator/dart/generated/google_cloud_longrunning/test/operation_test.dart
generator/internal/dart/annotate.go
generator/internal/dart/dart.go
generator/internal/dart/templates/lib/message.mustache
generator/internal/dart/templates/lib/method.mustache

- update the dart generator so that LRO methods use type parameters on their `Operation` result to indicate the expected result operation metadata
- hand-write an Operation class (based on the generated class) which provides `responseAsMessage` and `metadataAsMessage` getters to unpack the response and metadata typed objects from their respective Any instances
- the API delta for an API using LROs can be seen here: https://github.com/googleapis/google-cloud-rust/commit/d23837910cd80ef2f696c7fc67792401853848da
Note that this PR doesn't contain anything to help the user poll for the status of an LRO.
This keeps the existing `Any? response` and `Any? metadata` fields on Operation, and adds the typed `T? responseAsMessage` and `S? metadataAsMessage` getters. I don't know how important it is …

feat(generator/dart): generate LRO Operations with generic type parameters

---

.github/workflows/sdk.yaml
doc/contributor/howto-guide-set-up-development-environment.md
src/auth/src/credentials/mds.rs
src/firestore/src/convert.rs
src/firestore/src/status.rs
src/gax-internal/src/query_parameter.rs
src/gax/src/error/rpc.rs
src/gax/src/polling_error_policy.rs
src/gax/src/retry_policy.rs
src/gax/src/retry_throttler.rs
src/lro/src/details.rs
src/lro/src/lib.rs
src/wkt/src/duration.rs

`cargo clippy` does not lint the tests, `cargo clippy --profile=test` is
what we want to run.

cleanup: clippyfy all the tests

---

Cargo.lock
guide/samples/Cargo.toml
guide/samples/tests/mocking_lros_error.rs
guide/src/mocking_lros.md

Fixes #1661 
Describe how to simulate different types of LRO errors in tests in the user guide.
Looks like: [mocking_lros_error.pdf](https://github.com/user-attachments/files/19617740/mocking_lros_error.pdf)

docs: user guide for mocking LRO errors

---

src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/user_account.rs

Add indentation, break some long lines, and avoid `vec!` where not
needed. I think this makes the examples easier to read.

cleanup(auth): easier to read examples

---

generator/internal/rust/annotate.go
generator/internal/rust/codec.go
generator/internal/rust/codec_test.go

I am about to add another parameter that must be passed deep into the
call hierarchy. Changing a lot of functions to take a extra parameter
seems worse than having them take a codec parameter as in `codec.Foo()`.
Part of the work for #1813

refactor(generator/rust): pass parameters via codec

---

generator/internal/rust/codec.go
generator/internal/rust/codec_test.go

When targeting services that are gRPC-only, we need to generate all
methods, including those that lack HTTP annotations.
Part of the work for #1813

feat(generator/rust): methods w/o HTTP annotations

---

guide/src/introduction.md
guide/src/working_with_long_running_operations.md

This PR fixes minor typos in two chapters of the User Guide:
1. Introduction
2. Working with long-running operations

docs: fix typos in user guide

---

doc/contributor/howto-guide-set-up-development-environment.md

Integration tests require speech-to-text API enabled to run.
Fixes #1824

docs: add speech-to-text api to set up dev instructions

---

src/gax-internal/tests/grpc_auth.rs

Motivated by #1612 
Make sure we call auth from inside the retry loop for the gRPC client, and bubble up the errors, and all that jazz.
These tests are basically the same as the `auth.rs` tests for the HTTP client. The reviewer is heavily advised to compare the test fixtures.
I am kicking the can on trying to unify gRPC vs. HTTP client tests. We would have to unify the interface for both servers and both clients. I am not sure it is worth doing yet.
While we're here, speed up the existing auth test for the HTTP client by using a snappier backoff policy.

test(gaxi): auth in grpc client

---

generator/internal/api/model.go
generator/internal/parser/protobuf.go
generator/internal/parser/routing_info.go
generator/internal/parser/routing_info_test.go
generator/internal/parser/testdata/routing_info.proto
generator/testdata/googleapis/google/api/routing.proto

Parse the method routing extensions (if any) and save them in the model.
In a future PR we will use these extensions to generate Rust code.
Fixes #1819

impl(generator/rust): parse routing extensions

---

src/gax-internal/src/grpc.rs

Move header creation outside of the retry loop.
The strings referenced by a `HeaderValue` (such as our `api_client_header`) are copied into a `HeaderMap` when a `HeaderMap` is made. The lifetime of the `HeaderMap` is easier for the compiler to reason about. (We do not want the inner call in the retry loop to have a `'static` lifetime, which I think is what was happening when we tried to hold `&'static str`s in it.)
Cleanups:
- This brings us to <= 7 parameters, so we can remove the clippy allows.
- Restrict visibility on implementation details. `execute()` is the only API we need to expose for our tests / client crates.

refactor(gaxi): make fixed headers outside of loop

---

src/gax-internal/src/grpc.rs

`endpoint.connect()` would fail when trying to connect to `https://firestore.googleapis.com`. This was noticed when running the integration tests with a firestore client implemented by the `grpc::Client`.
Apparently we need to configure TLS on the endpoint. Note that:
(1) Our current firestore client (which passes the integration tests) uses `tonic::Endpoint::new()` (which @coryan notices is not part of `tonic`'s public API)
https://github.com/googleapis/google-cloud-rust/blob/cf54b210da52fd216042b57fb235e0edbb9cec47/src/firestore/src/generated/gapic/transport.rs#L74
(2) We are enabling the `_tls-any` feature via `tonic:tls-ring`, which gates the `tonic::transport::ClientTlsConfig` API.

impl(gax-internal): fix tonic endpoints

---

src/gax-internal/src/grpc.rs
src/gax-internal/tests/grpc_auth.rs
src/gax-internal/tests/grpc_retry_loop.rs
src/gax-internal/tests/grpc_simple_request.rs
src/gax-internal/tests/grpc_timeout.rs

Similar to #1833, these `GrpcMethod`s just hold two `&'static str`s. We will put it into an `Extensions` (which we need to do anyway). Note that `Extensions` box the values on insert. The `Extensions` is moved into the inner functor. It does not extend the lifetime of the functor.

refactor(gaxi): plumb `Extensions`, not `Method`

---

src/gax-internal/src/lib.rs
src/gax-internal/src/routing_parameter.rs

Implement functions to match routing parameters and their templates.
These functions will be used in the generated code to generate the
`x-goog-request-params` header.
Part of the work for #1846

impl(gax-internal): routing parameter matchers

---

src/gax-internal/src/grpc.rs
src/gax-internal/tests/grpc_auth.rs
src/gax-internal/tests/grpc_retry_loop.rs
src/gax-internal/tests/grpc_simple_request.rs
src/gax-internal/tests/grpc_timeout.rs

We want to return a full `tonic::Response`, so we can convert it to a full `gax::Response`. (i.e. we do not want to drop the metadata in the `grpc::Client`).

refactor(gaxi): return full `tonic::Response`

---

generator/dart/generated/google_cloud_secretmanager_v1/lib/secretmanager.dart
generator/internal/dart/annotate.go
generator/internal/dart/templates/lib/message.mustache

- use json names for fields when encoding and decoding
This switches from using the Dart field name (which is mostly the json name, but can occasionally be different) to using the json name when parsing from or converting to json. Found when generating google.cloud.aiplatform.v1, which has a field named `enum`, which we generate as `enum$`.

fix(generator/dart): use json names for fields when encoding and decoding

---

generator/dart/generated/google_cloud_common/lib/common.dart
generator/dart/generated/google_cloud_functions_v2/lib/cloudfunctions.dart
generator/dart/generated/google_cloud_iam_v1/lib/iam.dart
generator/dart/generated/google_cloud_language_v2/lib/language.dart
generator/dart/generated/google_cloud_location/lib/location.dart
generator/dart/generated/google_cloud_longrunning/lib/longrunning.dart
generator/dart/generated/google_cloud_longrunning/lib/src/longrunning.p.dart
generator/dart/generated/google_cloud_protobuf/.sidekick.toml
generator/dart/generated/google_cloud_protobuf/lib/protobuf.dart
generator/dart/generated/google_cloud_protobuf/lib/src/protobuf.p.dart
generator/dart/generated/google_cloud_rpc/lib/rpc.dart
generator/dart/generated/google_cloud_rpc/lib/src/rpc.p.dart
generator/dart/generated/google_cloud_secretmanager_v1/lib/secretmanager.dart
generator/dart/generated/google_cloud_type/lib/type.dart
generator/dart/packages/google_cloud_gax/lib/gax.dart
generator/dart/packages/google_cloud_gax/lib/src/encoding.dart
generator/internal/dart/annotate.go
generator/internal/dart/dart.go
generator/internal/dart/dart_test.go
generator/internal/dart/templates/lib/enum.mustache
generator/internal/dart/templates/lib/message.mustache
generator/internal/dart/templates/lib/method.mustache

- rename base message and enum types to avoid name conflicts; `Message` => `GMessage` and `Enum` => `GEnum`
- rename the `package:google_cloud_gax/common.dart` library to `package:google_cloud_gax/gax.dart`
- remove the need to explicitly import `dart:typed_data` (we just export the Uint8List type to people importing the gax base library)
`Enum` was going to conflict with a type of the same name from google.protobuf (it was also shadowing the `Enum` type from dart:core). `Message` was going to conflict with a type from firebase cloud messaging. We will need to figure out name prefixing in the future (google.cloud.aiplatform also has a message named 'Type', but needs to be able to refer the one from protobuf as well), but I think we should rename away from Enum and Message since the names …

refactor(generator/dart): rename base message and enum types to avoid name conflicts

---

generator/internal/rust/annotate.go
generator/internal/rust/generate.go

Part of the work for #1854
Remove duplicate HasServices field in modelAnnotations
Changes made:
1. Removed the HasServices boolean field from the modelAnnotations struct
2. Added a HasServices() method that returns true if there are any services in the Services slice
3. Updated the call in generate.go to use the new method instead of the field

refactor(generator): replace HasServices field with method for service

---

src/gax-internal/src/grpc.rs
src/gax-internal/tests/grpc_convert.rs

Part of the work for #1612
The `grpc::Client` interfaces are all in `prost`/`tonic` land, whereas our stub interfaces are all in `gax` land.
Every API in the gRPC transport will need this conversion function, so factor it out into one place instead of generating it N times.

impl(gaxi): convert tonic response to gax response

---

Cargo.lock
generator/internal/rust/templates/grpc-client/transport.rs.mustache
src/firestore/Cargo.toml
src/firestore/src/generated/gapic/transport.rs
src/gax-internal/src/grpc.rs
src/storage/Cargo.toml
src/storage/src/generated/gapic/transport.rs

Most of the work for #1612
Implement our gRPC-based client crates using the `gaxi::grpc::Client`.
I think it is slightly more than a pure refactor as these clients now support timeouts.
We rely on the firestore integration tests to ensure correctness of the code.

refactor: use `grpc::Client`

---

Cargo.lock
src/gax-internal/Cargo.toml
src/gax-internal/build.rs
src/gax-internal/src/api_header.rs

Resolves https://github.com/googleapis/google-cloud-rust/issues/1872.
This change makes vendoring `google-cloud-rust` into a hermetic build system _substantially_ easier, as all environment variables needs to be enumerated. `built` reads a *lot* of environment variables, but `gaxi` is only interested in two values.

cleanup(gaxi): switch from `built` to `rustc_version`

---

generator/internal/rust/annotate.go
generator/internal/rust/annotate_test.go
generator/internal/rust/codec.go
generator/internal/rust/codec_test.go
generator/internal/rust/templates/common/Cargo.toml.mustache
src/generated/cloud/aiplatform/v1/.sidekick.toml
src/generated/cloud/aiplatform/v1/Cargo.toml

Introduce an option to generate per-service features. Use this option
in the `Cargo.toml.mustache` template to introduce the features and
the default feature.
Part of the work for #1863

feat(generator/rust): per-service feature option

---

generator/internal/rust/annotate.go
generator/internal/rust/annotate_test.go

Part of the work for #1612
In the HTTP transport, we defer to `reqwest::Method::is_idempotent()` to tell us whether a request is idempotent. We cannot use that dep for gRPC transport.
So add a helper function to return the default idempotency, given the `pathInfoAnnotation`.
In a follow up, I will modify the template to call this function, and `set_default_idempotency(...)` using the output.
Please eviscerate my golang code, this is all new to me.

impl(generator/rust): default idempotency

---

generator/internal/rust/templates/grpc-client/transport.rs.mustache
src/firestore/src/generated/gapic/transport.rs
src/storage/src/generated/gapic/transport.rs

Part of the work for #1612
Set the default idempotency in `firestore` and `storage`, thus retrying more requests by default.
See: #1883 for the equivalent changes over HTTP.
On testing... I will defer: #1884

feat: retry more requests in firestore, storage

---

generator/internal/api/service_dependencies.go
generator/internal/api/service_dependencies_test.go

Implement a function to compute the transitive closures of a service
dependencies, including all request messages, all response messages,
all LRO metadata and response messages, and the transitive deps of these
messages.
Part of the work for #1863

impl(generator/rust): compute service dependencies

---

generator/internal/api/model.go
generator/internal/parser/routing_info.go
generator/internal/parser/routing_info_test.go

It is easier to generate code for the RoutingInfo if the path template
variants are grouped by name.
Fixes #1819 for realsies.

feat(generator): group RoutingInfo variants

---

Cargo.lock
src/auth/Cargo.toml
src/auth/src/credentials/mds.rs

This PR removes the trailing slash from the default Metadata endpoint (`METADATA_ROOT `).
**Reason:**
* The trailing slash caused multiple calls to MDS, see: https://github.com/googleapis/google-cloud-rust/issues/1835
**Implementation Details:**
* Updated the `METADATA_ROOT` to remove trailing slash
* Added `url` crate to `dev-dependencies`.
* Added a unit test using the `url` crate to validate the format of the default URL(s): for fetching token and service account.

fix(auth): remove trailing slash from Metadata root

---

src/auth/src/credentials.rs

Updated documentation to comment out invalid closing brace.

cleanup(auth): comment out invalid closing brace

---

generator/dart/.sidekick.toml
generator/dart/generated/google_cloud_rpc/lib/rpc.dart

- bump to the latest API SHA
- regenerate the existing APIs
Note that this captures added fields to a message in package:google_cloud_rpc. In the future, we may want some mechanism to help us know that this change requires a a semver minor version bump for `package:google_cloud_rpc`.

feat(generator/dart): bump to the latest API versions

---

src/wkt/src/any.rs
src/wkt/src/duration.rs
src/wkt/src/message.rs
src/wkt/src/rstruct.rs
src/wkt/src/timestamp.rs
src/wkt/src/wrappers.rs

Tangential to #1609, #1767 
There are only 2 cases for encoding, either we put the serialization of something into a `value` field, or we flatten it.
So use helper functions for the two cases and remove instances of logic.
While we're here, write up my understanding of why the `Any` business is the way it is.

refactor(wkt): DRY for `impl Message`

---

Cargo.lock
Cargo.toml
src/auth/Cargo.toml
src/auth/src/credentials.rs
src/auth/src/credentials/api_key_credentials.rs
src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/user_account.rs
src/auth/tests/credentials.rs
src/gax-internal/tests/grpc_auth.rs
src/gax-internal/tests/http_auth.rs

As mentioned in https://github.com/googleapis/google-cloud-rust/issues/1843 updating the name of CredentialsTrait to CredentialsProvider to make it more rusty.

refactor(auth)!: rename CredentialsTrait to CredentialsProvider

---

generator/dart/generated/google_cloud_functions_v2/lib/cloudfunctions.dart
generator/dart/generated/google_cloud_location/lib/location.dart
generator/dart/generated/google_cloud_longrunning/lib/longrunning.dart
generator/dart/generated/google_cloud_secretmanager_v1/lib/secretmanager.dart
generator/internal/dart/annotate.go
generator/internal/dart/annotate_test.go
generator/internal/dart/templates/lib/method.mustache

- pass http query params when making calls
- fix https://github.com/googleapis/google-cloud-rust/issues/1577
- code re-generated in a 2nd commit
I verified this manually (at least w/ simple query params) using the gemini API. This handles the cases in the issue listed above (primitive types; repeated primitive types; messages, enums, and bytes). It doesn't handle repeated messages - which aren't part of the spec. It does handle repeated enums, which may or may not be part of the spec?

feat(generator/dart): support passing http query params

---

Cargo.lock
Cargo.toml
src/gax-internal/Cargo.toml
src/gax-internal/src/routing_parameter.rs

Use a Rust enum to avoid `if x == "**"`, the generator can convert the
wildcards into branches of the enum ahead of time. Also, the generator
can use a special branch for "trailing" multi-segment wildcards. Those
have slightly different matching rules.
Part of the work for #1846

impl(gax-internal): improve routing info matchers

---

src/gax-internal/src/grpc.rs
src/gax-internal/tests/grpc_simple_request.rs

When using routing info to populate the request parameters, it is
possible that none of the path templates matches, in which case we need
to omit the header.
Part of the work for #1846

impl(gaxi-internal): ignore empty request params

---

generator/internal/parser/protobuf_annotations.go
generator/internal/parser/protobuf_test.go
generator/internal/parser/testdata/auto_populated.proto

Part of the work for #439 
https://google.aip.dev/client-libraries/4235 says:
> The field must not be annotated with [`google.api.field_behavior = REQUIRED`](https://google.aip.dev/203#required).
I assume we will need to do the same thing for the OpenAPI version.
`impl` instead of `fix`, because we do not use the `AutoPopulated` field in practice.

impl(generator): fix protobuf auto populated fields

---

generator/internal/rust/annotate.go
generator/internal/rust/codec.go
generator/internal/rust/templates/crate/src/builder.rs.mustache
src/storage/src/generated/gapic/.sidekick.toml
src/storage/src/generated/gapic/builder.rs

While we figure out how to generate properly linked documentation for
client and request builders, we just disable the comments. They break
the build and we need to unblock development of some clients.
Part of the work for #1813

feat(generator/rust): workaround for veneers

---

generator/dart/packages/google_cloud_gax/lib/gax.dart
generator/dart/packages/google_cloud_gax/test/client_test.dart

- support http `put` in the general gax client (used by `google.monitoring.v3`)
- add simple tests for `ServiceClient`; verify that it sends correct http request methods and headers
@natebosch - do you mind taking a look at the testing code to see if its a reasonable way to exercise package:http code?

feat(generator/dart): add http 'put' to the general gax client

---

Cargo.lock
src/integration-tests/Cargo.toml
src/integration-tests/src/lib.rs
src/integration-tests/src/workflows.rs
src/integration-tests/src/workflows_executions.rs
src/integration-tests/tests/driver.rs

Verify we can successfully send enums as query parameters. There was
some question as to whether these worked fine when serialized as
integers.
Fixes #1932

test: verify enums as query parameters work

---

generator/internal/dart/annotate.go
generator/internal/dart/dart.go
generator/internal/dart/dart_test.go

- allow specifying using an import prefix for specific packages
This is to address generating `google.cloud.aiplatform.v1`, which both defines a `Value` message and also needs to reference the `Value` from google.protobuf (which would otherwise be shadowed by the local definition). We can use a sidekick config:
```toml
[codec]
'prefix:google.protobuf' = 'protobuf'
```
to have all references to `google.protobuf` types be prefixed by 'protobuf.':
```dart
import 'package:google_cloud_longrunning/longrunning.dart';
import 'package:google_cloud_protobuf/protobuf.dart' as protobuf;
import 'package:google_cloud_rpc/rpc.dart';
...
class BatchPredictionJob extends ProtoMessage {
...
final protobuf.Value? modelParameters;
...
}
```
Other alternatives would be always prefixing everything (which …

feat(generator/dart): allow specifying packages that need import prefixes

---

src/integration-tests/src/lib.rs
src/integration-tests/src/storage.rs

Part of the work for #1813, will be useful for testing #1951 
Add bucket CRUD tests minus the U.

test(storage): add CRD tests

---

src/gax-internal/src/http.rs
src/wkt/src/empty.rs

In a typical AIP compliant library, successful delete operations return google.protobuf.Empty as their response [AIP-135](https://google.aip.dev/135). When in REST Fallback mode  this means a response would be `{}` - empty JSON. However, certain services return `null` with a 204 `No Content` response, instead of an empty JSON response. This behavior happens with BigQuery and Compute for example. This means that with certain RPCs (mainly some delete operations), users using BigQuery or Compute in REST mode will get an error returned when the call actually succeeded on the call side.
`serde_json` throws an error when trying to deserialize with an empty byte array:
```
Error("EOF while parsing a value", line: 1, column: 0)
```
This PR refactor the `reqwest::Response` parsing to a separated …

feat(gax): return default value for struct for 204 NoContent responses

---

src/integration-tests/src/storage.rs
src/storage-control/src/client.rs

Fixes #1951 
Add the client surface for IAM operations from `google/storage/v2`, with examples (that build, but don't run), and integration tests for the new methods.
The method signatures (which are handwritten in this veneer) are consistent with the Get/Set/Test IAM methods from other crates.

feat(storage): IAM operations

---

src/gax/src/error/rpc.rs
src/lro/src/details.rs
src/lro/src/lib.rs
src/wkt/src/any.rs
src/wkt/src/duration.rs
src/wkt/src/message.rs
src/wkt/src/rstruct.rs
src/wkt/src/timestamp.rs
src/wkt/src/wrappers.rs

This PR is part of #1609.
What the PR does:
- Split up the old `Message` trait into two new traits (`Message` and `MessageSerializer<T>`)
- The `MessageSerializer<T>` is hidden, as it's an internal API that's not intended for direct use by consumers of the `wkt` crate.
**Note**:
- Even though in the initial design, we had proposed the `serializer()` function to have the following signature (using _static dispatch_):
```rust
fn serializer() -> impl MessageSerializer<Self> {
DefaultSerializer::<Self>::new()
}
```
In this PR, I've decided to go with an approach that would allow dynamic dispatch through trait objects:
```rust
fn serializer() -> Box<dyn MessageSerializer<Self>> {
Box::new(DefaultSerializer::<Self>::new())
}
```
The dynamic dispatch approach generally allows for more cleaner …

refactor(wkt): refactor `wkt::message::Message` trait to use new design

---

generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go
src/storage-control/src/generated/convert/storage/convert.rs

I am not sure why, but this field was not initialized. And I also do not
understand why this changed the generated code (for one enum).

fix(generator): initialize ID field for enums

---

src/gax/src/paginator.rs

Part of the work for #1609, noticed because of #1961 
This is a breaking change, because it prevents applications from implementing `(Item)Paginator`.
But if applications cannot implement these traits, it means we can add functions to them at will.
`lro::Poller` should get the same treatment. Will send a follow up.

cleanup(gax)!: seal Paginator traits

---

Cargo.lock
Cargo.toml
src/gax/src/paginator.rs
src/lro/Cargo.toml
src/lro/src/lib.rs

Part of the work for #1609, analog of #1971 
Seal `lro::Poller`. This lets us add functions to the trait without breaking customers (because customers are not able to implement this trait).

cleanup(lro)!: seal Poller

---

generator/internal/api/model.go
generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go
generator/internal/parser/testdata/deprecated.proto
generator/internal/parser/testdata/deprecated_openapi.json

Both Protobuf and OpenAPIv3 supporting marking some fields, messages,
requests and (in the case of Protobuf) even complete services as
deprecated. In this change we capture the information, but no generated
code changes.
Part of the work for #1958

feat(generator): capture deprecated markers

---

generator/internal/api/model.go
generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_test.go

Add attributes to directly determine if fields are maps, repeated, or
singular.
I will use this to refactor some of the templates.

feat(generator): better classify fields

---

Cargo.lock
guide/samples/src/error_handling.rs
guide/samples/src/examine_error_details.rs
src/gax-internal/echo-server/Cargo.toml
src/gax-internal/echo-server/src/lib.rs
src/gax-internal/src/grpc/from_status.rs
src/gax-internal/src/http.rs
src/gax-internal/tests/grpc_simple_request.rs
src/gax-internal/tests/grpc_timeout.rs
src/gax/src/error/http_error.rs
src/gax/src/error/rpc.rs
src/gax/src/error/service_error.rs
src/gax/src/polling_error_policy.rs
src/gax/src/retry_policy.rs
src/integration-tests/src/error_details.rs
src/integration-tests/src/lib.rs
src/integration-tests/src/storage.rs
src/integration-tests/tests/driver.rs

Change `gax::error::rpc::Status` to always use `Code` for the status code. When
the error includes a HTTP status code (1) that is captured in the
`ServiceError`, (2) we convert the `status` string, falling back to `Unknown`
if needed.
Fixes #1671

impl(gax): normalize service errors

---

src/gax-internal/Cargo.toml
src/gax-internal/src/grpc.rs
src/gax-internal/src/http.rs
src/gax-internal/src/lib.rs

We want to use `cargo-semver-checks` with this crate, and
`#[doc(hidden)]` disables all semantic version checks. The generated
documentation is still empty, because none of the features are enabled
by default and therefore no documentation is generated for them.

cleanup(gax-internal): enable semver checks

---

src/auth/src/credentials/mds.rs

By default MDS uses `metadata.google.internal`  host for the metadata server. If a user wants to use a different host name, currently the only was is to use builder and set the `endpoint`.
This change introduces another way: set the `GCE_METADATA_HOST` environment variable.
Note: If user sets the env var and also provides an endpoint override through builder, we will use the env var.

feat(auth): Introduce GCE_METADATA_HOST env var to set the metadata server host

---

.github/workflows/sdk.yaml
src/gax/Cargo.toml
src/gax/src/client_builder.rs
src/gax/src/lib.rs
src/gax/src/options.rs
src/gax/src/paginator.rs
src/lro/Cargo.toml
src/lro/src/details.rs
src/lro/src/internal.rs
src/lro/src/lib.rs
src/wkt/Cargo.toml
src/wkt/src/lib.rs

Implement features and set the attributes to keep implementation details
hidden until we want to run `cargo semver-checks`.

impl: support semver checks for internal

---

README.md
src/gax/Cargo.toml
src/gax/src/lib.rs
src/gax/src/paginator.rs
src/lro/Cargo.toml
src/lro/src/lib.rs

Document why we have internal modules, `_internal-*` features,
and `unstable-*` features.
Add documentation to the `unstable-stream` features and properly tag
any functions that are enabled with these features. Updated the
documentation around these functions.
Fixes #1780

docs: document features and internal modules

---

src/auth/src/credentials/mds.rs

Normally we do not set the scopes, querying the default service account
to get the scopes is wasteful, we can just omit the query parameter and
get the same result.

feat(auth): optimize common path for MDS

---

generator/internal/rust/annotate.go
generator/internal/rust/codec.go
generator/internal/rust/templates/crate/src/builder.rs.mustache
generator/internal/rust/templates/crate/src/client.rs.mustache
src/storage-control/src/client.rs
src/storage-control/src/generated/gapic/.sidekick.toml
src/storage-control/src/generated/gapic/builder.rs
src/storage-control/src/generated/gapic/client.rs

We are going to add another client (for StorageControl), which also has a `ClientBuilder`. We do not use either, and the types will clash, so stop generating them for veneers.
We also skip most of the client documentation (which references the `builder()`), if we will not be exposing the client.

impl(storage-control): hide unused builders

---

src/integration-tests/src/storage.rs
src/storage-control/src/client.rs

Add `{create, get, delete, list}_folder` APIs to the storage control client.
I picked out the client signature, and handwrote the examples in the method documentation. We will lock down the surface later. For now, we just want to get a decent first iteration out.
These are validated in an integration test.

feat(storage-control): add some of the Folders API

---

src/integration-tests/src/storage.rs
src/storage-control/src/client.rs

Internal annotations reveal that `folder_id` is a query param, not in the path. So let's remove it from our client signature, even though it is required.

cleanup(storage): future-proof CreateFolder API

---

src/auth/integration-tests/tests/driver.rs

Re enabling the API key integration test as discussed offline.
The flakiness was likely due to temporary issue with language service. If we see further flakiness, we can switch to a different API for testing.

test(auth): Re-Enable API Key integration test

---

src/auth/src/credentials.rs

Fixed #2077 
The testing module is used in gax tests, so hiding it instead of making it `pub(crate)`

fix(auth): Hide testing mod from public documentation

---

src/storage-control/src/generated/gapic/.sidekick.toml
src/storage-control/src/generated/gapic/model.rs

We will use the request structs for media operations. That will automate
more code generation, though we will still need to manually map these
requests to the right fields in the JSON v1 API.
Part of the work for #2040

impl(storage): enable requests for media RPCs

---

src/auth/integration-tests/src/lib.rs
src/auth/src/credentials.rs
src/auth/src/credentials/api_key_credentials.rs
src/auth/tests/credentials.rs

This PR resolves #2075.
It replaces the `create_api_key_credentials` factory function with a builder.
cc: @sai-sunder-s

refactor(auth)!: replace create_api_key_credentials with builder

---

src/firestore/Cargo.toml

cleanup(firestore): use workspace dependencies

---

generator/internal/api/model.go
generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/parser/protobuf.go
generator/internal/parser/protobuf_annotations.go
generator/internal/parser/protobuf_mixin_test.go
generator/internal/parser/protobuf_test.go
generator/internal/sample/api.go

A method may have more than one binding in its HTTP info data structure.
With this change we capture all the bindings. We duplicate some data to
split the change in smaller PRs.
Part of the work for #2090

feat(generator): capture all HTTP bindings

---

generator/internal/api/model.go
generator/internal/dart/annotate.go
generator/internal/dart/dart.go
generator/internal/golang/golang.go
generator/internal/golang/gotemplate.go
generator/internal/language/codec.go
generator/internal/language/codec_test.go
generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/parser/protobuf_annotations.go
generator/internal/parser/protobuf_mixin_test.go
generator/internal/parser/protobuf_test.go
generator/internal/rust/annotate.go
generator/internal/rust/annotate_test.go
generator/internal/rust/codec.go
generator/internal/rust/codec_test.go
generator/internal/sample/api.go

Remove the "default" binding for methods. The codecs now use the first
binding, though in the future they may support *all* bindings for a
method.
Fixes #2090

cleanup(generator): remove default binding

---

guide/src/setting_up_rust_on_cloud_shell.md
guide/src/setting_up_your_development_environment.md

docs: add google-cloud-gax instructions to cloud shell

---

generator/internal/rust/templates/convert-prost/message.mustache
generator/internal/rust/templates/convert-prost/oneof.mustache
src/firestore/src/convert.rs
src/firestore/src/generated/convert/firestore/convert.rs
src/firestore/src/generated/convert/rpc/convert.rs
src/firestore/src/generated/convert/type/convert.rs
src/firestore/src/status.rs
src/gax-internal/src/grpc.rs
src/gax-internal/src/prost.rs
src/storage-control/src/generated/convert/control/convert.rs
src/storage-control/src/generated/convert/iam/convert.rs
src/storage-control/src/generated/convert/storage/convert.rs
src/storage-control/src/generated/convert/type/convert.rs
src/storage-control/src/lib.rs

We want to use the existing to/from proto traits when converting LROs.
In order to convert from a `prost_types::Any` -> `wkt::Any`, we need to match on type IDs, deserialize a prost message, convert it to our of our types, then pack it into our `Any`.
Many of these steps can fail. So we need our convert from proto function to potentially return an error.
I left myself one TODO (in `to_gax_response`) related to the refactor to break down this already unruly PR. `unwrap()`ing is currently fine, because we only return `Ok()`. I will fix in a follow up.
The diff for `convert.rs` is fairly poor. Sorry.

refactor(gaxi): FromProto can error

---

Cargo.lock
src/auth/Cargo.toml

I think this addresses the same problems as #1806 and #1810

cleanup(auth): reduce `-sys` dependencies

---

src/auth/src/credentials/user_account.rs

Fixes #2119 
When we switched to the builder pattern, we started including the token cache, which fetches a token upon credential creation, not just on calls for the `token()`.
We were comparing the expiration time to a time from between when the credentials are created and from when we ask for a token.
We want to compare the expiration time to a time from before the credentials are created.

ci(auth): deflake UC test

---

src/auth/src/credentials.rs
src/auth/src/credentials/service_account.rs

Motivated by #2121 
Only generate private keys for test once.
This doesn't fix the flake, as generating the initial keys could take > 60s, which is our test timeout.
Anecdotally, this does make `cargo test -p google-cloud-auth` run significantly faster. My last run was 21s vs. 52s at HEAD. All 20s go to generating the key.

ci(auth): reuse PKs in test

---

src/wkt/src/internal.rs
src/wkt/tests/message_with_f32.rs
src/wkt/tests/message_with_f64.rs

Sometimes floating point values appear as integers on the wire. The service may
send `1` when the value is `1.0`, and the service is doing the right thing in
this case.

fix(wkt): deserialize floats from ints

---

generator/internal/rust/templates/grpc-client/transport.rs.mustache
src/firestore/src/generated/gapic/transport.rs
src/gax-internal/src/grpc.rs
src/gax-internal/tests/grpc_convert.rs
src/storage-control/src/generated/gapic/transport.rs
src/storage-control/src/generated/gapic_control/transport.rs

`cnv()` can fail, so `to_gax_response()` can fail, as well.
I considered just unrolling the function, but it has a nice unit test, so let's keep it where it is.

cleanup(gaxi): tonic response conversion

---

src/storage/src/client.rs

Also adds a small test for some of the different types that we need to deserialize and convert to control::model::Object.
For #2039

impl(storage): add simple fields to the v1::Object type

---

Cargo.lock

Just ran `cargo update`. At least one package that was yanked and we
need to downgrade.

chore: update `Cargo.lock` file

---

src/auth/src/token.rs

Fixes #2073 .
Since `token()` method that used to expose the `Token` struct has been removed as part of #2072, we are free to mark the `Token` struct as `pub(crate)`.

fix(auth)!: Make Token struct pub(crate) since it is not exposed in a public surface

---

src/gax-internal/src/prost.rs

We are going to expand `ConvertError` to have an `Other(#[from] anyhow::Error)` branch. This will deal with the `AnyError`s or prost's any pack/unpack errors.
General errors are not `Clone` or `PartialEq`, so we need to drop these traits. They were only used to simplify the tests.

cleanup(gaxi): prepare to expand `ConvertError`

---

src/gax-internal/src/prost.rs

These will be convenient failure modes to capture.
Errors packing/unpacking our Any's or prost Any's will go into `Other`.

impl(gaxi): expand `ConvertError`

---

Cargo.lock
Cargo.toml
guide/samples/Cargo.toml
src/gax-internal/Cargo.toml
src/gax-internal/src/prost.rs
src/wkt/Cargo.toml
src/wkt/src/duration.rs
src/wkt/src/timestamp.rs
src/wkt/tests/duration.rs

We would like to prevent breaking changes if these errors ever gain
variants that are not comparable.
Fixes #2151

cleanup!: errors do not need to be `PartialEq`

---

Cargo.lock
src/storage-control/Cargo.toml
src/storage-control/src/convert.rs

Implement conversions from prost Any to our Any, handling the storage control LRO types.
The reverse direction of #2155

impl(storage-control): Any FromProto for LRO types

---

src/storage-control/src/convert.rs

Implement conversion functions for `google::longrunning::Operation`.
All that is left is to add rename folder to the client surface.

impl(storage-control): LRO conversions

---

Cargo.lock
Cargo.toml
src/auth/Cargo.toml
src/auth/src/credentials.rs
src/auth/src/credentials/service_account.rs

Attempting to fix #2121 by using pre-generated primes to speed up key generation.

fix(auth): generate private key for test from primes

---

src/integration-tests/src/storage.rs
src/storage-control/src/client.rs

Part of the work for #2037 and #944 
Add `RenameFolder` (an LRO) to the client surface, and use it from the integration test.
This is not the greatest integration test of LROs over gRPC, as the initial RPC returns a `done` Operation. It would be nice to exercise the polling loop (i.e. the `GetOperation` calls).
This RPC fails if a quota project is provided, let's see if one is set in our CI. :crossed_fingers:

feat(storage-control): add `RenameFolder` API

---

src/integration-tests/src/error_details.rs
src/integration-tests/src/storage.rs
src/storage-control/src/client.rs
src/storage-control/tests/mocking.rs

Part of the work for #1813
This is #2114, but for the handwritten surface. Eventually we want to generate this thing, so its surface should match the generated surface. (At the moment, we have some extra examples, but those don't hurt. The important thing is that the signatures match).

cleanup(storage-control): future-proof API

---

src/gax-internal/src/prost.rs
src/wkt/src/any.rs
src/wkt/src/duration.rs
src/wkt/src/timestamp.rs
src/wkt/tests/duration.rs

Prefer saving the source of the error instead of the error formatted as
a string.
Add some examples to illustrate how some of these errors work.

fix(wkt)!: preserve sources of errors

---

generator/internal/sidekick/rust_generate.go

`rust-generate` leaves `Cargo.lock` and `Cargo.toml` unstaged. So add them to remove a (small) manual step in library generation.
(I think it makes more sense to run this command in sidekick, vs. in the instructions).

cleanup(generator): one less step to generate library

---

src/wkt/src/duration.rs

Call out when a method is gated by a feature flag in docsrs.
Note that `Timestamp` already has these annotations.

docs(wkt): call out feature flags in `Duration`

---

src/gax-internal/src/path_parameter.rs
src/wkt/src/any.rs
src/wkt/src/duration.rs
src/wkt/src/timestamp.rs

We do not know if these errors will need to expand, they might. Making
them `#[non_exhaustive]` prevents future breaking changes. We do not
expect the downsides to be too bad, as most applications would not be
matching on these errors.
Fixes #2180

feat!: make errors `#[non_exhaustive]`

---

guide/samples/src/lro.rs
guide/samples/tests/mocking_lros_auto.rs
guide/samples/tests/mocking_lros_error.rs
guide/samples/tests/mocking_lros_manual.rs
src/firestore/src/status.rs
src/gax/src/error/rpc.rs
src/integration-tests/src/workflows.rs
src/lro/src/details.rs
src/lro/src/internal.rs
src/lro/tests/fake/responses.rs
src/lro/tests/integration.rs
src/storage-control/src/convert.rs
src/wkt/src/any.rs
src/wkt/src/rstruct.rs
src/wkt/src/wrappers.rs
src/wkt/tests/any.rs

We decided the names were confusing and one of them clashed with the standard `TryFrom` trait. The new names are more evocative and shorter.
Fixes #2184

cleanup(wkt)!: rename `Any::` functions

---

src/wkt/src/timestamp.rs

Given the invariants in the `Timestamp` struct, the serialization can
never fail. So we can use `.expect()` instead of returning an error.
We can remove one of the branches in the `TimestampError` enum, and
use `From<Timestamp> for String` instead of `TryFrom`.
Fixes #2177

cleanup(wkt)!: `Timestamp` always serialize

---

src/integration-tests/Cargo.toml
src/integration-tests/src/showcase.rs

I skipped the mixin RPCs (Locations, Operations, and IAM), as these are
tested elsewhere, and against production.
Fixes #2201

test(showcase): relevant RPCs in showcase `Compliance`

---

Cargo.lock
Cargo.toml
src/auth/Cargo.toml
src/gax-internal/Cargo.toml
src/gax-internal/echo-server/Cargo.toml
src/gax-internal/grpc-server/Cargo.toml
src/gax/Cargo.toml
src/integration-tests/Cargo.toml
src/lro/Cargo.toml

Disabling the default defaures prevents (some) breaking changes
introduced as we stop using features of our dependencies.
I think making this change for both regular and `dev-` dependencies is
easier to maintain in the future. The less we need to think about these
things, the better.
Fixes #2219

cleanup(deps)!: disable default features

---

generator/internal/rust/annotate.go
generator/internal/rust/annotate_test.go

Capture the LRO types used by a service. We can include metadata and response types together, as we `match` on the typeid. (It is a lookup either way).
A follow up PR will have the generator own this chunk of code, which is just iterating over the `LROTypes`:
https://github.com/googleapis/google-cloud-rust/blob/ae91098c611434626e9809a1cab470ab81b870a0/src/storage-control/src/convert.rs#L115-L149

impl(generator/rust): capture LRO types for a service

---

generator/internal/rust/templates/grpc-client/transport.rs.mustache
src/storage-control/src/convert.rs
src/storage-control/src/generated/gapic_control/transport.rs

Most of the remaining work for #2037.
Support LRO conversion in the generator. This will stay up to date if new LROs are added to the storage control service.
Reminder that we have unit tests in `convert.rs` and an integration test for the rename folder LRO.
I haven't decided if I want to move the `ToProto` / `FromProto` impls into transport. We definitely could.
Note that the mustache template for each `LROType` could be used for each `ErrorInfo` in a `rpc::Status`.

impl(generator/rust): support for LRO over gRPC

---

src/gax-internal/src/http.rs
src/gax/src/error/core_error.rs
src/gax/src/error/credentials.rs
src/gax/src/error/http_error.rs
src/gax/src/error/service_error.rs
src/gax/src/polling_error_policy.rs
src/gax/src/retry_policy.rs

cleanup(gax)!: use `HeaderMap` for headers

---

src/storage-control/src/convert.rs

Fixes #2037 
In the fullness of time, the generator should probably own these `{To, From}Proto` conversions for LROs (and also the ones for `rpc::Status`).
But the important thing is that we don't have to do any work to update the conversions if/when a new LRO is added to Storage Control.
So I am removing the TODOs and close out the bug.

cleanup(storage-control): remove TODOs

---

src/storage-control/src/stub.rs

Fill out the `StorageStub`. It will temporarily have a broader API surface than the client. I think that is fine. Eventually the client surface will catch up.

feat(storage-control): complete stub

---

src/gax/src/backoff_policy.rs
src/gax/src/polling_backoff_policy.rs
src/gax/src/polling_error_policy.rs
src/gax/src/retry_policy.rs
src/gax/src/retry_throttler.rs

Temporarily we are excluding the retry policy, backoff policy, polling
error policy, and polling backoff policy functions from the public
APIs. That will make it easier to evolve these APIs as we finalize the
design for the client libraries.
Part of the work for #2237

docs(gax)!: hide policy functions

---

generator/internal/rust/codec.go
generator/internal/rust/codec_test.go

Part of the work for #2232 
Introduce a way to override a service's name.
This is implemented as a map, based on the feedback from https://github.com/googleapis/google-cloud-rust/pull/2238#discussion_r2098047270, in case there are multiple services.

impl(generator/rust): service name overrides

---

generator/internal/rust/annotate.go
generator/internal/rust/annotate_test.go

Part of the work for #2232 
Actually use service name overrides to modify the rust annotations for services and methods.
testing nit: only compare fields we care about, so it is dead obvious what is under test.
I should have included this in #2242, I just missed my local changes to `annotate.go`.

impl(generator/rust): use service name overrides

---

src/storage/src/client.rs

The retention configuration is unused in the v2 library.
Fixes #2039

impl(storage): add retention field to v1::Object

---

src/auth/src/credentials/internal/sts_exchange.rs

Token exchange calls doesn't require authentication. From [RFC8693 Request section](https://datatracker.ietf.org/doc/html/rfc8693#Request):
```
The supported methods of client authentication and whether or not to allow unauthenticated or unidentified clients are deployment decisions that are at the discretion of the authorization server. [...] Thus, client authentication allows for additional authorization checks by the STS as to which entities are permitted to impersonate or receive delegations from other entities.
```
-  Example on GCP auth documentation page shows example without any auth header: https://cloud.google.com/iam/docs/workforce-obtaining-short-lived-credentials#use_the_rest_api

fix(auth): allow token exchange without auth info

---

src/storage-control/src/client.rs
src/storage-control/src/lib.rs

Rename the builder module to be consistent with code generated off of `storage/control/v2`.

cleanup(storage-control): rename builder module

---

src/integration-tests/src/storage.rs
src/integration-tests/tests/driver.rs
src/storage-control/src/client.rs
src/storage-control/src/stub.rs
src/storage-control/tests/mocking.rs

Rename the client to be consistent with code generated off of `storage/control/v2`.

cleanup(storage-control): rename client

---

generator/internal/rust/templates/crate/src/builder.rs.mustache
src/storage-control/src/generated/gapic/builder.rs
src/storage-control/src/generated/gapic_control/builder.rs

Fixes #2232 
I sent a fix upstream for `[here]`.  We will have to wait until that is published to remove the `#[allow(...)]` in `lib.rs`.
Note that we also need to fill out the client surface for some of the other links to work. I am sending PRs to do that.

docs(storage-control): links for builders

---

src/storage-control/src/client.rs

Fixes #1813 
Similar to #2248, but for the storage v2 (admin) surface.
@coryan - can you review whether we want the new APIs in the surface? I suspect we do not want `rewrite_object` (the C++ implementation is involved) and I am also not sure about `compose_object`.

feat(storage-control): storage v2 API surface

---

README.md

docs: fix typos in README document

---

src/lro/tests/fake/responses.rs
src/lro/tests/integration.rs

The test were simulating errors incorrectly. Instead of returning a
`google.rpc.Status` in the right message field, it was always failing
to decode an any and returning the decoding error. The new tests are
more specific and verify the status is received.
Motivated by #2221

test(lro): fix error simulation

---

src/gax/src/backoff_policy.rs
src/gax/src/client_builder.rs
src/gax/src/exponential_backoff.rs
src/gax/src/polling_backoff_policy.rs
src/gax/src/retry_throttler.rs
src/integration-tests/src/storage.rs
src/integration-tests/src/workflows.rs

We should use different error types for policy creation problems vs.
RPC problems.
Fixes #2283

cleanup(gax)!: split policy error types

---

.github/workflows/sdk.yaml
.tarpaulin.toml
doc/contributor/howto-guide-set-up-development-environment.md

Introduce a `.tarpaulin.toml` config file, as it is sufficiently complicated. https://github.com/xd009642/tarpaulin?tab=readme-ov-file#config-file
Exclude generated files from the coverage generation step, instead of the report step. This seems to save some time.
Start reporting coverage for `storage`, `storage-control`.
From running locally, `cargo tarpaulin` still seemed to pick up packages like `integration-tests`, so I will continue to ignore these manually in the reporting step (`.codecov.yml`).

ci: more, simpler, faster code coverage

---

src/auth/src/credentials.rs
src/auth/src/credentials/internal/sts_exchange.rs
src/auth/src/credentials/mds.rs
src/auth/src/credentials/service_account.rs
src/auth/src/credentials/user_account.rs
src/auth/src/errors.rs
src/auth/src/headers_util.rs
src/auth/src/token_cache.rs
src/auth/tests/crypto_provider.rs
src/gax-internal/tests/grpc_auth.rs
src/gax-internal/tests/http_auth.rs
src/gax/src/error.rs
src/gax/src/error/credentials.rs
src/gax/src/retry_policy.rs

Used this opportunity to rename `is_retryable()` to `is_transient()`.
Whether the error is retryable depends on what you are trying to do with
the result.
Support having a message with a source error, this is useful in the MDS
case where we get an error and we want to add some troubleshooting
information.
Preserve the error source from HTTP operations and rustls crypto
operations.
Fixes #2287

cleanup(gax)!: hide `CredentialsError` details

---

src/auth/src/credentials/internal/sts_exchange.rs

Also removed `RefreshAccessTokenRequest` as it's unused and leftover from previous PR. 
Towards https://github.com/googleapis/google-cloud-rust/issues/2079

cleanup(auth): scope is optional on TokenResponse

---

src/auth/src/credentials.rs
src/auth/src/credentials/api_key_credentials.rs
src/auth/src/lib.rs
src/auth/src/token.rs

The module had no public APIs, there is no sense in documenting and making it
part of the public API.
I also fixed some documentation nits along the way.

cleanup(auth): hide `token` module

---

generator/internal/rust/templates/grpc-client/transport.rs.mustache
src/firestore/src/generated/gapic/transport.rs
src/gax-internal/src/grpc.rs
src/gax-internal/src/http.rs
src/gax/src/error/core_error.rs
src/gax/src/error/rpc.rs
src/lro/src/details.rs
src/storage-control/src/generated/gapic/transport.rs
src/storage-control/src/generated/gapic_control/transport.rs

I think we want to distinguish between serialization problems (as these
are most likely caused by the application), and deserialization problems
(as these are most likely problems with the client libraries). They also
have different semantics: the former cannot result in outgoing RPCs,
the latter only happen after an RPC completed.
part of the work for #2312

feat: new error kind for deserialization

---

src/wkt/src/internal.rs
src/wkt/src/internal/int32.rs
src/wkt/tests/message_with_i32.rs

ProtoJSON requires accepting both strings and integers for integers. This PR
only adds support for signed 32-bit integers. Future PRs will deal with
unsigned integers and with 64-bit integers.
The changes to the generator and the generated code will also happen in
separate PRs.
Fixes #2323

impl(wkt): helper type for `i32` deserialization

---

src/gax/src/retry_loop_internal.rs

Fixes #2307 
Cut off the retry loop if we were going to sleep past the overall timeout.
Now that we refactored the retry loop, the two test cases funnel into the same code path. It doesn't hurt to have both tests in case we ever refactor the thing again.

fix(gax): do not sleep past overall timeout

---

Cargo.lock
Cargo.toml
src/wkt/Cargo.toml
src/wkt/src/any.rs

To pass the ProtoJSON conformance test we need to reject some invalid
values in the `@type` field.
Fixes #2326

impl(wkt): better validation for `Any`

---

src/gax/src/error/core_error.rs

cleanup(gax): remove `Error::serde`

---

src/integration-tests/src/storage.rs
src/storage/src/client.rs

Improve the documentation for the functions and rename them to use the "with" style that we use for builders. 
This also cleans up the remaining TODO, since there are no parameters that apply for softDeleted, projection and restoreToken. softDeleted only applies without alt=media, restoreToken only applies for softDeleted objects, and projection just changes the values that are returned, and we only return the bytes to the user anyway.
Fixes #2103

cleanup(storage)!: rename set functions to use "with" style

---

src/storage/src/client.rs

This is more specific than `Error::other()`, and sufficiently consistent
with other uses of `Error::binding()`.
Part of the work for #2312

impl(storage): prefer `Error::binding()`

---

src/wkt/tests/generated/mod.rs
src/wkt/tests/generated/recursive_types.proto
src/wkt/tests/message_with_recursion.rs

Messages can "recurse", with fields that refer back to the same message,
maybe indirectly. The mapping for these is different: we box such
messages and they need different testing.

test(wkt): add test for messages with recursion

---

src/auth/src/credentials/external_account.rs
src/auth/src/credentials/external_account_sources/url_sourced.rs

Previously, `ExternalAccountConfig` and `CredentialSource` were being used to mirror the external account file format and also for internal configuration usage. But this introduces challenges to have pre-computed and/or cache values, so it's better to treat them as separated structs. 
This PR introduces `ExternalAccountFile` and `CredentialSourceFile` to represent the [AIP-4117 file](https://google.aip.dev/auth/4117#configuration-file-generation-and-usage), with `ExternalAccountConfig` and `CredentialSource` being the internal configuration used across implementations.

cleanup(auth): separate ExternalAccountFile from internal configuration

---

src/auth/src/credentials/external_account.rs
src/auth/src/credentials/external_account_sources/executable_sourced.rs

Executable sourced credential was not being detected because of the enum order. Changed and added test to check that.

fix(auth): exec source cred not being detected properly

---

src/gax/src/retry_loop_internal.rs

cleanup(gax): prefer `Error::exhausted`

---

src/storage/src/client.rs

cleanup(storage): prefer `Error::ser`

---

generator/internal/rust/templates/common/deser_plain_message_field.mustache
generator/internal/rust/templates/common/deser_with_message_field.mustache
src/wkt/tests/common/src/generated/mod.rs
src/wkt/tests/complex_oneofs.rs
src/wkt/tests/message_with_bool.rs
src/wkt/tests/message_with_bytes.rs
src/wkt/tests/message_with_enum.rs
src/wkt/tests/message_with_f32.rs
src/wkt/tests/message_with_f64.rs
src/wkt/tests/message_with_field_mask.rs
src/wkt/tests/message_with_i32.rs
src/wkt/tests/message_with_i64.rs
src/wkt/tests/message_with_null_value.rs
src/wkt/tests/message_with_recursion.rs
src/wkt/tests/message_with_string.rs
src/wkt/tests/message_with_u32.rs
src/wkt/tests/message_with_u64.rs
src/wkt/tests/message_with_value.rs
src/wkt/tests/message_with_wrappers.rs
src/wkt/tests/oneofs.rs

For most types, `null` deserializes as the default value. For optional fields
that is `None`. The exception are `wkt::NullValue` and `wkt::Value`.

impl(generator): deserialize `null` as default

---

src/auth/src/credentials.rs
src/auth/src/credentials/impersonated.rs
src/auth/tests/credentials.rs

Introduces the impersonated creds.
Refer to https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/generateAccessToken for the API call we are making for getting the impersonated token.

feat(auth): Impersonated Service Account Credentials

---

.github/workflows/sdk.yaml
generator/internal/api/model.go
generator/internal/rust/templates/common/deser_field_tag.mustache
generator/internal/rust/templates/common/message.mustache
src/protojson-conformance/Cargo.toml
src/protojson-conformance/README.md
src/protojson-conformance/expected_failures.txt
src/protojson-conformance/src/generated/test_protos/.sidekick.toml
src/protojson-conformance/src/generated/test_protos/mod.rs

Part of the work for #2376, fixes #2328
We generate more code, but since there are fewer `#[derive(...)]` attributes the total code is smaller:
```
cargo expand -p protojson-conformance --lib generated::test_protos > expand-pos-pr21.rs
wc -l expand-p*
11334 expand-pos-pr21.rs
21773 expand-pre-pr21.rs
33107 total
```

test: use generated serde for protojson conformance

---

src/generated/cloud/workflows/v1/.sidekick.toml
src/generated/cloud/workflows/v1/src/model.rs

impl(workflows/v1): use generated `serde`

---

src/generated/cloud/aiplatform/v1/.sidekick.toml

impl(aiplatform/v1): use generated `serde`

---

generator/internal/rust/templates/common/message.mustache
src/generated/openapi-validation/.sidekick.toml
src/generated/openapi-validation/src/model.rs

We need to skip synthetic fields during serialization, otherwise the
service rejects the (unknown) fields.

impl(openapi-validation): use generated `serde`

---

generator/internal/api/documentation.go
generator/internal/api/documentation_test.go
generator/internal/config/config.go
generator/internal/config/config_test.go
generator/internal/sidekick/refresh.go
src/generated/cloud/dialogflow/v2/.sidekick.toml
src/generated/cloud/dialogflow/v2/src/model.rs

From time to time we may need to patch the documentation for a service,
method, message, field, enum, or enum value. This new configuration
option provides the necessary functionality.

impl(generator): support documentation overrides

---

src/generated/cloud/orgpolicy/v1/.sidekick.toml
src/generated/cloud/orgpolicy/v1/src/model.rs

impl(orgpolicy/v1): use generated `serde`

---

src/generated/api/servicecontrol/v2/.sidekick.toml
src/generated/api/servicecontrol/v2/src/model.rs

impl(servicecontrol/v2): use generated `serde`

---

src/wkt/src/any.rs
src/wkt/src/duration.rs
src/wkt/src/field_mask.rs
src/wkt/src/rstruct.rs
src/wkt/src/timestamp.rs

We do not want to advertise these too much. We need them to serialize
the messages over HTTP+JSON. We do not want to commit to supporting
these nor do we want to guarantee they work over any serde serialization
format.

docs(wkt): hide `serde` trait implementations

---

src/integration-tests/tests/idempotency.rs
src/integration-tests/tests/requests.rs

These are invalid resource names. When we start validating bindings, the tests will fail. So avoid that.

cleanup: avoid binding errors in tests

---

generator/internal/api/model.go
generator/internal/dart/dart.go
generator/internal/golang/golang.go
generator/internal/language/codec.go
generator/internal/parser/httprule/http_rule_parser.go
generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/parser/protobuf_annotations.go
generator/internal/parser/protobuf_mixin_test.go
generator/internal/parser/protobuf_test.go
generator/internal/rust/annotate_test.go
generator/internal/rust/codec.go
generator/internal/rust/codec_test.go
generator/internal/sample/api.go

Part of the work for #2317, #557
I want the name `api.PathSegment` for myself. So make room for it, by giving the current representation a disparaging `Legacy*` prefix.
There are too many changes to swap out the representation for path segments in place. Both will have to exist while we build out the new implementation.

refactor(generator): make way for a new `PathSegment` representation

---

src/gax-internal/tests/http_client_polling.rs
src/gax/src/lib.rs
src/gax/src/polling_error_policy.rs
src/gax/src/retry_loop_internal.rs
src/gax/src/retry_policy.rs
src/gax/src/retry_result.rs
src/gax/src/retry_throttler.rs
src/gax/src/throttle_result.rs
src/gax/tests/retry_policy.rs
src/integration-tests/tests/idempotency.rs
src/lro/src/details.rs

The name did not reflect its function, and it is more jarring now that
we have `ThrottleResult`.

refactor!: rename `gax::loop_state::LoopState`

---

guide/src/setting_up_your_development_environment.md

Add a call out in the dev setup guide noting that you have to enable the Secret Manager API.

docs: more prerequisites to set up development environment

---

generator/internal/dart/dart_test.go
generator/internal/language/codec_test.go
generator/internal/parser/openapi_test.go
generator/internal/sample/api.go

Noticed while working on #2317 
We had the wrong hardcoded expectations, leading to weirdness. This is the spec for `CreateSecret`:
https://github.com/googleapis/google-cloud-rust/blob/97ff8eb0b68ff39c89c024b43d6e9b7001dae048/generator/testdata/openapi/secretmanager_openapi_v1.json#L223
https://github.com/googleapis/google-cloud-rust/blob/97ff8eb0b68ff39c89c024b43d6e9b7001dae048/generator/testdata/openapi/secretmanager_openapi_v1.json#L316-L334

cleanup(generator): correct sample API

---

generator/internal/api/model.go
generator/internal/parser/openapi.go
generator/internal/parser/openapi_test.go
generator/internal/sample/api.go

Add `PathTemplate` to the model. We only use it in OpenAPI to start (just to keep the PRs manageable).
TIL: `go fmt` will preserve linebreaks if the line ends with a `.`, but not if the line starts with a `.`

impl(generator): use `PathTemplate` in model, OpenAPI

---

generator/internal/parser/protobuf_annotations.go
generator/internal/parser/protobuf_mixin_test.go
generator/internal/parser/protobuf_test.go

Part of the work for #2317
Store the full `api.PathTemplate` when parsing protobuf.
Note that with protobuf, `PathTemplate` holds extra information (the variable templates) which `LegacyPathTemplate` does not.

impl(generator): `PathTemplate` from protobuf

---

generator/internal/rust/annotate.go
generator/internal/rust/codec.go
generator/internal/rust/codec_test.go

Part of the work for #2499
use `api.PathTemplate` to produce the path fmt string.
Looking ahead, this `PathFmt` will be used as an annotation on a `PathBinding` (so we have one path per binding, instead of one path per method).

refactor(generator/rust): PathFmt from `PathTemplate`

---

generator/internal/api/model.go
generator/internal/rust/annotate.go
generator/internal/rust/annotate_test.go

Part of the work for #2317
Introduce an annotation for `api.PathBinding` in Rust.
`annotatePathBinding` will grow to include the variable substitutions we need for path matching. But it is better to start small.
I am definitely open to suggestions on how to test this stuff. I settled for just defining a new service with N bindings, which should cover the cases we need to complete #2317. And if I missed something, we will just add the (N+1)th binding. The `want_*`s should grow as `annotatePathBinding` grows.

impl(generator/rust): annotations for `PathBindings`

---

src/gax-internal/src/path_parameter.rs

Fixes #2497, part of the work for #2317
Basically a refactor.
As @coryan suggested, introduce a trait to unify the strings vs. non-string path fields.
Now we treat them differently from within gaxi, instead of keeping track of which fields are strings in the model, and in the gaxi interface. This is cleaner.

cleanup(gaxi): trait for working with path fields

---

src/gax/src/polling_error_policy.rs
src/lro/src/details.rs

Resolves the remaining half of #2335.
The other half was fixed in #2456 (`RetryPolicy::on_throttle()`)
cc: @dbolduc

cleanup(gax): idiomatic return type for `PollingErrorPolicy::on_in_progress()`

---

generator/internal/rust/annotate.go
src/storage-control/src/generated/gapic/transport.rs
src/storage-control/src/generated/gapic_control/transport.rs

Related to #2317 (I am going to reuse this code)
If we had an optional string in the leaf, this would return an `Option<&String>`. We want it to return an `Option<&str>`.
This doesn't happen in practice so far. This PR will just make us feel better about the future.

impl(generator/rust): fix accessor for optional string leaf

---

guide/src/setting_up_your_development_environment.md

Made a few nitty copy edits to the setup guide, and added guidance on creating a secret in Secret Manager.

docs: minor fixes to setup guide

---

Cargo.lock
src/gax/src/error/binding.rs
src/integration-tests/Cargo.toml
src/integration-tests/tests/bindings.rs

Part of the work for #2317
Add unit tests for the additional binding logic. This is what our generated code will look like.
`gapic-showcase` does not give us enough coverage, so these tests are necessary. Note also that we can set strict expectations if we own the service definition. (We are not at the mercy of a service adding more bindings).
---
Related to #2523 - If you are curious how the binding code was generated, see:
https://github.com/dbolduc/google-cloud-rust/commit/007bc88771772eddb3b2b41b77f5f05feeaae571

test: additional bindings

---

generator/internal/rust/annotate.go
generator/internal/rust/templates/crate/src/transport.rs.mustache
src/generated/showcase/src/transport.rs
src/integration-tests/src/showcase/compliance.rs

Add the mustache template needed to support additional bindings for Rust.
Enable this for gapic-showcase, with tests that it works.
I prefer to hardcode the `AdditionalBindings` flag, instead of plumbing a sidekick feature. The flag should have a lifetime of <1 day.

impl(generator/rust): additional bindings in showcase

---

generator/internal/rust/annotate.go
src/generated/cloud/secretmanager/v1/src/transport.rs
src/generated/cloud/sql/v1/src/transport.rs
src/generated/cloud/workflows/executions/v1/src/transport.rs
src/generated/cloud/workflows/v1/src/transport.rs
src/generated/openapi-validation/src/transport.rs

Part of the work for #2316, #2317
Support additional bindings / binding validation for services used in our integration tests.
If the 300-character-wide golang line bothers you, note that it will be removed in the next PR, where I plan to turn this on for all services.

feat: binding validation in some services

---

guide/samples/src/binding_errors.rs
guide/samples/src/lib.rs
guide/samples/src/pagination.rs
guide/samples/tests/driver.rs
guide/src/SUMMARY.md
guide/src/binding_errors.md
src/gax/src/error/binding.rs

Fixes #2317  (there are some cleanups we should do, but this closes out everything that is public-facing).
Add a user guide section on handling binding errors. My main goal is to explain what is a `*`.
It renders like this: [ug_binding_errors.pdf](https://github.com/user-attachments/files/20953752/ug_binding_errors.pdf)

docs: explain binding errors

---

Cargo.lock
src/storage/Cargo.toml
src/storage/src/lib.rs
src/storage/src/upload_source.rs

We want to upload arbitrarily long (up to the GCS limits, 5TiB) objects.
This introduces a trait and a number of implementations to represent
sources of upload data. These sources represent a stream of data, and
support rewinding the stream. That will make the uploads more efficient
for things like files or objects returned from other storage systems.
Part of the work for #2042

impl(storage): implement source for uploads

---

generator/internal/rust/annotate.go
generator/internal/rust/templates/grpc-client/routinginfo.mustache
src/storage-control/src/generated/gapic/transport.rs
src/storage-control/src/generated/gapic_control/transport.rs

I prefer to have a simpler template, but that is just me. If @coryan disagrees, I am happy to just close this PR. The difference is miniscule.
FWIW, the HTTP path computation also uses the `None.or_else(...).or_else(...)...` set up.
https://github.com/googleapis/google-cloud-rust/blob/7b40638a34e5c2ce0f3b359c563a1aa9e5bd76fe/generator/internal/rust/templates/crate/src/transport.rs.mustache#L77-L79

cleanup: simpler routing info template

---

src/integration-tests/src/storage.rs
src/integration-tests/tests/driver.rs

Make the test more realistic and use a larger object. Chose a size that returned 4 chunks when running the integration tests locally.
While it would be easier to create a `const CONTENTS: &[u8] = &[5_u8; TOTAL_BYTES]`, it would be harder to verify that the data actually matched, since downloading the first chunk repeatedly would yield the same result.

test(storage): use a larger file for chunking read

---

generator/internal/api/model.go
generator/internal/parser/httprule/http_rule_parser.go
generator/internal/parser/routing_info.go
generator/internal/rust/annotate.go

Related to #557 
Just represent a variable subsegment as a string, instead of a strongly typed variant. e.g. `{"projects", "*"}`
This is what we do with explicit routing, might as well be consistent. The code is a littler simpler too. There is just less structure in the model.

cleanup(generator): weaker typed variable subsegments

---

generator/go.mod
generator/internal/gcloud/gcloud.go
generator/internal/gcloud/gcloud_test.go
generator/internal/gcloud/testdata/parallelstore/gcloud.yaml

Introduce Go structs for parsing a sample gcloud config YAML file. This is a first step to evaluate if we can use sidekick for automating gcloud command generation.

feat(internal/gcloud): add structs for gcloud config YAML

---

src/auth/src/credentials/external_account.rs

This change introduces the ability to use service account impersonation with external account credentials that are created using the ProgrammaticBuilder.
Previously, the ProgrammaticBuilder was missing a method to specify the service_account_impersonation_url, which prevented its use in scenarios requiring service account impersonation.
This commit addresses the limitation by:
- Adding the with_service_account_impersonation_url method to the ProgrammaticBuilder.
- Adding a comprehensive unit test to verify that the end-to-end impersonation flow is working correctly when configured through the ProgrammaticBuilder.

feat(auth): Enable impersonation in ProgrammaticBuilder

---

doc/contributor/howto-guide-generated-code-maintenance.md

Follow up to #2570, `typos` is no longer an error case when generating a new library.

cleanup: no typos when "onboarding"

---

src/integration-tests/src/storage.rs
src/storage/src/client.rs

Make the method signature more similar to futures::StreamExt. It is simple to convert between the two with `transpose()` so this will not greatly affect the usability of the API. We can also consider adding a try_next helper to return a Result<Option<Bytes>> as well.

feat(storage)!: change return type for next()

---

Cargo.lock
src/gax-internal/src/http.rs
src/integration-tests/src/storage.rs
src/storage/Cargo.toml
src/storage/src/client.rs
src/storage/src/upload_source.rs

Consume bytes as well as streaming types into `insert_object()`.
Fixes #2042

impl(storage): `insert_object()` streaming support

---

generator/internal/rust/annotate_test.go
generator/internal/rust/codec.go
generator/internal/rust/codec_test.go
generator/internal/rust/used_by_test.go
generator/internal/sidekick/cmdline_test.go
generator/internal/sidekick/sidekick_rust_prost_convert_test.go
generator/internal/sidekick/sidekick_test.go

Noticed while doing #439 
We define all of our dependent packages in the top-level `Cargo.toml` (including our own common crates).
In generated crates, we can just reference `foo.workspace = true` to pick up these crates.
We don't need to support `path` / `version` / `defaultFeatures` via the codec. They don't factor into the generated code:
https://github.com/googleapis/google-cloud-rust/blob/040c93c395529cf1aaf8d8b4a09ed7ed353922a1/generator/internal/rust/codec.go#L1344-L1350

cleanup(generator/rust): pare package codec

---

.sidekick.toml
Cargo.lock
Cargo.toml
generator/internal/rust/codec.go
generator/internal/rust/used_by_test.go
src/generated/showcase/Cargo.toml
src/generated/showcase/src/model.rs

Part of the work for #439 
Take a dependency on `uuid` if a crate has an RPC with an auto-populated field.
At the moment, the only service with auto-populated fields has a handwritten `Cargo.toml`. Still, it doesn't hurt to put this piece in place for later.

impl(generator/rust): uuid dep if auto-population

---

src/storage/src/client.rs
src/storage/src/upload_source.rs

Separate the `Seek` trait so we can create functions that only require
`StreamingSource`.

refactor(storage): rename upload source traits

---

src/auth/src/credentials/external_account.rs

As a follow up on https://github.com/googleapis/google-cloud-rust/pull/2541 I added another unit test in programmatic sourced credentials and remove the extra braces in the credential sources

cleanup(auth): add test for programmatic credential

---

src/storage/src/client.rs
src/storage/src/client/upload_object_buffered.rs

When the payload does not support `Seek` we need to use resumable
uploads, buffer any uncommitted data, and periodically flush the buffer.
This PR introduces the basic skeleton to support such uploads.

impl(storage): scaffold for buffered uploads

---

generator/internal/api/dependencies.go
generator/internal/api/dependencies_test.go

Part of the work for #2397 
Add support for finding dependencies of given IDs.
Conceptually, it is more complicated than finding the transitive closure of a graph. (I think it is finding the transitive closure of two different graphs). Hopefully the write up makes sense.
I know about `FindServiceDependencies`. In a follow up, I will [refactor it to use this](https://github.com/dbolduc/google-cloud-rust/commit/4b9700508aef98901e86aa711db16ad310bfc97e).

impl(sidekick): find any dependencies

---

src/auth/src/credentials/api_key_credentials.rs

According to AIP-4110 (https://google.aip.dev/auth/4110), the GOOGLE_CLOUD_QUOTA_PROJECT environment variable is intended to be used exclusively by the Application Default Credentials (ADC) flow. 
Therefore, this change removes support for the GOOGLE_CLOUD_QUOTA_PROJECT environment variable from the api_key_credentials builder. This is a breaking change intended to align our library with official Google Cloud standards and improve behavioral consistency.

refactor(auth)!: remove quota project env var from api_key

---

src/integration-tests/src/storage.rs
src/integration-tests/tests/driver.rs
src/storage/src/client/upload_object_buffered.rs

Split "large" uploads in multiple PUT calls, checkpointing each PUT will allow
us to resume the upload with a limited buffer.

impl(storage): checkpoint buffered uploads

---

src/integration-tests/src/storage.rs
src/storage/src/client.rs
src/storage/src/client/upload_object.rs
src/storage/src/client/upload_object/unbuffered.rs

Use a single method in the `Storage` client to upload objects. Then
implement two different methods in the request builder:
- `send()` uses buffered uploads, probably the most common case.
- `send_unbuffered()` skips any local buffering.

refactor(storage): consolidate upload methods

---

Cargo.lock
src/auth/Cargo.toml
src/auth/build.rs
src/auth/src/credentials/impersonated.rs
src/auth/src/headers_util.rs

Metrics headers from auth and client libraries are sent through `x-goog-api-client` header. These headers are used for auth requests to get token as well as while using the auth tokens and making an API call.
This PR focuses on the headers for the auth requests only.
There will be future PRs for auth request headers for other cred types and for token usage through grpc and http requests.

fix(auth): Implement framework for Auth Request metric headers and use in impersonated creds

---

src/storage/src/client.rs
src/storage/src/client/upload_object.rs

When creating a new resumable upload session we should retry in case of
transient failures.
Part of the work for #2057

impl(storage): retry resumable sessions

---

src/gax/src/error/rpc.rs
src/integration-tests/src/showcase/echo.rs
src/integration-tests/src/workflows.rs
src/lro/src/details.rs

Fixes #2440 
Implements `impl From<&rpc::model::Status> for Status` to avoid cloning before converting

chore: improve deserde of errors from Status

---

generator/internal/rust/annotate.go
generator/internal/rust/annotate_test.go
generator/internal/rust/codec.go
generator/internal/rust/templates/common/message.mustache
src/storage/src/control.rs
src/storage/src/control/generated/gapic/.sidekick.toml
src/storage/src/control/generated/gapic/model.rs
src/storage/src/lib.rs

Fixes #2403 
Hides `ReadObjectRequest`, `WriteObjectSpec` from the public API.
Note that if we enumerated the types we want to expose from `storage/v2`, we would have to manually maintain that list.
If we exclude the two types via the codec, we are not broken if existing `storage/v2` requests gain new message fields.
---
I might still move things around internally, but the public API is stable, and what we want. [meme](https://cdn-useast1.kapwing.com/static/templates/homer-simpsons-back-fat-meme-template-thumbnail-9f5dc0bb.webp)

cleanup(storage): hide generated implementation details

---

src/storage/src/storage.rs
src/storage/src/storage/client.rs
src/storage/src/storage/request_options.rs
src/storage/src/storage/upload_object.rs
src/storage/src/storage/upload_object/unbuffered.rs

The first set of options are only used in uploads, my plan is to use the
same type for downloads, uploads, and to keep the client options.
Part of the work for #2056 and #2057

impl(storage): per-request options

---

src/storage/src/storage/upload_object.rs
src/storage/src/storage/upload_object/unbuffered.rs

Change `UploadObject` to use the `self.spec.resource` field to keep
object metadata information. This will make it easier to write the
idempotency policies.
Part of the changes for #2056

impl(storage): only use `WriteObjectSpec`

---

src/gax-internal/src/grpc/from_status.rs
src/gax-internal/src/grpc/status.rs
src/integration-tests/src/error_details.rs
src/integration-tests/tests/driver.rs

Fixes #1699 
Captures error details from tonic, and surfaces them in our `gax::error::rpc::Status`.
gRPC is weird. They send the code in `grpc-status`, and the message in `grpc-message`, and then they also encode a full `google.rpc.Status` proto (which has a `code` and `message` field) in `grpc-status-details-bin`. Seems redundant to me. I will just assume they are always the same :shrug:. If they aren't the non-binary headers will win.
https://docs.rs/tonic/0.13.1/src/tonic/status.rs.html#442-457
Added an integration test, to confirm the weirdness.

feat: full error details over gRPC

---

src/auth/src/credentials/user_account.rs

This PR introduces the ability for users to configure custom retry, backoff, and throttling policies for the user account credentials.

feat(auth): Allow custom retry policy for user

---

doc/contributor/howto-guide-generated-code-maintenance.md

Script more steps on the googleapis SHA updates. Move rarely used steps
to a section at the bottom.

docs: update maintenance guide

---

doc/contributor/howto-guide-set-up-development-environment.md

With older versions of rust, there end up being lint errors that are no longer relevant. Add a hint for devs if they encounter this problem.

docs: add hint in how to guide for lint errors

---

Cargo.lock
Cargo.toml
src/auth/Cargo.toml

We want to test all the versions in a `*-rc1` release because too many
versions changed manually.

chore(auth): temporarily use `-rc1` version

---

src/auth/src/credentials/mds.rs
src/auth/src/credentials/user_account.rs
src/gax/src/client_builder.rs
src/storage/src/storage/client.rs
src/storage/src/storage/upload_object.rs

As a followup to https://github.com/googleapis/google-cloud-rust/pull/2659 simplify examples at the other places.

cleanup(auth/gax): simplify examples

---

src/lro/src/internal.rs
src/lro/src/lib.rs

Pin the stream so callers don't have to. Adding a trait is not a breaking change.

feat(lro): `into_stream()` is `Unpin`

---

src/wkt/src/message.rs
src/wkt/src/wrappers.rs

Related to #1609 
`rustc --version == 1.90` starts to flag this as an [E0446](https://doc.rust-lang.org/error_codes/E0446.html). See [a failed build](https://github.com/googleapis/google-cloud-rust/actions/runs/16347121498/job/46183704836?pr=2708) against 1.90.
We can make the trait public, but sealed. No downstream crates can implement it. It remains hidden from our docs, as it is an implementation detail.
This is not a breaking change, as the `MessageSerializer` trait was previously un-implementable outside of `wkt`.
Tested locally with: `cargo +nightly doc -p google-cloud-kms-v1`

fix(wkt): no private types in public traits

---

src/storage/src/storage/upload_source.rs

Previously Tokio files did not have a good size hint, and therefore
their upload was not as optimized as it could be.
Part of the work for #2641

impl(storage): better upload for tokio files

---

guide/src/configuring_retry_policies.md

Made a few minor tweaks to the retry guide:
* Changed "we" to "you".
* Added a brief summary of AIP-194.
* Fixed a couple of nitty typo/usage things.

docs: clarifications and fixes in retry guide

---

generator/internal/rust/codec.go
generator/internal/rust/codec_test.go
src/storage/src/generated/gapic/client.rs

Part of the work for #2398 
When we start using the generated client docs, the broken link to `Storage::restore_object` becomes public. We need to apply the service name overrides for doc links.
Aside: the name overrides could apply to more link types, (e.g. messages / fields / etc.) but we will add the support as needed.

impl: service name overrides in doc links

---

src/storage/src/storage/read_object.rs
src/storage/src/storage/read_object/resume_tests.rs
src/storage/src/storage/upload_object.rs

Weave the retry options into the `read_object()` builder, so we can at least
retry the initial request. Resuming interrupted downloads will come in a future PR.
Part of the work for #2048

impl(storage): `read_object()` retries at start

---

generator/internal/rust/annotate.go
generator/internal/rust/annotate_test.go
generator/internal/rust/codec.go

Part of the work for #2401 
Introduce a new codec option and plumb it where we will need it. (on a method annotation)

impl(generator/rust): plumb routing-required option

---

src/storage/src/download_resume_policy.rs
src/storage/src/lib.rs

We will need a way to configure what type of error we tolerate for resumes, and
how many errors we tolerate too.
Part of the work for #2048

impl(storage): introduce resume policies

---

guide/samples/tests/enums.rs

Avoid `unreachable!()` in code that may be reached, it is bad guidance,
even if it was not the main point of the example. Prefer returning an
error. Document cases where `unreachable!()` may be appropriate.
I also made some cosmetic changes to keep the examples from rendering
with a horizontal scroll bar.
Motivated by https://www.reddit.com/r/rust/comments/1luqn9l/comment/n25a19z

docs(user-guide): improve enum examples

---

src/integration-tests/src/storage.rs
src/integration-tests/tests/driver.rs

I was worried that the service would commit the data on aborted uploads.
Specially when the object size is not know, so a successful `PUT`
completes the upload. Everything worked well, yay!
Motivated by #2639

test(storage): aborted uploads integration tests

---

src/storage/src/download_resume_policy.rs
src/storage/src/storage/client.rs
src/storage/src/storage/read_object.rs
src/storage/src/storage/read_object/resume_tests.rs
src/storage/src/storage/request_options.rs

Add fluent setters for the download resume policies, and use the policy
to conditionally resume an interrupted download.
Fixes #2048

impl(storage): use download resume policies

---

generator/internal/api/model.go
generator/internal/api/model_test.go

Related to #2401 
I will use this in storage control to determine whether failures to extract the routing parameters belong in the same path (as in `precondition1 && precondition2`) or in separate paths (as in `precondition1 || precondition2`).
If you are curious, this is the full change: https://github.com/googleapis/google-cloud-rust/commit/023e970e029693911dc7538476eb0f4b53dbd899

impl(sidekick): new routing info grouping

---

src/storage/src/storage/upload_object.rs
src/storage/src/storage/upload_object/buffered.rs
src/storage/src/storage/upload_object/buffered/resumable_tests.rs
src/storage/src/storage/upload_object/unbuffered.rs

Make this type into a builder object, with the actual upload methods
moved to `PerformUpload`. This will be useful when we introduce a
`Checksum` field into the builder. It may also help me move the code
into smaller files.
Part of the work for #2050

refactor(storage): `UploadObject` is a builder

---

guide/samples/tests/storage/quickstart.rs
src/integration-tests/src/storage.rs
src/storage/src/storage/client.rs
src/storage/src/storage/read_object.rs
src/storage/src/storage/read_object/resume_tests.rs

The `all_bytes` method was added as a convenience function to be used with small object downloads. By providing this method, we were also making it easier for our users to incorrectly use our library. Downloading all of the data into memory is not desirable in many use cases for the storage API.
Since this method is implemented in terms of the `next()` function anyway, this does not actually remove any functionality from the API.

fix(storage)!: remove all_bytes method for storage downloads

---

src/integration-tests/src/storage.rs
src/integration-tests/tests/driver.rs
src/storage/src/storage/checksum.rs
src/storage/src/storage/perform_upload.rs
src/storage/src/storage/perform_upload/buffered.rs
src/storage/src/storage/perform_upload/tests.rs
src/storage/src/storage/perform_upload/tests/checksums.rs
src/storage/src/storage/perform_upload/unbuffered.rs
src/storage/src/storage/upload_object.rs

Compare the computed (or pre-computed) checksums against the values
received from the service. Returning an error if the values do not
match.
Part of the work for #2050

impl(storage): compare final checksums on upload

---

src/storage/src/storage.rs
src/storage/src/storage/client.rs
src/storage/src/storage/perform_upload/buffered/progress.rs
src/storage/src/storage/upload_object.rs
src/storage/src/storage/upload_source.rs

The original name was (partly) justified because the method was
`insert_object()`. The method is now `upload_object()`, and `upload` is
already part of the module name.
Part of the work for #2641

cleanup(storate): drop `Insert` from `InsertPayload`

---

Cargo.lock
Cargo.toml
guide/samples/Cargo.toml
guide/src/configuring_polling_policies.md
guide/src/configuring_retry_policies.md
guide/src/error_handling.md
guide/src/examine_error_details.md
guide/src/generate_text_using_the_vertex_ai_gemini_api.md
guide/src/initialize_a_client.md
guide/src/mock_a_client.md
guide/src/pagination.md
guide/src/storage.md
guide/src/storage/queue.md
guide/src/storage/rewrite_object.md
guide/src/storage/striped_downloads.md
guide/src/storage/terminate_uploads.md
guide/src/working_with_enums.md
guide/src/working_with_long_running_operations.md

This is much easier to maintain, and anybody following the guide would
get the latest (non-preview) version by default.  However, this is not
as robust, as the `cargo add` command is not tested. OTOH, the version
numbers in the published doc may be out of date too, so neither approach
is perfect.

cleanup(user-guide): prefer `cargo add`

---

src/integration-tests/src/storage.rs
src/storage/src/storage/read_object.rs

Add remaining fields for data that is returned as headers for object downloads.
Fixes #2626

feat(storage): add more fields to ObjectHighlights

---

src/storage/src/storage/checksum.rs
src/storage/src/storage/perform_upload.rs
src/storage/src/storage/perform_upload/buffered.rs
src/storage/src/storage/upload_object.rs

With this change we track whether the CRC32C checksum, the MD5 hash, or
both are set to known values. Once one of them is set to a known value,
the value cannot be changed: the corresponding `with_known_*()` function
is not available. It is also not possible to revert from known values
to computed values. The `compute_*()` functions are not available.
As a side effect: the CRC32C checksum is always present, either known
or computed. It cannot be removed from the upload.
Renamed the (crate private) types from `Precomputed` to `Known*`.

impl(storage): fine grained known checksum tracking

---

src/integration-tests/src/storage.rs
src/integration-tests/tests/driver.rs
src/storage/src/storage/perform_upload.rs
src/storage/src/storage/perform_upload/buffered.rs
src/storage/src/storage/perform_upload/unbuffered.rs

During uploads we were percent encoding the name of the objects twice.
Once manually, and another time because `.query()` automatically percent
encode things.
Consequently the names of the uploaded objects were all wrong (they were
the percent encoded names), and using the objects in `get_object()` or
`read_object()` or `list_objects()` became extremely difficult.

fix(storage): percent-encode name once on uploads

---

doc/contributor/howto-guide-set-up-development-environment.md
guide/src/error_handling.md

* Added instructions for formatting code examples to the contributor guide.
* Made a few nitty style fixes, including:
* Prefer present to future tense.
* Prefer "you" to "we".
* Added several links to the Secret Manager docs.
* Added cross links to several other guides.
* Added complete `update_secret` function to the start of "Handling the error." (It feels a little easier to follow the explanation if you can see the entire function first.)
* Added a "What's next" section.
* Added complete code for the helper functions, and linked to them.
* Made verbs match operations (*create* a secret vs. *add* a secret version).

docs: error handling full code + cleanups

---

src/storage/src/lib.rs
src/storage/src/storage.rs
src/storage/src/storage/checksum/details.rs
src/storage/src/storage/perform_upload/buffered.rs
src/storage/src/storage/read_object.rs

Use a single error type for both I/O and checksum problems in uploads.
Fixes #2828

cleanup(storage)!: merge upload errors

---

src/storage/src/lib.rs
src/storage/src/storage.rs
src/storage/src/storage/checksum.rs

Applications need this to use the `UploadObject` builder in generic
code.
Fixes #2826

impl(storage): make `ChecksumEngine` public

---

src/wkt/tests/common/src/generated/mod.rs
src/wkt/tests/complex_oneofs.rs
src/wkt/tests/protos/oneofs.proto

The tests used `int` instead of `int32` and `long` instead of `int64` to
workaround problems in name serialization for oneof fields. I fixed
the serialization problems, but neglected to update the tests.
See #2383 for more history.

test(wkt): natural names for `intXX` fields

---

src/auth/src/credentials/mds.rs

Fixes #2292 
The tests assumed there was no MDS present. They fail on a fresh GCE VM.
We fix this case by short circuiting the test if we get a valid token.
Then there is the Googler-only case of running on your Cloudtop, where the default SA doesn't work with the default scopes. In this case, fetching a token returns a `404` which is not transient.
We address this by making less assertions about the error contents.

cleanup(auth): unit test MDS assumptions

---

src/gax-internal/src/grpc.rs
src/gax-internal/tests/grpc_client_polling.rs

Part of the work for #2863 
Add ability to override polling error and polling backoff policies.
The implementation and tests are copied almost exactly from the HTTP client.

impl(gaxi): custom gRPC polling policies

---

.github/workflows/generator_dart.yaml
.github/workflows/sdk.yaml
src/storage/src/generated/gapic_control/transport.rs

fix(storage): heed custom polling policies

---

Cargo.lock
Cargo.toml
src/storage/Cargo.toml
src/storage/src/error.rs
src/storage/src/storage/perform_upload/buffered.rs
src/storage/src/storage/perform_upload/tests/checksums.rs

When uploading an object we return an error if the resulting object
checksums do not match the computed or expected checksums. We should
include the object metadata in the error, as the object was created.
Fixes #2855

feat(storage)!: return object on checksum mismatch

---

Cargo.lock
Cargo.toml
src/storage/Cargo.toml
src/storage/src/storage/perform_upload.rs
src/storage/src/storage/perform_upload/buffered.rs
src/storage/src/storage/perform_upload/unbuffered.rs

Only errors that come from the user should abort an upload. Other errors
are I/O errors and should allow the upload to continue (subject to the
retry or resume policies).
part of the work for #2811

fix(storage): fewer errors abort uploads

---

Cargo.lock
src/storage/examples/Cargo.toml
src/storage/examples/src/change_default_storage_class.rs
src/storage/examples/src/create_bucket.rs
src/storage/examples/src/create_bucket_class_location.rs
src/storage/examples/src/create_bucket_dual_region.rs
src/storage/examples/src/create_bucket_hierarchical_namespace.rs
src/storage/examples/src/delete_bucket.rs
src/storage/examples/src/get_bucket_metadata.rs
src/storage/examples/src/lib.rs
src/storage/examples/tests/integration.rs

docs(storage): more examples for buckets

---

src/storage/examples/src/control/quickstart.rs
src/storage/examples/src/lib.rs
src/storage/examples/src/quickstart.rs

docs(storage): quickstart examples

---

src/integration-tests/src/storage.rs
src/storage/examples/src/lib.rs
src/storage/src/error.rs
src/storage/src/lib.rs
src/storage/src/model.rs
src/storage/src/model/request_helpers.rs
src/storage/src/storage/client.rs
src/storage/src/storage/perform_upload/buffered/resumable_tests.rs
src/storage/src/storage/perform_upload/tests.rs
src/storage/src/storage/perform_upload/unbuffered.rs
src/storage/src/storage/perform_upload/unbuffered/resumable_tests.rs
src/storage/src/storage/read_object.rs
src/storage/src/storage/upload_object.rs

cleanup(storage)!: move `KeyAes256`

---

guide/samples/tests/storage/quickstart.rs
guide/samples/tests/storage/striped.rs
src/integration-tests/src/storage.rs
src/storage/examples/src/objects/stream_file_download.rs
src/storage/src/storage/client.rs
src/storage/src/storage/read_object.rs
src/storage/src/storage/read_object/resume_tests.rs
src/w1r3/src/main.rs

Fixes #2901, and helps with #2041 
Conflicts with #2907. @suzmue - I am happy to do this in either order. I had to introduce extra guarantees on the `C: ChecksumEngine` to make this work.... but none of that would be necessary if there was no `C` to begin with.

refactor(storage)!: Make `ReadObjectResponse` a trait

---

.github/workflows/sdk.yaml
Cargo.lock
Cargo.toml
src/auth/src/credentials/external_account_sources/executable_sourced.rs
src/auth/tests/credentials.rs

Generally I bumped the minimal version to whatever is current. In a couple of
places I just changed the code because it looked bad too. I also created a new
build to test these minimal versions.

fix: match code and minimal versions

---

src/storage/examples/src/define_bucket_website_configuration.rs
src/storage/examples/src/lib.rs
src/storage/examples/src/print_bucket_website_configuration.rs

docs(storage): website configuration examples

---

src/w1r3/src/main.rs

This can be useful to speed up the benchmark, at the cost of leaving
garbage files in the test bucket.

impl(w1r3): deletes can be disabled

---

src/storage/src/control/client.rs
src/storage/src/retry_policy.rs

These values are based on the experiment running one billion requests successfully.

feat(storage): better retry policy defaults

---

.github/workflows/generator_dart.yaml
.github/workflows/sdk.yaml
src/storage/src/generated/gapic_control/transport.rs

Fixes #3125. Basically we needed to fix `sidekick` and regenerate the code.

fix(storage): correct mixin service name

---

src/w1r3/src/main.rs

With this change, the benchmark uses the default retry policies unless
either (or both) of these are true:
- It is invoked with `--retry-timeout=...` to set the retry time limit.
- It is invoked with `--debug-retry` to log the retry attempts for
errors.
This is useful to test the client library with its defaults, but also
supports adding logging to troubleshoot failures.

feat(w1r3): use default retry policies

---

src/storage/examples/src/control/create_anywhere_cache.rs
src/storage/examples/src/control/disable_anywhere_cache.rs
src/storage/examples/src/control/get_anywhere_cache.rs
src/storage/examples/src/control/list_anywhere_caches.rs
src/storage/examples/src/control/pause_anywhere_cache.rs
src/storage/examples/src/control/resume_anywhere_cache.rs
src/storage/examples/src/control/update_anywhere_cache.rs
src/storage/examples/src/lib.rs
src/storage/examples/tests/integration.rs

These examples are disabled by default, they are too slow for CI. But we can
run them manually if something breaks.
Fixes #3035, fixes #3036, fixes #3037, fixes #3038, fixes #3039, fixes #3040, and fixes #3041

docs(storage): examples for anywhere cache

---

guide/samples/tests/storage/quickstart.rs
guide/samples/tests/storage/striped.rs
src/integration-tests/src/storage.rs
src/storage/examples/src/objects/download_byte_range.rs
src/storage/examples/src/objects/download_encrypted_file.rs
src/storage/examples/src/objects/stream_file_download.rs
src/storage/src/read_object.rs
src/storage/src/storage/client.rs
src/storage/src/storage/read_object.rs
src/storage/src/storage/read_object/resume_tests.rs
src/w1r3/src/main.rs

Part of the work for #2041, reverts #2931 
Restore `ReadObjectResponse` to be a concrete object.
Implement it using a pimpl pattern. This will let us inject a fake implementation when we need to mock it as a return type.

refactor(storage)!: `ReadObjectResponse` uses pimpl

---

guide/samples/src/pagination.rs
guide/src/SUMMARY.md
guide/src/pagination.md

* Updated "Prerequisites" to match other updated guides that use Secret Manager.
* Updated first example (iterating over items) to mention `ItemPaginator` and `by_item`. It looks like an older version of the guide showed `Paginator` and `items`, and the code got updated but not the text.
* Updated second example (iterating over pages) to show how to bring `Paginator` into scope and to mention `by_page`.
* Documented `use` statement for streaming example.
* Made various nitty style updates, including user "list" instead of "List", unless we're talking about the API operation.
* Add two "What's next" links.

docs(user-guide): improve list operations guide

---

src/auth/src/credentials/external_account.rs
src/auth/src/credentials/external_account_sources/file_sourced.rs
src/auth/src/credentials/external_account_sources/url_sourced.rs

Howdy folks, I came across https://github.com/googleapis/google-cloud-rust/issues/1342 and wanted to test, but wasn't able to get service account impersonation working; attempted patching it here. We've tested this works for us.
This pull request improves how external account credentials are parsed and handled, particularly for Kubernetes Workload Identity Federation (WIF) scenarios. The main focus is on making the `subject_token_field_name` optional, setting sensible defaults, and enhancing test coverage for Kubernetes identity configurations.
**Parsing and struct improvements:**
* Made the `subject_token_field_name` field in `CredentialSourceFormat` optional (`Option<String>`) to allow for configurations where it may be omitted.
* Updated construction logic in both …

fix: workload identity federation service account impersonation

---

src/storage/src/generated/gapic/.sidekick.toml
src/storage/src/generated/gapic/model.rs

These request types will factor into our mock interfaces. We need to make them public.

feat(storage): request types for mocking

---

src/storage/src/storage/perform_upload.rs
src/storage/src/storage/read_object.rs
src/storage/src/storage/request_options.rs
src/storage/src/storage/write_object.rs

Fold `Checksum` into `RequestOptions`. This means we do not need to include `Checksum` as a parameter in the stub signatures.
The `RequestOptions` could/should hold an enum representing the checksum config that only gets turned into an engine when the engine is actually needed. We can do that later.
Also while we are here, make all the fields of `RequestOptions` crate-private. This gives us leeway to change the types if we make `RequestOptions` public.

refactor(storage): Checksum as an option

---

src/gax-internal/src/unimplemented.rs
src/storage/src/model_ext.rs
src/storage/src/storage.rs
src/storage/src/storage/stub.rs

My plan is to
- put the stub in place
- introduce the `transport::Storage` stub and implement `read_object` with it
- implement `write_object` with the `transport::Storage` stub
- plumb the `transport::Storage` stub from the client to the builders
- replace the `transport::Storage` stub with a generic `T: crate::stub::Storage`
- add the `client::Storage::from_stub()` and mock tests. Make sure everything that needs to be public is public.
We could template the client and the builders with a placeholder earlier.

impl(storage): introduce stub interface

---

.gcb/builds/main.tf
.gcb/builds/resources/main.tf
.gcb/builds/services/main.tf

The integration tests for the storage examples will require a KMS crypto
key, which in turns lives in a KMS key ring. And we need the storage
service account to have access to the crypto key too.
part of the work for #3100 and #3101, #3098, #3097 and  probably several other examples.

ci: create KMS resources for integration tests

---

src/storage/src/storage.rs
src/storage/src/storage/read_object.rs
src/storage/src/storage/stub.rs
src/storage/src/storage/transport.rs

Introduce the `transport::Storage` stub, with an implementation for `read_object`.
Refactor `ReadObject` to write the implementation in terms of the `stub`, not the `inner`.
We start by naming the `transport::Storage` stub explicitly in `ReadObject`. Eventually it will get replaced by a `T: stub::Storage`, when we are ready.
`ReadObject` can't know about the `http_request_builder` any more. (That is only known by the specific transport stub implementation, which will eventually be a generic stub implementation). So in tests, we use the `ReadObject` builder to give us a request and options. We use those to construct something that knows about `http_request_builder`.

impl(storage): use stub for read_object

---

src/storage/src/storage/perform_upload/buffered.rs
src/storage/src/storage/perform_upload/buffered/resumable_tests.rs
src/storage/src/storage/perform_upload/tests.rs
src/storage/src/storage/perform_upload/unbuffered/single_shot_tests.rs
src/storage/src/storage/transport.rs
src/storage/src/storage/write_object.rs

Implement `WriteObject` using the `transport::Storage` stub.
Similarly to the `ReadObject` change, we had test helpers on the builder that would no longer have access to the real implementation details (the `StorageInner`, hidden in the transport stub). Again, we take the request and options from the builder, and combine it with an `inner` from outside the builder.

refactor(storage): use stub for write_object

---

src/storage/examples/src/buckets.rs
src/storage/examples/src/buckets/create_bucket_with_object_retention.rs
src/storage/examples/src/lib.rs

docs(storage): create bucket with object retention

---

src/storage/src/model_ext.rs
src/storage/src/storage/client.rs
src/storage/src/storage/read_object.rs
src/storage/src/storage/request_options.rs
src/storage/src/storage/write_object.rs

Template the `client::Storage` on the `stub::Storage` implementing it. I use `S` for `Stub`, and because no other generics used `S`. That kept the diff in check.
The default template is a `transport::Storage` in the client and the builders. This means code like: `let client: Storage = Storage::builder().build().await` keeps working as before.
The `builder()` method is only available on the "real" client. It only ever gives you a real client.
We need to make the default template type public, although it does not need to be name-able by applications.
The next PR will add the `client::Storage::from_stub()` method and make sure all types like `RequestOptions` are name-able outside of the crate.

refactor(storage): client is templated on stubs

---

src/storage/examples/src/lib.rs

We test folders in `run_managed_folders_example`, no need to do it in `run_object_examples`.

cleanup: remove extra sample run

---

src/wkt/src/timestamp.rs

It seems like time==0.3.42 has a regression in its Nanosecond -> Second
helpers. This workarounds that problem using a constant value to convert
from nanoseconds to seconds.
More details at: https://github.com/time-rs/time/issues/749
Unblocks #3193

impl(wkt): workaround for time==0.3.42

---

doc/rustdocfx/generate.go
doc/rustdocfx/workspace.go

This also fix:
- input arg types: primitive
- borrowed ref lifetime
Fixes: #3221

docs(rustdocfx): add function signature error checks

---

src/auth/src/credentials/api_key_credentials.rs
src/auth/src/headers_util.rs

API Key and Quota Project are not meant to be used together. I
When quota project is passed with an API Key, the error is asking to give IAM permissions for using the quota project but API Key is not a principal to assign IAM Permissions.
(It works if no quota project is passed or if quota project is passed with a user cred)
```
$ curl -X POST \
-H "Content-Type: application/json" \
-H "X-Goog-User-Project: <quota-project>" \
"https://translation.googleapis.com/language/translate/v2?key=<api key>" \
-d '{
"q": "Hello world!",
"target": "es"
}'
{
"error": {
"code": 403,
"message": "Caller does not have required permission to use project  <quota-project>. Grant the caller the roles/serviceusage.serviceUsageConsumer role, or a custom role with the serviceusage.services.use permission, by …
```

fix(auth)!: Remove support for quota project from API Key creds

---

src/auth/src/credentials.rs
src/auth/src/retry.rs
src/gax-internal/tests/grpc_timeout.rs
src/gax-internal/tests/http_timeout.rs
src/gax/src/backoff_policy.rs
src/gax/src/exponential_backoff.rs
src/gax/src/retry_loop_internal.rs
src/gax/tests/backoff_policy.rs
src/storage/src/backoff_policy.rs
src/storage/src/storage/client.rs

Use a struct as an argument so we can add fields to it without breaking
the trait definition.

cleanup(gax)!: future proof backoff policy

---

doc/rustdocfx/generate.go
doc/rustdocfx/main.go
doc/rustdocfx/render_metadata.go
doc/rustdocfx/render_metadata_test.go

Embedded templates make it easier to redistribute the binary, or use
it from outside its repository.
Fixes #3211

cleanup(rustdocfx): always use embedded templates

---

Cargo.lock
Cargo.toml
src/gax/Cargo.toml

Changing some traits to be future proof is a breaking change, we need
to bump the version.

chore(gax): bump version after future proofing

---

src/auth/src/credentials.rs
src/auth/tests/credentials.rs
src/gax-internal/tests/grpc_client_polling.rs
src/gax-internal/tests/grpc_retry_loop.rs
src/gax-internal/tests/grpc_simple_request.rs
src/gax-internal/tests/grpc_timeout.rs
src/gax-internal/tests/grpc_user_agent.rs
src/gax-internal/tests/http_client_errors.rs
src/gax-internal/tests/http_client_polling.rs
src/gax-internal/tests/http_metadata.rs
src/gax-internal/tests/http_retry_loop.rs
src/gax-internal/tests/http_timeout.rs
src/gax-internal/tests/http_user_agent.rs
src/integration-tests/src/showcase.rs
src/integration-tests/src/showcase/compliance.rs
src/integration-tests/src/showcase/echo.rs
src/integration-tests/src/showcase/identity.rs
src/integration-tests/tests/bindings.rs
src/integration-tests/tests/requests.rs
src/lro/tests/integration.rs
src/storage/src/control/client.rs
src/storage/src/storage/client.rs
src/storage/src/storage/perform_upload/buffered/resumable_tests.rs
src/storage/src/storage/perform_upload/buffered/single_shot_tests.rs
src/storage/src/storage/perform_upload/unbuffered/resumable_tests.rs
src/storage/src/storage/perform_upload/unbuffered/single_shot_tests.rs
src/storage/src/storage/read_object.rs
src/storage/src/storage/read_object/resume_tests.rs
src/storage/src/storage/write_object.rs
src/storage/tests/binding.rs

This is now redundant, `anonymous::Builder` can do the same thing.
This is non-breaking. The function was `#[doc(hidden)]`, and those are
not part of the public API. In any case, we bumped the version for other
reasons

cleanup(auth): remove `test_credentials()`

---

.github/workflows/sdk.yaml

In `bash` backticks mean `$()`. I forgot that and used them inside an
interpolated heredoc.

ci: fix major semver message

---

Cargo.lock
Cargo.toml
src/gax-internal/Cargo.toml

Need a new version that depends on gax@1.0.0

chore: bump version for gax-internal

---

.github/workflows/sdk.yaml

The build is very slow for some reason. Maybe a regression in rustdoc.
In any case, I do not expect that building all the clients will catch
any problems vs. building a few clients

ci: trim docs build with `rust:nightly`

---

doc/rustdocfx/go.mod
doc/rustdocfx/go.sum
doc/rustdocfx/process_docs.go
doc/rustdocfx/process_docs_test.go

Part of the work for #3226 
Introduce a simple parser for markdown. We will use these on the doc strings.
---
For context, this is where we are going: https://github.com/dbolduc/google-cloud-rust/commit/84636a719ce3ed82e70f234546c98a54832619f9
I plan to add the node kinds one at a time to make the reviews easier. But some of the code along the way may seem like overkill.

impl(rustdocfx): introduce markdown parsing for comments

---

doc/rustdocfx/process_docs.go
doc/rustdocfx/process_docs_test.go

Part of the work for #3213 
Handle indented code blocks. Leave them as-is, instead of wrapping them in a fenced code block.
I do not think these currently occur in our docs. We would have to use one in a handwritten comment. (the sidekick proto comment parser converts these to fenced code blocks). I already wrote the code and a test though, so let's commit it.

impl(docfx): handle code blocks in comments

---

src/gax/src/options.rs

This sets up request-level details for #3239 to select a low cardinality path template to include in span names etc.; the path template is part of the contract for sidekick to populate.

impl(gax): add path_template to RequestOptions

---

src/gax-internal/src/http.rs
src/gax-internal/src/options.rs

This structure forms an API to be populated and added by the generator (like the implementation of x-goog-api-client.)
It will be used by instrumentation to describe the client library itself, for #3239

impl(gax-internal): define InstrumentationClientInfo for tracing

---

Cargo.lock
src/integration-tests/Cargo.toml
src/integration-tests/src/lib.rs
src/integration-tests/src/pubsub.rs
src/integration-tests/tests/driver.rs

Adds a very simple integration test for the TopicAdmin client, adding some setup and cleanup functions that will be useful later when testing the publisher and subscriber.
There is still remaining work to cleanup stale topics that are not deleted because the test failed.
For #3355

test(pubsub): add simple integration test

---

Cargo.lock
src/integration-tests/Cargo.toml
src/integration-tests/src/pubsub.rs

Cleanup stale topics created by integration tests. Pubsub topics don't have a create time field, so instead create a label that records the creation time. There are restrictions on the characters used in labels including no uppercase letters. The wkt::Timestamp serialization uses uppercase letters, so instead this keeps it simple for the tests and stores the time in seconds.
Fixes #3355

test(pubub): add cleanup for pubsub topics

---

src/integration-tests/src/bigquery.rs
src/integration-tests/src/error_details.rs
src/integration-tests/src/firestore.rs
src/integration-tests/src/secret_manager/openapi.rs
src/integration-tests/src/secret_manager/openapi_locational.rs
src/integration-tests/src/sql.rs
src/integration-tests/src/workflows.rs
src/integration-tests/src/workflows_executions.rs
src/integration-tests/tests/driver.rs

Instead of testing every client with/without tracing, and with/without a custom retry policy, just test these dimensions in `secretmanager`, `storagecontrol`.
By default, enable tracing in the clients. We would like to know if anything goes wrong.
Note that we don't need to set the retry policy, as clients come with a default policy now.

cleanup: reduce integration test matrix wrt client config

---

src/gax-internal/src/observability.rs

impl(gax-internal): Define OpenTelemetry key constants for HttpSpanInfo

---

src/auth/integration-tests/src/lib.rs
src/auth/integration-tests/tests/driver.rs

Minor improvement on the external account integration test, where it was not explicitly raising the error when failing to generate id tokens. I was setting up accounts to run those tests locally and the error was not showing up. 
This PR also fixes a warning on importing the `test_case` crate only on when `run-byoid-integration-tests` feature is enabled.

test(auth): raise error when id token generation fails

---

src/integration-tests/src/storage.rs

In tests, prefer retrying -- which may return an error on duplicate
requests -- over failing on the first transient error. At least we
should get a more meaningful error with the new approach.
Part of the work for #3412

test(storage): deflake integration tests

---

.github/workflows/sdk.yaml
src/generated/cloud/compute/v1/src/lib.rs
src/generated/cloud/compute/v1/src/model.rs

This time with support for deprecated elements in a discovery doc
specification.

chore: update sidekick version

---

dart/packages/google_cloud_gax/lib/gax.dart
dart/packages/google_cloud_gax/test/client_test.dart

The generator code that uses this looks like:
https://github.com/googleapis/librarian/compare/main...brianquinlan:librarian:generate_stream?expand=1
When we launch `package:google_cloud_ai_generativelanguage_v1`, the only method that supports streaming will look like:
```dart
/// Generates a [streamed response](https://ai.google.dev/gemini-api/docs/text-generation?lang=python#generate-a-text-stream)
/// from the model given an input `GenerateContentRequest`.
Stream<GenerateContentResponse> streamGenerateContent(
GenerateContentRequest request,
) {
final url = Uri.https(_host, '/v1/${request.model}:streamGenerateContent');
return _client
.postStreaming(url, body: request)
.map(GenerateContentResponse.fromJson);
}
```

feat: Add support for APIs that use server-sent events (SSE)

---

Cargo.lock
Cargo.toml
src/gax-internal/Cargo.toml
src/gax-internal/src/observability.rs
src/integration-tests/Cargo.toml
src/test-utils/Cargo.toml
src/test-utils/src/lib.rs
src/test-utils/src/test_layer.rs

This change introduces a dedicated test utility, `TestLayer`, to reliably capture and isolate tracing spans within individual test cases, especially in async contexts.
Key changes in `google-cloud-gax-internal/src/observability.rs`:
-   **New `test_layer` Module:** Encapsulates all test-specific tracing
infrastructure, including the `TestLayer`, `CapturedSpanLog`, and
`TestVisitor`. This module is marked `#[cfg(test)]`.
-   **`TestLayer::initialize()`:** Provides an RAII guard to install the
`TestLayer` as a global subscriber for the duration of a test. It uses
a unique `test_id` to isolate captured spans.
-   **`TestLayer::capture()`:** A new public API to retrieve spans
captured for a specific `test_id`.
-   **Improved Isolation:** `CapturedSpanLog` and the global `SPAN_LOG`
instance …

feat(test): TestLayer for async tests

---

src/gax-internal/src/grpc/from_status.rs

The Google Cloud load balancer can respond with HTML or XML messages if
the target endpoint is invalid, e.g. `not-a-service.googleapis.com`, or
if the target endpoint does not match the service, e.g. using
`pubsub.googleapis.com` to call Cloud Storage RPCs.
This change generates a better error message in these cases, which we
hope makes troubleshooting easier.
----
Fixes #3460
From:
```
ERROR the service reports an error with code INTERNAL described as: protocol error: received message with invalid compression flag: 60 (valid flags are 0 and 1) while receiving response with status: 400 Bad Request
```
To:
```
ERROR the transport reports an error: unexpected value in content-type header, should start with application/grpc. In Google Cloud, this is a common problem when using an invalid …
```

fix(gax-internal): better gRPC error messages

---

src/gax-internal/src/grpc.rs
src/gax-internal/src/host.rs
src/gax-internal/src/http.rs
src/gax-internal/src/lib.rs
src/integration-tests/tests/driver.rs

Fixes #3375 
Use locational endpoints as the `:authority` field in gRPC requests, instead of the default. An analog to #3402, but for gRPC.
I couldn't reproduce this with GCS. I think it was forgiving of trying to access locational resources from a global endpoint. And I did not want to [restrict global endpoint usage](https://cloud.google.com/assured-workloads/docs/restrict-endpoint-usage) in our test project.
I tested locally with `aiplatform`, and saw the same behavior we see over HTTP. https://github.com/dbolduc/google-cloud-rust/commit/381b5fe4130da304672df7b34a60187b7fb1e80b

fix(storage): respect locational endpoints
